#!/usr/bin/env python3
"""Levels -> Project Bean backgrounds, for port/src/gebeanstagetable.h.

A row is keyed by GoldenEye's own key for the level (gefiles.LEVELS), which is
the name the conversion writes the level under: files/bgdata/bg_gx<key>.seg,
the same file for the arena and for the solo mission on it. That is all the
port needs to know it: the conversion is GoldenEye's own geometry, which is
what Bean's HD mesh was built on, so nothing about the rooms is measured at run
time. (Rows were keyed by room count and a hash of the room positions until
2026-09-22, when Streets was found to have silently lost its HD - its rooms had
moved since the hash was taken - and the 24 GoldenEye X levels that pairing
also served were dropped: GE Plus is built from the ROM alone.)

Each row gives:
- the Bean background (files/new/background/<name>), and the scale that takes
  Bean's units to the level file's: Bean's own file is GoldenEye's units times
  a scale of its own (beanscales.json, beancover.py), and the
  conversion is GoldenEye's units divided by the level scale
- the offset the conversion takes off, which moves the middle of a level's
  walkable area to the origin (geconvert.c; arenas.json is written
  by `GE_ARENAS_JSON=... geconvert.py OUTDIR`). It follows from the ROM's own
  stan and level scale alone, so a change to the conversion's geometry cannot
  move it - but a change to that re-centring would, and this table with it.

GoldenEye X's own levels are not emitted. The docstring used to say they kept
their rows "as a homage to the mod" (the user, 2026-09-22), keyed by room count
and an FNV-1a of the rooms' positions out of stagetable.json (stagefit_all.py:
every Bean N64-look level against every GE-X bg file, scale and translation by
trimmed ICP; the matches all have zero translation) - but this script never
reads stagetable.json, and the header has only the GoldenEye-key rows below.
stagetable.json and stagefit_all.json are kept as the record of that fit.

    gen_stagetable.py [-o OUT]     (default port/src/gebeanstagetable.h; -o - is stdout)
"""
import json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths
import gefiles

sys.stdout = paths.output(paths.repo('port/src/gebeanstagetable.h'))

# Bean's N64-look mesh has to lie on GoldenEye's own vertices for the level to
# be the same level: 4J remodelled Statue Park, whose best fit is 0%
MIN_COVER = 0.3

scales = json.load(open(paths.data('beanscales.json')))
offsets = json.load(open(paths.data('arenas.json')))

print("// Generated by tools/geconvert/fit/gen_stagetable.py - do not edit.")
print("// { GoldenEye's key for the level, Bean background, Bean units -> file units,")
print("//   then less the offset the conversion took off }")

for key in sorted(gefiles.LEVELS):
    if key not in scales or key not in offsets:
        print("\t// %s: no GoldenEye XBLA level was looked for" % key)
        continue

    s, o = scales[key], offsets[key]

    if s['cover'] < MIN_COVER:
        print("\t// %s: GoldenEye XBLA's %s is a remodel, not this level (%.0f%% of it)"
              % (key, s['bean'], s['cover'] * 100))
        continue

    print('\t{ "%s", "%s", %.9ff, { %.1ff, %.1ff, %.1ff } }, // %.0f%% of its vertices' % (
        key, s['bean'], s['scale'] / gefiles.LEVELS[key][4],
        o['offset'][0], o['offset'][1], o['offset'][2], s['cover'] * 100))

