#!/usr/bin/env python3
"""GoldenEye's own characters -> Project Bean assets, for port/src/gebeanchrtable.h.

GE Plus converts all eighty of the ROM's `c_item_entries` characters as
files/Cgx%03dZ (tools/geconvert/gechr.py). 4J built the XBLA release on the
cartridge's own models, so the pairing is the ROM's own file name with the C
and the Z taken off: CredmanZ is files/new/char/redman, CheadkarlZ is
files/new/head/headkarl. Seventy-two of the eighty pair straight across.

Seventy-three with Csuit_lf_handZ, the watch's floating arm (and the gun
barrel's hand), whose release file drops GoldenEye's underscores:
files/new/char/suitlfhand (f405e7c87, 2026-09-27 - the table had said the
release had no such file). RENAMED maps it and notes what it is.

The seven that do not:
- The five Brosnan heads have no usable head file: the release's
  head/headbrosnan is a static N64-style whole figure, and its HD Brosnan is
  the head each Bond body carries on its neck (the same rule gen_beantable.py
  uses for GoldenEye X's two Brosnan heads). Each takes its own outfit's body,
  and the plain one the tuxedo's by elimination - GoldenEye has five Bond
  bodies with a headspot and five Brosnan heads.
- blueman, bluewoman and greyman are broken in the release (BROKEN_SOURCES in
  batch_gex.py) and are left in the N64 look.
- headdave is Dr. Doak's head (HEAD_Male_Dave_Dr_Doak), and the release's
  head/headdave is another man: a clean-shaven face in glasses, where
  GoldenEye's Doak has dark curly hair, a moustache and a goatee (F3
  20260925-225738, Facility: "dr doak using wrong face texture"). No other
  file of the release has his face, so he keeps GoldenEye's own.

A head is a character with no skeleton of its own (one list node); the rest
are bodies, and a body's kind is GoldenEye's own `hashead` flag out of
c_item_entries, which over all eighty is exactly "this model has no HEADSPOT
node": a body that carries its own head takes no grafted one, so its mesh is
the whole character. The release files spicebond under both char and head, so
which directory holds a name does not answer either question.

    gen_chrtable.py [-o OUT]       (default port/src/gebeanchrtable.h; -o - is stdout)
"""
import os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths
import gefiles

sys.stdout = paths.output(paths.repo('port/src/gebeanchrtable.h'))

BEAN = os.path.join(paths.BEAN, 'files/new')

BROKEN = {'blueman', 'bluewoman', 'greyman'}

# Heads whose release file is somebody else's face. headdave is not Doak's
# face, but the user keeps the release's HD head anyway (2026-09-26).
NOT_THEIRS = set()

# GoldenEye's stem -> the release's name for it, and a note for the row
RENAMED = {
    'suit_lf_hand': ('suitlfhand', "the watch's floating arm"),
}

# Kinds that GoldenEye's hashead flag gets wrong for the port. The floating arm
# has hashead 0 but no HEADSPOT either - there is nowhere to graft a head - so
# its mesh is the whole model (f405e7c87).
KIND = {
    'suitlfhand': 'GEBEAN_WHOLE',
}

# The head each Bond body wears, and the body its HD face comes off
BOND_HEADS = {
    'headbrosnanboiler': 'char/boilerbond',
    'headbrosnansuit':   'char/suitbond',
    'headbrosnantimber': 'char/timberbond',
    'headbrosnansnow':   'char/snowbond',
    'headbrosnan':       'char/djbond',
}

chrs = gefiles.rom().chrs()
have = {d: set(os.listdir(os.path.join(BEAN, d))) for d in ('char', 'head')}

print('// Generated by tools/geconvert/fit/gen_chrtable.py - do not edit.')
print('// The conversion\'s file, what the release replaces it with, and GoldenEye\'s own name')

for num, (name, scale, h) in enumerate(chrs):
    stem = name[1:-1] if name[:1] == 'C' and name[-1:] == 'Z' else name
    stem, note = RENAMED.get(stem, (stem, None))
    ishead = h['skeleton'] == 0
    source = BOND_HEADS.get(stem)

    for d in (('head', 'char') if ishead else ('char', 'head')):
        if source is None and stem in have[d]:
            source = '%s/%s' % (d, stem)

    if stem in BROKEN:
        print('\t// %d %s: broken in the release, left in the N64 look' % (num, name))
        continue

    if source is None:
        print('\t// %d %s: the release has no such file' % (num, name))
        continue

    if stem in NOT_THEIRS:
        print('\t// %d %s: the release\'s is another face, left in the N64 look' % (num, name))
        continue

    kind = 'GEBEAN_HEAD' if ishead else 'GEBEAN_WHOLE' if h['hashead'] else 'GEBEAN_BODY'
    kind = KIND.get(stem, kind)
    print('\tCHRROW("Cgx%03dZ", %-14s "%s"), // %s' % (num, kind + ',', source,
                                                    name + (', ' + note if note else '')))
