#!/usr/bin/env python3
"""The GE-X -> Project Bean table for port/src/gebeantable.h, from batch_gex.py's decisions.

Same inputs and rules as batch_gex.py (gemap.json, gexassign.json,
texcompare.json, BROKEN_SOURCES, ties), but instead of converting it writes
one C row per GE-X file: its name, what its list nodes and vertices add up to
(so a different mod's file with the same name is not taken), and the Bean
asset that replaces it.

    gen_beantable.py [-o OUT]      (default port/src/gebeantable.h; -o - is stdout)
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths
from batch_gex import HERE, BEAN, GEX, BROKEN_SOURCES, apply_textures
from bean2obj import Model
from pdmodel import PdModel, load

KIND_BODY, KIND_BODYHEAD, KIND_HEAD = 'GEBEAN_BODY', 'GEBEAN_BODY_WITH_HEAD', 'GEBEAN_HEAD'

# GoldenEye's Bond heads are head files of their own, but Bean's head/headbrosnan
# is a static N64-style full figure; its HD Brosnan is the head every Bond body
# carries on its neck. GE-X's two Brosnan heads (by vertex arrays: headbrosnan
# and headbrosnansuit) take it from the body of the same outfit. Its four Classic
# heads (Cheadneil2Z, CheadtrentZ, CheadpennyZ, CheadjonZ) are the same mesh
# painted as other Bonds, which Bean has no HD face for.
BOND_HEADS = {'CheadcarringtonZ': 'char/djbond', 'Ca51faceplateZ': 'char/suitbond'}


def signature(fn):
    m = PdModel(load(os.path.join(GEX, fn)))
    return len(m.listnodes), sum(len(ln['verts']) for ln in m.listnodes)


def main():
    sys.stdout = paths.output(paths.repo('port/src/gebeantable.h'))
    gemap = json.load(open(os.path.join(HERE, 'gemap.json')))
    gemap.pop('_arrays')
    assign = json.load(open(os.path.join(HERE, 'gexassign.json')))
    notes = []
    apply_textures(assign, lambda s: notes.append(s))

    headclaim = {}
    for ge, per in gemap.items():
        for fn, v in per.items():
            n = v['joints'].get('3', 0)
            if fn.startswith('Chead') and n:
                if fn not in headclaim or n > headclaim[fn][1] or (n == headclaim[fn][1] and ge < headclaim[fn][0]):
                    headclaim[fn] = (ge, n)

    rows = []
    for fn, a in sorted(assign.items()):
        ge = a['best']
        if fn.startswith('Chead') or a['nodes'] != 25 or a['score'] < 0.5 or ge in BROKEN_SOURCES:
            continue
        if not os.path.exists(os.path.join(BEAN, 'char', ge, 'default.bin')):
            continue
        heads = sorted(h for h, (g, _) in headclaim.items() if g == ge)
        rows.append((fn, KIND_BODYHEAD if heads else KIND_BODY, 'char/' + ge))
        for h in heads:
            rows.append((h, KIND_HEAD, 'char/' + ge))

    for fn, a in sorted(assign.items()):
        ge = a['best']
        if not fn.startswith('Chead') or fn in headclaim or not ge or len(a['tied']) > 1:
            continue
        path = os.path.join(BEAN, 'head', ge, 'default.bin')
        if not ge.startswith('head') or not os.path.exists(path):
            continue
        m = Model(path)
        if not m.remap or len(m.pose) != 16:
            continue
        rows.append((fn, KIND_HEAD, 'head/' + ge))

    for fn, src in BOND_HEADS.items():
        rows.append((fn, KIND_HEAD, src))

    print('/* Generated by tools/geconvert/fit/gen_beantable.py - GE-X 6a model files and')
    print(' * the Project Bean assets that replace them. See CLAUDE-notes/ge-bean.md. */')
    print('')
    # A head claimed by a GoldenEye character that two GE-X bodies take comes
    # out once per body; it is one file.
    for fn, kind, src in sorted(set(rows)):
        nodes, verts = signature(fn)
        print('\t{ "%s", %d, %d, %s, "%s" },' % (fn, nodes, verts, kind, src))
    print('/* %d rows */' % len(rows), file=sys.stderr)


if __name__ == '__main__':
    main()
