#!/usr/bin/env python3
"""port/src/geproptable.h from propfit.json: the GoldenEye remake's prop model
files (Pgx<GoldenEye model number>Z, geconvert.py) and the Bean HD prop drawn on
each, as gebeanBuildRigid() lays a pickup: axis k of the result is sign[k] *
Bean axis perm[k], centred on beancentre, scaled and moved to n64centre - here
in the space of the model's first list node's matrix, which is what the rigid
build puts every vertex on, so the origins of the groups over that list are
taken off the model-space fit. A fit scoring under 0.6 is left out (desk1 and
chrplastique match nothing of GoldenEye's).

EXCLUDE: fitted, but drawn wrong or drawn by another table: the guns' props
(GUN_PROPS, below) and the intro's logo (2026-09-30). Before those it was empty from
feat/ge-hd-gas-tank (2026-09-26): the gas tank (117) was left out by
fix/f3-hd-prop-textures because its material is three pictures the shader
blends (a dark spot map, a landscape reflection, a pale base) - the biggest
alone drew GoldenEye's black bottling-room tanks white. gebean.c now draws the
landscape through the spot map as a reflection and takes GoldenEye's shade
under the pale picture (beanReflectPicture(), beanStockShade()).

The three autoguns (98 roofgun, 292 gun_runway1, 299 groundgun) were excluded
with it until fix/f3-runway-emplacement-hd (2026-09-26): their barrels hang
off parts nested under the turret, which the rigid build binds only with the
second binding pass of c80118821 (fix/f3-tank-aim-fire, "HD tank's barrel
turns with its turret"). With that pass every moving bone lands on its part
(gunrunway1: body on part 1, barrel on part 3; groundgun and roofgun: yaw,
pitch and barrels each on their own); without it the barrels ride the yaw.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths
import json, struct
import numpy as np
import gefiles, gemodelconv

OUT = paths.repo('port/src/geproptable.h')   # -o OUT, or -o - for stdout
SEG = 0x05000000


def first_list_origin(name):
    h = gemodelconv.header(name)
    fname, _ = gemodelconv.prop_record(name)
    d = gefiles.rom_file('P%sZ' % fname)
    u = lambda o: struct.unpack_from('>I', d, o)[0]

    def walk(o, origin):
        while o:
            t = struct.unpack_from('>H', d, o)[0]
            ro = u(o + 4) - SEG
            here = origin
            if t in (0x02, 0x15):
                here = origin + np.array(struct.unpack_from('>3f', d, ro))
            elif t in (0x04, 0x18, 0x16):
                return here
            child = u(o + 20)
            if child:
                got = walk(child - SEG, here)
                if got is not None:
                    return got
            nxt = u(o + 12)
            o = nxt - SEG if nxt else 0
        return None
    return walk(4 * h['numswitches'] + 12 * h['numtextures'], np.zeros(3))


# GoldenEye's guns' own props (PROP_CHR*): each already has a row in
# gegunstable.h, fitted by gunfit2.py on the release's HD gun, which
# gebeanPoolRowForFile() finds for a Pgx<prop>Z only when no prop row matches
# it first. A propfit row (fitted on the release's N64-look copy) would take
# its place on every guard's gun, floor pickup and the intro's PP7 - the Golden
# Gun came out silver and half as big again (2026-09-30, Egyptian).
GUN_PROPS = {184, 185, 186, 187, 189, 190, 191, 192, 193, 194, 195, 196, 199, 200, 201,
             204, 205, 206, 208, 209, 210}

EXCLUDE = set(GUN_PROPS) | {
    # goldeneyelogo: only the intro draws Pgx277Z, as GoldenEye's gold under
    # the Level Metal pass (geintro.c, introLogoMetal()); the release's prop
    # put a flat orange ramp in its place in the HD look (2026-09-30)
    277,
}


def main():
    fit = json.load(open(paths.data('propfit.json')))
    names = gemodelconv.prop_names()
    out = ['// Generated by tools/geconvert/fit/gen_proptable.py from propfit.json - do not edit.',
           '// file, source, perm[3], sign[3], scale, beancentre[3], n64centre[3] (first list matrix space)']
    for k in sorted(fit, key=int):
        f = fit[k]
        if f['score'] < 0.6 or int(k) in EXCLUDE:
            continue
        origin = first_list_origin(names[int(k)])
        centre = np.array(f['n64centre']) - (origin if origin is not None else 0)
        out.append('\tPROPROW("Pgx%03dZ", "prop/%s", %s, %s, %.5ff, %s, %s), // %s, %.0f%%' % (
            int(k), f['bean'], ', '.join(map(str, f['perm'])), ', '.join(map(str, f['sign'])), f['scale'],
            ', '.join('%.2ff' % x for x in f['beancentre']), ', '.join('%.2ff' % x for x in centre),
            names[int(k)], f['score'] * 100))
    paths.output(OUT).write('\n'.join(out) + '\n')
    print(len(out) - 2, 'rows', file=sys.stderr)


if __name__ == '__main__':
    main()
