#!/usr/bin/env python3
"""Write port/src/gegunstable.h from gunfit.json (see the header's comment).

gunfit.json comes from gunfit2.py, which lays each Bean pickup on the GoldenEye
decomp's N64 pickup: one rotation for all of them (perm (1,0,2), sign (1,-1,1)
- Bean y is the barrel and GoldenEye x is), the scale from their extents along
GoldenEye's longest axis, and the translation by trimmed ICP.

The throwing knife takes that rotation too since f15515659: gunfit2.py no
longer turns it a half turn (see HALF_TURN there for why), so its gunfit.json
row is the canonical fit and nothing here special-cases it.
"""
import json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths

OUT = paths.repo('port/src/gegunstable.h')   # -o OUT, or -o - for stdout

ROWS = [  # weapon, alias file, gunfit key (also Bean's prop/<name>)
    ('WEAPON_GE_PP7', 'PchrgePP7Z', 'chrwppk'),
    ('WEAPON_GE_PP7SILENCED', 'PchrgePP7silZ', 'chrwppksil'),
    ('WEAPON_GE_DD44', 'PchrgeDD44Z', 'chrtt33'),
    ('WEAPON_GE_KLOBB', 'PchrgeKlobbZ', 'chrskorpion'),
    ('WEAPON_GE_KF7SOVIET', 'PchrgeKF7Z', 'chrkalash'),
    ('WEAPON_GE_ZMG', 'PchrgeZMGZ', 'chruzi'),
    ('WEAPON_GE_D5K', 'PchrgeD5KZ', 'chrmp5k'),
    ('WEAPON_GE_D5KSILENCED', 'PchrgeD5KsilZ', 'chrmp5ksil'),
    ('WEAPON_GE_PHANTOM', 'PchrgePhantomZ', 'chrspectre'),
    ('WEAPON_GE_AR33', 'PchrgeAR33Z', 'chrm16'),
    ('WEAPON_GE_RCP90', 'PchrgeRCP90Z', 'chrfnp90'),
    ('WEAPON_GE_SHOTGUN', 'PchrgeShotgunZ', 'chrshotgun'),
    ('WEAPON_GE_AUTOSHOTGUN', 'PchrgeAutoShotgunZ', 'chrautoshot'),
    ('WEAPON_GE_SNIPERRIFLE', 'PchrgeSniperZ', 'chrsniperrifle'),
    ('WEAPON_GE_COUGARMAGNUM', 'PchrgeCougarZ', 'chrruger'),
    ('WEAPON_GE_GOLDENGUN', 'PchrgeGoldenGunZ', 'chrgolden'),
    ('WEAPON_GE_MOONRAKER', 'PchrgeMoonrakerZ', 'chrlaser'),
    ('WEAPON_GE_GRENADELAUNCHER', 'PchrgeGrenadeLauncherZ', 'chrgrenadelaunch'),
    ('WEAPON_GE_ROCKETLAUNCHER', 'PchrgeRocketLauncherZ', 'chrrocketlaunch'),
    ('WEAPON_GE_HUNTINGKNIFE', 'PchrgeKnifeZ', 'chrknife'),
    ('WEAPON_GE_THROWINGKNIFE', 'PchrgeThrowingKnifeZ', 'chrthrowknife'),
    ('WEAPON_GE_GRENADE', 'PchrgeGrenadeZ', 'chrgrenade'),
    ('WEAPON_GE_TIMEDMINE', 'PchrgeTimedMineZ', 'chrtimedmine'),
    ('WEAPON_GE_PROXIMITYMINE', 'PchrgeProximityMineZ', 'chrproximitymine'),
    ('WEAPON_GE_REMOTEMINE', 'PchrgeRemoteMineZ', 'chrremotemine'),
]


def main():
    fit = json.load(open(paths.data('gunfit.json')))
    out = [
        '// Generated by tools/geconvert/fit/gen_guntable.py from gunfit.json: each of',
        "// GoldenEye's guns, the file its pickup model is an alias to, Bean's pickup",
        '// (files/new|original/prop/<source>), and how Bean\'s pickup is laid onto',
        "// GoldenEye's N64 one, whose frame is Perfect Dark's: axis k of the result is",
        '// sign[k] * Bean axis perm[k], centred on beancentre, scaled, and moved to',
        '// n64centre. One rotation for all of them, the throwing knife included:',
        '// GoldenEye models it 180 degrees from its hunting knife, held by the blade',
        "// with the handle up, and so is it drawn (gunfit2.py's HALF_TURN, which held",
        "// it by the handle, is not applied to this row any more); the scale is the two",
        "// extents along GoldenEye's longest axis and the translation a trimmed ICP",
        '// (gunfit2.py).',
        '// weapon, file, source, perm[3], sign[3], scale, beancentre[3], n64centre[3]',
    ]
    for weapon, alias, key in ROWS:
        g = fit[key]
        floats = lambda v: ', '.join('%.2ff' % x for x in v)
        out.append('\tGUNROW(%s, "%s", "prop/%s", %s, %s, %.5ff, %s, %s),' % (
            weapon, alias, key, ', '.join(map(str, g['perm'])), ', '.join(map(str, g['signs'])),
            g['scale'], floats(g['beancentre']), floats(g['n64centre'])))
    paths.output(OUT).write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
