#!/usr/bin/env python3
"""
Writes port/fast3d/post/gfx_post_src.h: the vendored SMAA and FSR 1 shader
sources in port/fast3d/post/ as C strings, so both renderers can compile them
at run time. Run it again after replacing any of the three files.

    python3 tools/postshaders/gen.py
"""

import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', '..'))
POST = os.path.join(ROOT, 'port', 'fast3d', 'post')

FILES = [
    ('gfx_post_smaa_src', 'SMAA.hlsl'),
    ('gfx_post_ffx_a_src', 'ffx_a.h'),
    ('gfx_post_ffx_fsr1_src', 'ffx_fsr1.h'),
]


def literal(line):
    out = []
    for ch in line:
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif ch == '\t':
            out.append('    ')
        elif ' ' <= ch <= '~':
            out.append(ch)
        # anything else (the odd Latin-1 byte in a comment) is dropped
    return '"' + ''.join(out) + '\\n"'


def main():
    lines = [
        '// Generated by tools/postshaders/gen.py from the files beside it. Do not edit.',
        '#pragma once',
        '',
    ]
    for name, fname in FILES:
        with open(os.path.join(POST, fname), 'rb') as f:
            text = f.read().decode('latin-1').replace('\r\n', '\n').replace('\r', '\n')
        lines.append('static const char %s[] =' % name)
        for line in text.split('\n'):
            # GLSL before 4.20 has no line continuation, and SMAA's banner is
            # ASCII art with backslashes at the ends of its lines; no macro in
            # any of the three continues a line, so none is lost
            lines.append('    ' + literal(line.rstrip().rstrip('\\')))
        lines[-1] += ';'
        lines.append('')
    with open(os.path.join(POST, 'gfx_post_src.h'), 'w', newline='\n') as f:
        f.write('\n'.join(lines))


if __name__ == '__main__':
    main()
