#!/usr/bin/env python3
"""Generates port/include/xbla4jintro.h: 4J's own animation of the Perfect Dark
logo stage, from the curves curves4j.py reads out of a draw log of the Xbox 360
release running in Xenia (see README in this directory).

    gen4jtable.py curves.csv port/include/xbla4jintro.h

Stage time in the header is the port's: ticks since the stage started, the
4J Studios card included. The log's clock starts at the stage's first drawn
frame; the cubes' scale is 0.3 + rate * t in 4J's time and reads 0.3 about two
ticks before that frame, so the log's ticks are shifted by that much.

What is linear in the log (scale, the name's fade, the red cube's fade, the
Perfect Dark cube's stretch and fade) is fitted and written as constants. The
spin and the pitch are not simple curves, so they are written per tick,
resampled from the frames and smoothed over five ticks where they move, which
takes out the capture's timing jitter (about a third of a tick) and nothing of
the curve.
"""
import csv, sys, math
import numpy as np

rows = list(csv.DictReader(open(sys.argv[1])))
out = sys.argv[2]
t = np.array([float(r['tick']) for r in rows])
col = lambda k: np.array([float(r[k]) for r in rows])


def linfit(y, lo, hi):
    m = (y > lo) & (y < hi)
    a, b = np.polyfit(t[m], y[m], 1)
    return a, b


scale = col('scale')
rate, s0 = linfit(scale, 0.30, 0.4999)
tau0 = (s0 - 0.3) / rate           # ticks to add to the log's clock: it reads 0.3 at -tau0
tau = t + tau0


def crossing(y, value, lo, hi):
    a, b = linfit(y, lo, hi)
    return (value - b) / a + tau0


text_start = crossing(col('text_a'), 1.0, 0.0001, 0.9999)
text_end = crossing(col('text_a'), 0.0, 0.0001, 0.9999)
morph_start = crossing(col('pdy'), 0.5, 0.5001, 0.9999)
morph_end = crossing(col('pdy'), 1.0, 0.5001, 0.9999)
red_start = crossing(col('red_a'), 1.0, 0.0001, 0.9999)
red_end = crossing(col('red_a'), 0.0, 0.0001, 0.9999)

spin = col('spin')
pitch = col('pitch')
# The card: the pose holds still until the spin starts.
card_ticks = int(math.floor(tau[np.argmax(spin > 0.01)]))
end_tick = int(math.ceil(tau[np.argmax(spin >= 719.999)])) + 2
ticks = np.arange(0, end_tick)
spin_t = np.interp(ticks, tau, spin, left=0.0, right=720.0)
pitch_t = np.interp(ticks, tau, pitch, left=90.0, right=0.0)


def smooth(v, lo, hi):
    moving = (v > lo) & (v < hi)
    k = np.convolve(v, np.ones(5) / 5.0, mode='same')
    v = np.where(moving, k, v)
    return np.clip(v, lo, hi)


spin_t = np.maximum.accumulate(smooth(spin_t, 0.0, 720.0))
pitch_t = np.minimum.accumulate(smooth(pitch_t, 0.0, 90.0))


def table(name, v):
    lines = []
    for i in range(0, len(v), 8):
        lines.append('\t' + ' '.join('%.3ff,' % x for x in v[i:i + 8]))
    return 'static const f32 %s[XBLA4J_TABLE_TICKS] = {\n%s\n};\n' % (name, '\n'.join(lines))


with open(out, 'w') as f:
    f.write('''#ifndef _IN_XBLA4JINTRO_H
#define _IN_XBLA4JINTRO_H

/**
 * 4J's animation of the Perfect Dark logo stage in the Xbox 360 release,
 * GENERATED by tools/xblaintro/gen4jtable.py from the release's own draw calls
 * logged in Xenia. Do not edit; regenerate.
 *
 * Times are ticks since the stage started, the 4J Studios card included. Both
 * cubes share one pose: pitch about the screen's horizontal, spin about the
 * cube's own up axis, uniform scale in the title camera the N64 uses (fov 46,
 * distance 4000), which is the camera 4J kept.
 */

// The 4J Studios card: the pose holds still until the spin starts.
#define XBLA4J_CARD_TICKS       %d

#define XBLA4J_SCALE_START      0.3f
#define XBLA4J_SCALE_PER_TICK   %.9ff
#define XBLA4J_SCALE_END        0.5f

// The name fades from 1 to 0.
#define XBLA4J_TEXT_FADE_START  %.2ff
#define XBLA4J_TEXT_FADE_END    %.2ff

// The Perfect Dark cube stretches from half height to its own, and fades in.
#define XBLA4J_MORPH_START      %.2ff
#define XBLA4J_MORPH_END        %.2ff

// The red cube fades from 1 to 0.
#define XBLA4J_RED_OUT_START    %.2ff
#define XBLA4J_RED_OUT_END      %.2ff

// Degrees, one a tick; held at the last value after the table.
#define XBLA4J_TABLE_TICKS      %d

''' % (card_ticks, rate, text_start, text_end, morph_start, morph_end, red_start, red_end, end_tick))
    f.write(table('g_Xbla4JSpinDeg', spin_t))
    f.write('\n')
    f.write(table('g_Xbla4JPitchDeg', pitch_t))
    f.write('\n#endif\n')

print('tau0 %.2f  card %d  scale rate %.9f  text %.2f..%.2f  morph %.2f..%.2f  red %.2f..%.2f  table %d ticks' % (
    tau0, card_ticks, rate, text_start, text_end, morph_start, morph_end, red_start, red_end, end_tick))
