// Generated by .xbla-work/ge-bean/gen_stagetable.py - do not edit.
// { GoldenEye's key for the level, Bean background, Bean units -> file units,
//   then less the offset the conversion took off }
	{ "arch", "archives", 1.072400836f, { -1474.0f, 215.0f, -1725.0f } }, // 95% of its vertices
	{ "arec", "control", 1.616580623f, { -269.0f, 259.0f, -1485.0f } }, // 96% of its vertices
	{ "ark", "facility", 0.531318270f, { 4509.0f, -106.0f, -1063.0f } }, // 99% of its vertices
	{ "azt", "aztec", 1.475407422f, { -129.0f, -61.0f, 1389.0f } }, // 85% of its vertices
	{ "base", "library", 0.573907333f, { -804.0f, 29.0f, -1033.0f } }, // 100% of its vertices
	{ "cave", "cavern", 0.501072787f, { 535.0f, -1467.0f, -2213.0f } }, // 98% of its vertices
	{ "crad", "cradle", 1.828668257f, { 1495.0f, -3750.0f, 1169.0f } }, // 99% of its vertices
	{ "cryp", "temple", 0.921010121f, { -738.0f, -322.0f, -3224.0f } }, // 82% of its vertices
	{ "dam", "dam", 4.280101153f, { 3390.0f, -13219.0f, -8584.0f } }, // 92% of its vertices
	{ "depo", "depot", 0.805820509f, { 982.0f, -25.0f, -4916.0f } }, // 99% of its vertices
	{ "dest", "frigate", 0.821433927f, { -123.0f, 508.0f, -2334.0f } }, // 92% of its vertices
	{ "dish", "multitemple", 3.119410587f, { 935.0f, 0.0f, -312.0f } }, // 99% of its vertices
	{ "jun", "jungle", 0.706146978f, { 10590.0f, 956.0f, -5255.0f } }, // 69% of its vertices
	{ "lib", "library", 0.573907333f, { -804.0f, 29.0f, -1033.0f } }, // 100% of its vertices
	{ "oat", "caves", 0.715800060f, { 20067.0f, 1361.0f, -6890.0f } }, // 99% of its vertices
	{ "pete", "streets", 1.239411313f, { 2881.0f, -32.0f, 15462.0f } }, // 85% of its vertices
	{ "ref", "complex", 0.401740938f, { 241.0f, 0.0f, 602.0f } }, // 99% of its vertices
	{ "run", "runway", 0.508383572f, { 11259.0f, -441.0f, -14441.0f } }, // 88% of its vertices
	{ "sev", "bunker", 0.429214082f, { 6.0f, 467.0f, -1864.0f } }, // 93% of its vertices
	{ "sevb", "bunker2", 0.429214887f, { 6.0f, 462.0f, -1624.0f } }, // 97% of its vertices
	{ "sevx", "surface", 0.497385395f, { -5604.0f, -168.0f, -10382.0f } }, // 85% of its vertices
	{ "sevxb", "surface", 0.497385395f, { -5604.0f, -168.0f, -10382.0f } }, // 85% of its vertices
	{ "silo", "silo", 0.615140709f, { 1315.0f, -1173.0f, 1374.0f } }, // 98% of its vertices
	{ "stack", "library", 0.573907333f, { -804.0f, 29.0f, -1033.0f } }, // 100% of its vertices
	// stat: GoldenEye XBLA's statuepark is a remodel, not this level (0% of it)
	{ "tra", "train", 1.300371514f, { -16592.0f, 50.0f, 50.0f } }, // 91% of its vertices
