// Generated by .xbla-work/ge-bean/gen_stagetable.py - do not edit.
// { rooms, room position hash, Bean background, Bean units -> file units }
	{  35, 0x106e2092, "frigate", 0.821435f }, // GE-X bg_arec, 75% of its vertices
	{  95, 0x2943d475, "aztec", 1.475392f }, // GE-X bg_ash, 49% of its vertices
	{  26, 0x12a8fb2b, "aztec", 1.475350f }, // GE-X bg_crad, 46% of its vertices
	{  91, 0x724dc342, "depot", 0.805822f }, // GE-X bg_dam, 14% of its vertices
	{  87, 0x4e4224f1, "silo", 0.615138f }, // GE-X bg_depo, 74% of its vertices
	{  45, 0x0293fe7b, "temple", 0.921026f }, // GE-X bg_dest, 19% of its vertices
	{  80, 0x0eed22be, "facility", 0.531320f }, // GE-X bg_ear, 96% of its vertices
	{  40, 0x5a61c949, "surface", 0.497386f }, // GE-X bg_eld, 72% of its vertices
	{  36, 0x0a64a71f, "archives", 1.072435f }, // GE-X bg_jun, 89% of its vertices
	{  92, 0x33aef8f7, "control", 1.616582f }, // GE-X bg_lee, 83% of its vertices
	{  60, 0x8f48322c, "frigate", 0.821432f }, // GE-X bg_lue, 69% of its vertices
	{  37, 0xa45850e7, "library", 0.573911f }, // GE-X bg_mp10, 100% of its vertices
	{  45, 0xf246f5c6, "temple", 0.921028f }, // GE-X bg_mp11, 20% of its vertices
	{  53, 0xbe93e668, "library", 0.573896f }, // GE-X bg_mp12, 98% of its vertices
	{  27, 0x50d814d0, "archives", 1.072424f }, // GE-X bg_mp16, 84% of its vertices
	{  93, 0x3463b625, "library", 0.573896f }, // GE-X bg_mp4, 98% of its vertices
	{  48, 0xde7a5106, "cavern", 0.501076f }, // GE-X bg_mp9, 45% of its vertices
	{  26, 0x368a19f7, "multitemple", 3.119334f }, // GE-X bg_oat, 92% of its vertices
	{  33, 0x5202b734, "bunker", 0.429208f }, // GE-X bg_pete, 78% of its vertices
	{  45, 0xf8c64745, "complex", 0.401741f }, // GE-X bg_ref, 98% of its vertices
	{  67, 0x5bd8a738, "archives", 1.072412f }, // GE-X bg_rit, 75% of its vertices
	{  68, 0x636d4efb, "cavern", 0.501074f }, // GE-X bg_sho, 40% of its vertices
	{  71, 0x20f0f98c, "bunker2", 0.429208f }, // GE-X bg_tra, 86% of its vertices
	{  39, 0xd176ef00, "cradle", 1.828757f }, // GE-X bg_wax, 18% of its vertices
