// Generated by .xbla-work/ge-bean/gen_guntable.py from gunfit.json: each of
// GoldenEye's guns, the file its pickup model is an alias to, Bean's pickup
// (files/new|original/prop/<source>), and how Bean's pickup is laid onto
// GoldenEye's N64 one, whose frame is Perfect Dark's: axis k of the result is
// sign[k] * Bean axis perm[k], centred on beancentre, scaled, and moved to
// n64centre. One rotation for all of them; the scale is the two extents along
// GoldenEye's longest axis and the translation a trimmed ICP (gunfit2.py).
// weapon, file, source, perm[3], sign[3], scale, beancentre[3], n64centre[3]
	GUNROW(WEAPON_GE_PP7, "PchrgePP7Z", "prop/chrwppk", 1, 0, 2, 1, -1, 1, 0.23791f, 0.00f, 0.00f, 0.00f, 296.92f, -288.47f, -50.33f),
	GUNROW(WEAPON_GE_PP7SILENCED, "PchrgePP7silZ", "prop/chrwppksil", 1, 0, 2, 1, -1, 1, 0.21189f, 0.00f, 0.00f, 0.00f, 279.70f, -257.90f, -49.78f),
	GUNROW(WEAPON_GE_DD44, "PchrgeDD44Z", "prop/chrtt33", 1, 0, 2, 1, -1, 1, 0.22423f, 0.00f, 0.00f, 0.00f, 278.34f, -273.38f, -52.63f),
	GUNROW(WEAPON_GE_KLOBB, "PchrgeKlobbZ", "prop/chrskorpion", 1, 0, 2, 1, -1, 1, 0.19972f, 0.00f, 0.00f, 0.00f, 293.25f, -223.07f, -81.78f),
	GUNROW(WEAPON_GE_KF7SOVIET, "PchrgeKF7Z", "prop/chrkalash", 1, 0, 2, 1, -1, 1, 0.19046f, 0.00f, 0.00f, 0.00f, 353.08f, -214.35f, -60.43f),
	GUNROW(WEAPON_GE_ZMG, "PchrgeZMGZ", "prop/chruzi", 1, 0, 2, 1, -1, 1, 0.21530f, 0.00f, 0.00f, 0.00f, 232.57f, -242.15f, -65.74f),
	GUNROW(WEAPON_GE_D5K, "PchrgeD5KZ", "prop/chrmp5k", 1, 0, 2, 1, -1, 1, 0.24750f, 0.00f, 0.00f, 0.00f, 350.75f, -280.09f, -145.37f),
	GUNROW(WEAPON_GE_D5KSILENCED, "PchrgeD5KsilZ", "prop/chrmp5ksil", 1, 0, 2, 1, -1, 1, 0.21674f, 0.00f, 0.00f, 0.00f, 290.67f, -246.27f, -129.98f),
	GUNROW(WEAPON_GE_PHANTOM, "PchrgePhantomZ", "prop/chrspectre", 1, 0, 2, 1, -1, 1, 0.21712f, 0.00f, 0.00f, 0.00f, 366.50f, -249.87f, -67.44f),
	GUNROW(WEAPON_GE_AR33, "PchrgeAR33Z", "prop/chrm16", 1, 0, 2, 1, -1, 1, 0.19440f, 0.00f, 0.00f, 0.00f, 352.49f, -219.07f, -123.07f),
	GUNROW(WEAPON_GE_RCP90, "PchrgeRCP90Z", "prop/chrfnp90", 1, 0, 2, 1, -1, 1, 0.17001f, 0.00f, 0.00f, 0.00f, 312.50f, -189.98f, -61.93f),
	GUNROW(WEAPON_GE_SHOTGUN, "PchrgeShotgunZ", "prop/chrshotgun", 1, 0, 2, 1, -1, 1, 0.23252f, 0.00f, 0.00f, 0.00f, 443.04f, -259.42f, -94.84f),
	GUNROW(WEAPON_GE_AUTOSHOTGUN, "PchrgeAutoShotgunZ", "prop/chrautoshot", 1, 0, 2, 1, -1, 1, 0.21025f, 0.00f, 0.00f, 0.00f, 441.01f, -230.72f, -115.18f),
	GUNROW(WEAPON_GE_SNIPERRIFLE, "PchrgeSniperZ", "prop/chrsniperrifle", 1, 0, 2, 1, -1, 1, 0.20087f, 0.00f, 0.00f, 0.00f, 359.76f, -224.31f, -69.41f),
	GUNROW(WEAPON_GE_COUGARMAGNUM, "PchrgeCougarZ", "prop/chrruger", 1, 0, 2, 1, -1, 1, 0.19447f, 0.00f, 0.00f, 0.00f, 276.76f, -231.89f, -81.26f),
	GUNROW(WEAPON_GE_GOLDENGUN, "PchrgeGoldenGunZ", "prop/chrgolden", 1, 0, 2, 1, -1, 1, 0.15834f, 0.00f, 0.00f, 0.00f, 223.52f, -192.06f, -51.11f),
	GUNROW(WEAPON_GE_MOONRAKER, "PchrgeMoonrakerZ", "prop/chrlaser", 1, 0, 2, 1, -1, 1, 0.20395f, 0.00f, 0.00f, 0.00f, 268.62f, -231.55f, -91.66f),
	GUNROW(WEAPON_GE_GRENADELAUNCHER, "PchrgeGrenadeLauncherZ", "prop/chrgrenadelaunch", 1, 0, 2, 1, -1, 1, 0.22439f, 0.00f, 0.00f, 0.00f, 492.70f, -251.62f, -114.08f),
	GUNROW(WEAPON_GE_ROCKETLAUNCHER, "PchrgeRocketLauncherZ", "prop/chrrocketlaunch", 1, 0, 2, 1, -1, 1, 0.14094f, 0.00f, 0.00f, 0.00f, 293.80f, -168.30f, -68.90f),
	GUNROW(WEAPON_GE_HUNTINGKNIFE, "PchrgeKnifeZ", "prop/chrknife", 1, 0, 2, 1, -1, 1, 0.18173f, 0.00f, 0.00f, 0.00f, 178.04f, -208.67f, -78.41f),
	GUNROW(WEAPON_GE_THROWINGKNIFE, "PchrgeThrowingKnifeZ", "prop/chrthrowknife", 1, 0, 2, 1, -1, 1, 0.18394f, 0.00f, 0.00f, 0.00f, 218.79f, -211.91f, -112.32f),
	GUNROW(WEAPON_GE_GRENADE, "PchrgeGrenadeZ", "prop/chrgrenade", 1, 0, 2, 1, -1, 1, 0.26535f, 0.00f, 0.00f, 0.00f, 249.18f, -295.77f, -17.55f),
	GUNROW(WEAPON_GE_TIMEDMINE, "PchrgeTimedMineZ", "prop/chrtimedmine", 1, 0, 2, 1, -1, 1, 0.21323f, 0.00f, 0.00f, 0.00f, 282.90f, -243.96f, 0.49f),
	GUNROW(WEAPON_GE_PROXIMITYMINE, "PchrgeProximityMineZ", "prop/chrproximitymine", 1, 0, 2, 1, -1, 1, 0.21335f, 0.00f, 0.00f, 0.00f, 283.09f, -243.88f, 0.53f),
	GUNROW(WEAPON_GE_REMOTEMINE, "PchrgeRemoteMineZ", "prop/chrremotemine", 1, 0, 2, 1, -1, 1, 0.21334f, 0.00f, 0.00f, 0.00f, 283.09f, -245.36f, 0.50f),
