// Generated by tools/geguns/gen_gunstats.py from GoldenEye's decomp
// (obseg/gun/<source>/gunWeaponStat.inc.c, fields named by its gun.h):
// GoldenEye's own numbers for each of its guns, as they stand. Perfect
// Dark's conversions of these guns carry the same numbers - the DD44's 1
// damage, 6 spread, 8 rounds and 16 frame recovery are the tt33's
// Destruction, Inaccuracy, MagSize and SingleRate - so nothing is scaled.
// weapon, source, magazine, automatic rate, single rate, objects shot
// through, destruction (damage), inaccuracy (spread), force of impact,
// then how loud it is: the least and most a guard hears it from (x100
// units), what a shot adds, and the two times the noise dies away over;
// then how it handles: the four recoil speed bytes, how far the hands
// pull back, how far the gun kicks up, how far the bolt slides, the
// sway, the aim zoom and how far the flash sits past the barrel; then
// GoldenEye's ammunition type (its AMMOTYPES index) and its BitFlags
	GUNSTAT(WEAPON_GE_PP7, "wppk", 7, 0xff, 0x10, 1, 1.0f, 1.0f, 0.0f, 1.0f, 12.0f, 2.0f, 2.0f, 4.0f,
		4, 8, 3, 0, 3.0f, 10.0f, 29.999998f, 1.0f, 0.0f, 1.0f, 1, 0x00170fb9),
	GUNSTAT(WEAPON_GE_PP7SILENCED, "wppksil", 7, 0xff, 0x10, 1, 1.0f, 3.0f, 0.0f, 0.0f, 5.0f, 1.0f, 2.0f, 4.0f,
		4, 8, 3, 0, 1.5f, 5.0f, 29.999998f, 1.0f, 0.0f, 1.0f, 1, 0x00170fb9),
	GUNSTAT(WEAPON_GE_DD44, "tt33", 8, 0xff, 0x10, 1, 1.0f, 6.0f, 0.0f, 2.0f, 16.0f, 3.0f, 2.0f, 4.0f,
		4, 8, 3, 0, 5.0f, 10.0f, 59.999996f, 1.0f, 0.0f, 1.0f, 1, 0x00170fb9),
	GUNSTAT(WEAPON_GE_KLOBB, "skorpion", 20, 0x03, 0x00, 1, 0.60000002f, 15.0f, 0.0f, 2.0f, 20.0f, 2.0f, 2.0f, 4.0f,
		0, 0, 0, 6, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 2.0f, 1, 0x00170b79),
	GUNSTAT(WEAPON_GE_KF7SOVIET, "ak47", 30, 0x03, 0x00, 1, 1.0f, 10.0f, 3.0f, 2.0f, 20.0f, 2.0f, 2.0f, 4.0f,
		4, 12, 0, 6, 4.5f, 2.0f, 0.0f, 1.0f, 30.0f, 2.0f, 3, 0x00171a7c),
	GUNSTAT(WEAPON_GE_ZMG, "uzi", 32, 0x02, 0x00, 1, 1.0f, 9.0f, 0.0f, 2.0f, 20.0f, 2.0f, 2.0f, 4.0f,
		6, 18, 0, 6, 4.0f, 3.0f, 0.0f, 1.0f, 0.0f, 3.0f, 1, 0x00171b79),
	GUNSTAT(WEAPON_GE_D5K, "mp5k", 30, 0x03, 0x00, 1, 1.0f, 7.0f, 0.0f, 2.0f, 20.0f, 2.0f, 2.0f, 4.0f,
		6, 18, 0, 6, 4.0f, 3.0f, 0.0f, 1.0f, 0.0f, 2.0f, 1, 0x00171a79),
	GUNSTAT(WEAPON_GE_D5KSILENCED, "mp5ksil", 30, 0x03, 0x00, 1, 1.0f, 9.0f, 0.0f, 0.0f, 7.0f, 1.2f, 2.0f, 4.0f,
		6, 18, 0, 6, 3.5f, 2.0f, 0.0f, 1.0f, 0.0f, 2.0f, 1, 0x00171a79),
	GUNSTAT(WEAPON_GE_PHANTOM, "spectre", 50, 0x03, 0x00, 1, 1.4f, 12.0f, 0.0f, 2.0f, 20.0f, 2.0f, 2.0f, 4.0f,
		4, 12, 0, 6, 4.5f, 2.0f, 0.0f, 1.0f, 0.0f, 2.0f, 1, 0x00171a79),
	GUNSTAT(WEAPON_GE_AR33, "m16", 30, 0x02, 0x00, 2, 1.4f, 6.0f, 4.0f, 2.0f, 20.0f, 2.0f, 2.0f, 4.0f,
		6, 18, 2, 8, 5.0f, 2.0f, 0.0f, 0.5f, 20.0f, 6.0f, 3, 0x00171a7c),
	GUNSTAT(WEAPON_GE_RCP90, "fnp90", 80, 0x02, 0x00, 3, 1.8f, 6.0f, 4.0f, 2.0f, 20.0f, 2.0f, 2.0f, 4.0f,
		4, 8, 0, 3, 3.5f, 2.0f, 0.0f, 1.0f, 0.0f, 4.0f, 1, 0x00171a78),
	GUNSTAT(WEAPON_GE_SHOTGUN, "shotgun", 5, 0xff, 0x0a, 1, 0.40000001f, 20.0f, 5.0f, 2.0f, 25.0f, 4.0f, 2.0f, 4.0f,
		8, 18, 8, 12, 9.0f, 10.0f, 0.0f, 1.0f, 0.0f, 4.0f, 4, 0x00170af9),
	GUNSTAT(WEAPON_GE_AUTOSHOTGUN, "autoshot", 5, 0xff, 0x0a, 1, 0.60000002f, 16.0f, 5.0f, 2.0f, 20.0f, 3.0f, 2.0f, 4.0f,
		8, 18, 8, 12, 4.5f, 3.0f, 0.0f, 1.0f, 0.0f, 4.0f, 4, 0x00170af9),
	GUNSTAT(WEAPON_GE_SNIPERRIFLE, "sniperrifle", 8, 0xff, 0x10, 1, 1.0f, 0.0f, 0.0f, 0.0f, 7.0f, 1.2f, 2.0f, 4.0f,
		0, 0, 0, 0, 0.0f, 0.0f, 0.0f, 0.25f, 15.0f, 6.0f, 3, 0x00178a70),
	GUNSTAT(WEAPON_GE_COUGARMAGNUM, "ruger", 6, 0xff, 0x14, 10, 2.0f, 0.0f, 6.0f, 2.0f, 20.0f, 3.0f, 2.0f, 4.0f,
		8, 16, 0, -1, 12.0f, 35.0f, 0.0f, 1.0f, 0.0f, 2.0f, 12, 0x00170fb9),
	GUNSTAT(WEAPON_GE_GOLDENGUN, "goldengun", 1, 0xff, 0x00, 1, 100.0f, 0.0f, 0.0f, 1.0f, 9.0f, 1.5f, 2.0f, 4.0f,
		4, 8, 0, -1, 5.0f, 10.0f, 0.0f, 1.0f, 0.0f, 1.0f, 13, 0x00170f99),
	GUNSTAT(WEAPON_GE_MOONRAKER, "laser", 0, 0xff, 0x06, 2, 2.0f, 0.0f, 2.0f, 2.0f, 16.0f, 2.0f, 2.0f, 4.0f,
		6, 0, 6, 6, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 0, 0x00170b99),
	GUNSTAT(WEAPON_GE_GRENADELAUNCHER, "grenadelaunch", 6, 0xff, 0x14, 1, 1.0f, 0.0f, 0.0f, 2.0f, 20.0f, 2.0f, 2.0f, 4.0f,
		8, 16, 0, -1, 10.5f, 15.0f, 0.0f, 1.0f, 0.0f, 1.0f, 11, 0x00120af1),
	GUNSTAT(WEAPON_GE_ROCKETLAUNCHER, "rocketlaunch", 1, 0xff, 0x14, 1, 1.0f, 0.0f, 0.0f, 2.0f, 25.0f, 10.0f, 2.0f, 4.0f,
		0, 0, 0, -1, 0.0f, 0.0f, 0.0f, 0.5f, 0.0f, 1.0f, 6, 0x00120ff1),
	GUNSTAT(WEAPON_GE_HUNTINGKNIFE, "knife", 0, 0xff, 0x06, 1, 3.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 2.0f, 4.0f,
		0, 0, 0, 0, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 0, 0x00160d91),
	GUNSTAT(WEAPON_GE_THROWINGKNIFE, "throwknife", 1, 0xff, 0x06, 1, 3.0f, 0.0f, 1.0f, 0.0f, 1.0f, 1.0f, 2.0f, 4.0f,
		0, 0, 0, 0, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 10, 0x00560d83),
	GUNSTAT(WEAPON_GE_GRENADE, "grenade", 1, 0xff, 0x00, 1, 1.0f, 0.0f, 0.0f, 0.0f, 2.0f, 2.0f, 2.0f, 4.0f,
		0, 0, 0, -1, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 5, 0x00422982),
	GUNSTAT(WEAPON_GE_TIMEDMINE, "timedmine", 1, 0xff, 0x06, 1, 1.0f, 0.0f, 0.0f, 0.0f, 2.0f, 2.0f, 2.0f, 4.0f,
		0, 0, 0, 0, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 9, 0x00422d82),
	GUNSTAT(WEAPON_GE_PROXIMITYMINE, "proximitymine", 1, 0xff, 0x06, 1, 1.0f, 0.0f, 0.0f, 0.0f, 2.0f, 2.0f, 2.0f, 4.0f,
		0, 0, 0, 0, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 8, 0x00422d82),
	GUNSTAT(WEAPON_GE_REMOTEMINE, "remotemine", 1, 0xff, 0x06, 1, 1.0f, 0.0f, 0.0f, 0.0f, 2.0f, 2.0f, 2.0f, 4.0f,
		0, 0, 0, 0, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 7, 0x00422d82),
