// Generated by .xbla-work/ge-bean/gen_guntable.py from gunfit.json: each of
// GoldenEye's guns, the file its pickup model is an alias to, Bean's pickup
// (files/new|original/prop/<source>), and how Bean's pickup is laid onto
// GoldenEye's N64 one, whose frame is Perfect Dark's: axis k of the result is
// sign[k] * Bean axis perm[k], centred on beancentre, scaled, and moved to
// n64centre. Matched by nearest vertex against the decomp's obseg/prop models.
// weapon, file, source, perm[3], sign[3], scale, beancentre[3], n64centre[3]
	GUNROW(WEAPON_GE_PP7, "PchrgePP7Z", "prop/chrwppk", 1, 0, 2, 1, 1, 1, 0.23791f, -1294.50f, -1207.03f, 112.15f, -11.50f, 0.50f, -15.50f),
	GUNROW(WEAPON_GE_PP7SILENCED, "PchrgePP7silZ", "prop/chrwppksil", 1, 0, 2, 1, 1, 1, 0.21189f, -1585.19f, -1217.64f, 91.82f, -48.50f, 0.50f, -21.50f),
	GUNROW(WEAPON_GE_DD44, "PchrgeDD44Z", "prop/chrtt33", 1, 0, 2, 1, -1, 1, 0.22423f, -1383.59f, 1217.89f, 90.73f, -27.50f, 0.50f, -28.50f),
	GUNROW(WEAPON_GE_KLOBB, "PchrgeKlobbZ", "prop/chrskorpion", 1, 0, 2, 1, 1, 1, 0.19972f, -1570.94f, -1103.73f, 275.63f, -15.50f, -0.50f, -41.00f),
	GUNROW(WEAPON_GE_KF7SOVIET, "PchrgeKF7Z", "prop/chrkalash", 1, 0, 2, 1, -1, 1, 0.19046f, -2366.04f, 1126.26f, -56.16f, -75.50f, 0.50f, -62.50f),
	GUNROW(WEAPON_GE_ZMG, "PchrgeZMGZ", "prop/chruzi", 1, 0, 2, 1, 1, 1, 0.21530f, -1261.35f, -1112.79f, -101.80f, -34.00f, -2.00f, -88.50f),
	GUNROW(WEAPON_GE_D5K, "PchrgeD5KZ", "prop/chrmp5k", 1, 0, 2, 1, 1, 1, 0.24750f, -1592.08f, -1114.24f, 185.47f, -36.00f, -4.00f, -88.00f),
	GUNROW(WEAPON_GE_D5KSILENCED, "PchrgeD5KsilZ", "prop/chrmp5ksil", 1, 0, 2, 1, 1, 1, 0.21674f, -2032.56f, -1114.54f, 185.47f, -109.50f, -4.00f, -88.00f),
	GUNROW(WEAPON_GE_PHANTOM, "PchrgePhantomZ", "prop/chrspectre", 1, 0, 2, -1, 1, 1, 0.21712f, 1920.89f, -1121.66f, -44.36f, -45.00f, 0.00f, -100.00f),
	GUNROW(WEAPON_GE_AR33, "PchrgeAR33Z", "prop/chrm16", 2, 0, 1, 1, 1, -1, 0.69747f, 328.49f, -1119.87f, 2152.45f, -64.50f, -63.00f, 78.00f),
	GUNROW(WEAPON_GE_RCP90, "PchrgeRCP90Z", "prop/chrfnp90", 0, 1, 2, -1, 1, -1, 1.55349f, 1113.24f, -1129.92f, -438.13f, 121.00f, 137.50f, 36.50f),
	GUNROW(WEAPON_GE_SHOTGUN, "PchrgeShotgunZ", "prop/chrshotgun", 1, 0, 2, 1, -1, 1, 0.23252f, -2334.49f, 1127.03f, 208.62f, -99.50f, 1.50f, -44.50f),
	GUNROW(WEAPON_GE_AUTOSHOTGUN, "PchrgeAutoShotgunZ", "prop/chrautoshot", 1, 0, 2, 1, -1, 1, 0.21025f, -2306.31f, 1218.39f, 409.25f, -31.50f, 0.00f, -33.00f),
	GUNROW(WEAPON_GE_SNIPERRIFLE, "PchrgeSniperZ", "prop/chrsniperrifle", 1, 0, 2, 1, -1, 1, 0.20087f, -2341.48f, 1086.08f, 429.15f, -103.50f, -2.00f, 12.50f),
	GUNROW(WEAPON_GE_COUGARMAGNUM, "PchrgeCougarZ", "prop/chrruger", 1, 0, 2, 1, -1, 1, 0.19447f, -1679.68f, 1194.51f, 223.21f, -47.50f, 0.50f, -34.00f),
	GUNROW(WEAPON_GE_GOLDENGUN, "PchrgeGoldenGunZ", "prop/chrgolden", 1, 0, 2, 1, 1, 1, 0.15834f, -1604.42f, -1217.30f, 187.31f, -36.00f, 0.50f, -22.00f),
	GUNROW(WEAPON_GE_MOONRAKER, "PchrgeMoonrakerZ", "prop/chrlaser", 1, 0, 2, 1, 1, 1, 0.20395f, -1652.76f, -1123.01f, 441.46f, -49.50f, 0.00f, -16.50f),
	GUNROW(WEAPON_GE_GRENADELAUNCHER, "PchrgeGrenadeLauncherZ", "prop/chrgrenadelaunch", 1, 0, 2, 1, -1, 1, 0.22439f, -2530.91f, 1132.88f, 305.90f, -20.50f, 2.50f, -42.00f),
	GUNROW(WEAPON_GE_ROCKETLAUNCHER, "PchrgeRocketLauncherZ", "prop/chrrocketlaunch", 1, 0, 2, -1, -1, 1, 0.14094f, 1998.66f, 1199.92f, 288.95f, 1.00f, 1.50f, -54.50f),
	GUNROW(WEAPON_GE_HUNTINGKNIFE, "PchrgeKnifeZ", "prop/chrknife", 1, 0, 2, -1, 1, 1, 0.18173f, 974.74f, -1152.41f, 619.16f, 1.50f, 0.00f, 49.00f),
	GUNROW(WEAPON_GE_THROWINGKNIFE, "PchrgeThrowingKnifeZ", "prop/chrthrowknife", 1, 0, 2, 1, -1, 1, 0.18394f, -1213.88f, 1152.73f, 571.29f, 4.50f, 0.00f, -17.50f),
	GUNROW(WEAPON_GE_GRENADE, "PchrgeGrenadeZ", "prop/chrgrenade", 0, 1, 2, -1, -1, 1, 0.26535f, 1134.72f, 934.49f, 147.14f, 0.50f, 1.00f, 23.50f),
	GUNROW(WEAPON_GE_TIMEDMINE, "PchrgeTimedMineZ", "prop/chrtimedmine", 1, 0, 2, 1, -1, 1, 0.21323f, -1331.70f, 1156.49f, -2.11f, -1.00f, 2.50f, 0.00f),
	GUNROW(WEAPON_GE_PROXIMITYMINE, "PchrgeProximityMineZ", "prop/chrproximitymine", 1, 0, 2, 1, -1, 1, 0.21335f, -1331.70f, 1156.53f, -2.11f, -1.00f, 3.00f, 0.00f),
	GUNROW(WEAPON_GE_REMOTEMINE, "PchrgeRemoteMineZ", "prop/chrremotemine", 1, 0, 2, 1, -1, 1, 0.21334f, -1331.70f, 1156.53f, -2.11f, -1.00f, 1.50f, 0.00f),
