// Generated by tools/geguns/gen_gunstats.py from GoldenEye's decomp
// (obseg/gun/fist/gunWeaponStat.inc.c): GoldenEye's unarmed hand, ITEM_FIST,
// in gegunstats.h's fields and order, and its PosX/PosY/PosZ
	FISTSTAT("fist", 0, 0xff, 0x06, 1, 2.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 2.0f, 4.0f,
		0, 0, 0, 0, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 0, 0x00064d91),
#define FISTPOS { 11.0f, -50.0f, -33.0f }
