#include <stddef.h>
#include <PR/ultratypes.h>
#include "types.h"
#include "ghostrecovery.h"

/**
 * The ten lists. See ghostrecovery.h - the ids are frozen, the names are not.
 *
 * The lists are long enough that no category is a coin toss and short enough
 * that a dropdown of them can be scrolled through in a few seconds, which is
 * the whole design: everything here is picked twice, once when the account is
 * made and once a year later by somebody who has forgotten their PIN, and an
 * answer they cannot find in the list is worse than no answer at all.
 */
static const struct ghostrecoveryoption g_GhostRecovery_actor[] = {
	{ "alpacino", "Al Pacino" },
	{ "angelinajolie", "Angelina Jolie" },
	{ "anyataylorjoy", "Anya Taylor-Joy" },
	{ "arnoldschwarzenegger", "Arnold Schwarzenegger" },
	{ "bradpitt", "Brad Pitt" },
	{ "brucewillis", "Bruce Willis" },
	{ "cateblanchett", "Cate Blanchett" },
	{ "charlizetheron", "Charlize Theron" },
	{ "chrishemsworth", "Chris Hemsworth" },
	{ "clinteastwood", "Clint Eastwood" },
	{ "danielcraig", "Daniel Craig" },
	{ "denzelwashington", "Denzel Washington" },
	{ "dwaynejohnson", "Dwayne Johnson" },
	{ "emmastone", "Emma Stone" },
	{ "harrisonford", "Harrison Ford" },
	{ "idriselba", "Idris Elba" },
	{ "jackiechan", "Jackie Chan" },
	{ "jimcarrey", "Jim Carrey" },
	{ "keanureeves", "Keanu Reeves" },
	{ "leonardodicaprio", "Leonardo DiCaprio" },
	{ "margotrobbie", "Margot Robbie" },
	{ "merylstreep", "Meryl Streep" },
	{ "morganfreeman", "Morgan Freeman" },
	{ "natalieportman", "Natalie Portman" },
	{ "piercebrosnan", "Pierce Brosnan" },
	{ "robertdowneyjr", "Robert Downey Jr" },
	{ "ryanreynolds", "Ryan Reynolds" },
	{ "samuelljackson", "Samuel L Jackson" },
	{ "scarlettjohansson", "Scarlett Johansson" },
	{ "seanconnery", "Sean Connery" },
	{ "sigourneyweaver", "Sigourney Weaver" },
	{ "tomcruise", "Tom Cruise" },
	{ "tomhanks", "Tom Hanks" },
	{ "willsmith", "Will Smith" },
	{ "zendaya", "Zendaya" },
	{ "mrbeast", "MrBeast" },
	{ "pewdiepie", "PewDiePie" },
	{ "markiplier", "Markiplier" },
	{ "jacksepticeye", "Jacksepticeye" },
	{ "ludwig", "Ludwig" },
	{ "pokimane", "Pokimane" },
	{ "dream", "Dream" },
	{ "summoningsalt", "Summoning Salt" },
	{ "karljobst", "Karl Jobst" },
	{ "gamegrumps", "Game Grumps" },
	{ "linustechtips", "Linus Tech Tips" },
	{ "markrober", "Mark Rober" },
	{ "videogamedunkey", "videogamedunkey" },
};

static const struct ghostrecoveryoption g_GhostRecovery_athlete[] = {
	{ "michaeljordan", "Michael Jordan" },
	{ "lebronjames", "LeBron James" },
	{ "kobebryant", "Kobe Bryant" },
	{ "stephencurry", "Stephen Curry" },
	{ "shaquilleoneal", "Shaquille O'Neal" },
	{ "larrybird", "Larry Bird" },
	{ "magicjohnson", "Magic Johnson" },
	{ "tombrady", "Tom Brady" },
	{ "patrickmahomes", "Patrick Mahomes" },
	{ "jerryrice", "Jerry Rice" },
	{ "peytonmanning", "Peyton Manning" },
	{ "barrysanders", "Barry Sanders" },
	{ "walterpayton", "Walter Payton" },
	{ "waynegretzky", "Wayne Gretzky" },
	{ "sidneycrosby", "Sidney Crosby" },
	{ "connormcdavid", "Connor McDavid" },
	{ "mariolemieux", "Mario Lemieux" },
	{ "baberuth", "Babe Ruth" },
	{ "derekjeter", "Derek Jeter" },
	{ "shoheiohtani", "Shohei Ohtani" },
	{ "kengriffeyjr", "Ken Griffey Jr" },
	{ "hankaaron", "Hank Aaron" },
	{ "jackierobinson", "Jackie Robinson" },
	{ "lionelmessi", "Lionel Messi" },
	{ "cristianoronaldo", "Cristiano Ronaldo" },
	{ "pele", "Pele" },
	{ "diegomaradona", "Diego Maradona" },
	{ "ronaldinho", "Ronaldinho" },
	{ "kylianmbappe", "Kylian Mbappe" },
	{ "zinedinezidane", "Zinedine Zidane" },
	{ "davidbeckham", "David Beckham" },
	{ "muhammadali", "Muhammad Ali" },
	{ "miketyson", "Mike Tyson" },
	{ "floydmayweather", "Floyd Mayweather" },
	{ "usainbolt", "Usain Bolt" },
	{ "michaelphelps", "Michael Phelps" },
	{ "simonebiles", "Simone Biles" },
	{ "serenawilliams", "Serena Williams" },
	{ "rogerfederer", "Roger Federer" },
	{ "rafaelnadal", "Rafael Nadal" },
	{ "novakdjokovic", "Novak Djokovic" },
	{ "tigerwoods", "Tiger Woods" },
	{ "lewishamilton", "Lewis Hamilton" },
	{ "ayrtonsenna", "Ayrton Senna" },
	{ "michaelschumacher", "Michael Schumacher" },
	{ "valentinorossi", "Valentino Rossi" },
	{ "tonyhawk", "Tony Hawk" },
	{ "daleearnhardt", "Dale Earnhardt" },
};

static const struct ghostrecoveryoption g_GhostRecovery_president[] = {
	{ "georgewashington", "George Washington" },
	{ "johnadams", "John Adams" },
	{ "thomasjefferson", "Thomas Jefferson" },
	{ "jamesmadison", "James Madison" },
	{ "jamesmonroe", "James Monroe" },
	{ "johnquincyadams", "John Quincy Adams" },
	{ "andrewjackson", "Andrew Jackson" },
	{ "martinvanburen", "Martin Van Buren" },
	{ "williamhenryharrison", "William Henry Harrison" },
	{ "johntyler", "John Tyler" },
	{ "jameskpolk", "James K Polk" },
	{ "zacharytaylor", "Zachary Taylor" },
	{ "millardfillmore", "Millard Fillmore" },
	{ "franklinpierce", "Franklin Pierce" },
	{ "jamesbuchanan", "James Buchanan" },
	{ "abrahamlincoln", "Abraham Lincoln" },
	{ "andrewjohnson", "Andrew Johnson" },
	{ "ulyssessgrant", "Ulysses S Grant" },
	{ "rutherfordbhayes", "Rutherford B Hayes" },
	{ "jamesgarfield", "James Garfield" },
	{ "chesteraarthur", "Chester A Arthur" },
	{ "grovercleveland", "Grover Cleveland" },
	{ "benjaminharrison", "Benjamin Harrison" },
	{ "williammckinley", "William McKinley" },
	{ "theodoreroosevelt", "Theodore Roosevelt" },
	{ "williamhowardtaft", "William Howard Taft" },
	{ "woodrowwilson", "Woodrow Wilson" },
	{ "warrengharding", "Warren G Harding" },
	{ "calvincoolidge", "Calvin Coolidge" },
	{ "herberthoover", "Herbert Hoover" },
	{ "franklindroosevelt", "Franklin D Roosevelt" },
	{ "harrystruman", "Harry S Truman" },
	{ "dwightdeisenhower", "Dwight D Eisenhower" },
	{ "johnfkennedy", "John F Kennedy" },
	{ "lyndonbjohnson", "Lyndon B Johnson" },
	{ "richardnixon", "Richard Nixon" },
	{ "geraldford", "Gerald Ford" },
	{ "jimmycarter", "Jimmy Carter" },
	{ "ronaldreagan", "Ronald Reagan" },
	{ "georgehwbush", "George H W Bush" },
	{ "billclinton", "Bill Clinton" },
	{ "georgewbush", "George W Bush" },
	{ "barackobama", "Barack Obama" },
	{ "donaldtrump", "Donald Trump" },
	{ "joebiden", "Joe Biden" },
};

static const struct ghostrecoveryoption g_GhostRecovery_food[] = {
	{ "pizza", "Pizza" },
	{ "cheeseburger", "Cheeseburger" },
	{ "sushi", "Sushi" },
	{ "tacos", "Tacos" },
	{ "steak", "Steak" },
	{ "friedchicken", "Fried Chicken" },
	{ "bbqribs", "BBQ Ribs" },
	{ "spaghetti", "Spaghetti" },
	{ "lasagna", "Lasagna" },
	{ "ramen", "Ramen" },
	{ "pho", "Pho" },
	{ "padthai", "Pad Thai" },
	{ "curry", "Curry" },
	{ "burrito", "Burrito" },
	{ "nachos", "Nachos" },
	{ "hotdog", "Hot Dog" },
	{ "grilledcheese", "Grilled Cheese" },
	{ "macandcheese", "Mac and Cheese" },
	{ "fishandchips", "Fish and Chips" },
	{ "chickenwings", "Chicken Wings" },
	{ "pancakes", "Pancakes" },
	{ "waffles", "Waffles" },
	{ "baconandeggs", "Bacon and Eggs" },
	{ "biscuitsandgravy", "Biscuits and Gravy" },
	{ "dumplings", "Dumplings" },
	{ "friedrice", "Fried Rice" },
	{ "gyro", "Gyro" },
	{ "falafel", "Falafel" },
	{ "paella", "Paella" },
	{ "poutine", "Poutine" },
	{ "meatloaf", "Meatloaf" },
	{ "potroast", "Pot Roast" },
	{ "chili", "Chili" },
	{ "clamchowder", "Clam Chowder" },
	{ "salmon", "Salmon" },
	{ "lobster", "Lobster" },
	{ "shrimpscampi", "Shrimp Scampi" },
	{ "pulledpork", "Pulled Pork" },
	{ "empanadas", "Empanadas" },
	{ "pierogi", "Pierogi" },
	{ "kebab", "Kebab" },
	{ "bibimbap", "Bibimbap" },
	{ "katsucurry", "Katsu Curry" },
	{ "icecream", "Ice Cream" },
	{ "cheesecake", "Cheesecake" },
	{ "applepie", "Apple Pie" },
	{ "chocolatecake", "Chocolate Cake" },
};

static const struct ghostrecoveryoption g_GhostRecovery_drink[] = {
	{ "water", "Water" },
	{ "coffee", "Coffee" },
	{ "espresso", "Espresso" },
	{ "latte", "Latte" },
	{ "greentea", "Green Tea" },
	{ "icedtea", "Iced Tea" },
	{ "sweettea", "Sweet Tea" },
	{ "hotchocolate", "Hot Chocolate" },
	{ "milk", "Milk" },
	{ "orangejuice", "Orange Juice" },
	{ "applejuice", "Apple Juice" },
	{ "lemonade", "Lemonade" },
	{ "cocacola", "Coca-Cola" },
	{ "pepsi", "Pepsi" },
	{ "drpepper", "Dr Pepper" },
	{ "mountaindew", "Mountain Dew" },
	{ "sprite", "Sprite" },
	{ "rootbeer", "Root Beer" },
	{ "gingerale", "Ginger Ale" },
	{ "creamsoda", "Cream Soda" },
	{ "redbull", "Red Bull" },
	{ "monster", "Monster" },
	{ "gatorade", "Gatorade" },
	{ "smoothie", "Smoothie" },
	{ "milkshake", "Milkshake" },
	{ "beer", "Beer" },
	{ "ipa", "IPA" },
	{ "stout", "Stout" },
	{ "cider", "Cider" },
	{ "redwine", "Red Wine" },
	{ "whitewine", "White Wine" },
	{ "champagne", "Champagne" },
	{ "whiskey", "Whiskey" },
	{ "bourbon", "Bourbon" },
	{ "scotch", "Scotch" },
	{ "vodka", "Vodka" },
	{ "gin", "Gin" },
	{ "rum", "Rum" },
	{ "tequila", "Tequila" },
	{ "margarita", "Margarita" },
	{ "martini", "Martini" },
	{ "mojito", "Mojito" },
	{ "oldfashioned", "Old Fashioned" },
	{ "sake", "Sake" },
};

static const struct ghostrecoveryoption g_GhostRecovery_car[] = {
	{ "fordf150", "Ford F-150" },
	{ "chevroletsilverado", "Chevrolet Silverado" },
	{ "ram1500", "Ram 1500" },
	{ "toyotatacoma", "Toyota Tacoma" },
	{ "toyotatundra", "Toyota Tundra" },
	{ "gmcsierra", "GMC Sierra" },
	{ "jeepwrangler", "Jeep Wrangler" },
	{ "fordbronco", "Ford Bronco" },
	{ "landroverdefender", "Land Rover Defender" },
	{ "hummerh1", "Hummer H1" },
	{ "fordmustang", "Ford Mustang" },
	{ "chevroletcamaro", "Chevrolet Camaro" },
	{ "dodgechallenger", "Dodge Challenger" },
	{ "dodgecharger", "Dodge Charger" },
	{ "chevroletcorvette", "Chevrolet Corvette" },
	{ "fordgt", "Ford GT" },
	{ "dodgeviper", "Dodge Viper" },
	{ "shelbycobra", "Shelby Cobra" },
	{ "pontiacfirebird", "Pontiac Firebird" },
	{ "chevroletimpala", "Chevrolet Impala" },
	{ "hondacivic", "Honda Civic" },
	{ "hondaaccord", "Honda Accord" },
	{ "toyotacorolla", "Toyota Corolla" },
	{ "toyotacamry", "Toyota Camry" },
	{ "toyotasupra", "Toyota Supra" },
	{ "nissanskylinegtr", "Nissan Skyline GT-R" },
	{ "nissan370z", "Nissan 370Z" },
	{ "mazdamx5miata", "Mazda MX-5 Miata" },
	{ "mazdarx7", "Mazda RX-7" },
	{ "subaruwrx", "Subaru WRX" },
	{ "mitsubishilancerevo", "Mitsubishi Lancer Evo" },
	{ "volkswagengolfgti", "Volkswagen Golf GTI" },
	{ "volkswagenbeetle", "Volkswagen Beetle" },
	{ "minicooper", "Mini Cooper" },
	{ "bmwm3", "BMW M3" },
	{ "mercedesgwagon", "Mercedes G-Wagon" },
	{ "audir8", "Audi R8" },
	{ "porsche911", "Porsche 911" },
	{ "ferrarif40", "Ferrari F40" },
	{ "lamborghinicountach", "Lamborghini Countach" },
	{ "lamborghinihuracan", "Lamborghini Huracan" },
	{ "mclarenf1", "McLaren F1" },
	{ "bugattiveyron", "Bugatti Veyron" },
	{ "astonmartindb5", "Aston Martin DB5" },
	{ "jaguaretype", "Jaguar E-Type" },
	{ "teslamodels", "Tesla Model S" },
	{ "teslacybertruck", "Tesla Cybertruck" },
	{ "deloreandmc12", "DeLorean DMC-12" },
};

static const struct ghostrecoveryoption g_GhostRecovery_book[] = {
	{ "1984", "1984" },
	{ "animalfarm", "Animal Farm" },
	{ "bravenewworld", "Brave New World" },
	{ "fahrenheit451", "Fahrenheit 451" },
	{ "thegreatgatsby", "The Great Gatsby" },
	{ "tokillamockingbird", "To Kill a Mockingbird" },
	{ "catch22", "Catch-22" },
	{ "thecatcherintherye", "The Catcher in the Rye" },
	{ "ofmiceandmen", "Of Mice and Men" },
	{ "mobydick", "Moby-Dick" },
	{ "theodyssey", "The Odyssey" },
	{ "donquixote", "Don Quixote" },
	{ "prideandprejudice", "Pride and Prejudice" },
	{ "janeeyre", "Jane Eyre" },
	{ "wutheringheights", "Wuthering Heights" },
	{ "frankenstein", "Frankenstein" },
	{ "dracula", "Dracula" },
	{ "thehobbit", "The Hobbit" },
	{ "thelordoftherings", "The Lord of the Rings" },
	{ "agameofthrones", "A Game of Thrones" },
	{ "dune", "Dune" },
	{ "foundation", "Foundation" },
	{ "endersgame", "Ender's Game" },
	{ "neuromancer", "Neuromancer" },
	{ "snowcrash", "Snow Crash" },
	{ "readyplayerone", "Ready Player One" },
	{ "themartian", "The Martian" },
	{ "jurassicpark", "Jurassic Park" },
	{ "theshining", "The Shining" },
	{ "it", "It" },
	{ "thestand", "The Stand" },
	{ "thedavincicode", "The Da Vinci Code" },
	{ "thehuntforredoctober", "The Hunt for Red October" },
	{ "harrypotter", "Harry Potter" },
	{ "percyjackson", "Percy Jackson" },
	{ "thehungergames", "The Hunger Games" },
	{ "thealchemist", "The Alchemist" },
	{ "lifeofpi", "Life of Pi" },
	{ "theroad", "The Road" },
	{ "slaughterhousefive", "Slaughterhouse-Five" },
	{ "thecountofmontecristo", "The Count of Monte Cristo" },
	{ "lesmiserables", "Les Miserables" },
	{ "crimeandpunishment", "Crime and Punishment" },
	{ "theartofwar", "The Art of War" },
	{ "sapiens", "Sapiens" },
	{ "thebible", "The Bible" },
};

static const struct ghostrecoveryoption g_GhostRecovery_show[] = {
	{ "thesimpsons", "The Simpsons" },
	{ "familyguy", "Family Guy" },
	{ "southpark", "South Park" },
	{ "rickandmorty", "Rick and Morty" },
	{ "futurama", "Futurama" },
	{ "kingofthehill", "King of the Hill" },
	{ "bobsburgers", "Bob's Burgers" },
	{ "seinfeld", "Seinfeld" },
	{ "friends", "Friends" },
	{ "theoffice", "The Office" },
	{ "parksandrecreation", "Parks and Recreation" },
	{ "itsalwayssunny", "It's Always Sunny" },
	{ "cheers", "Cheers" },
	{ "frasier", "Frasier" },
	{ "howimetyourmother", "How I Met Your Mother" },
	{ "thebigbangtheory", "The Big Bang Theory" },
	{ "scrubs", "Scrubs" },
	{ "tedlasso", "Ted Lasso" },
	{ "breakingbad", "Breaking Bad" },
	{ "bettercallsaul", "Better Call Saul" },
	{ "thesopranos", "The Sopranos" },
	{ "thewire", "The Wire" },
	{ "madmen", "Mad Men" },
	{ "peakyblinders", "Peaky Blinders" },
	{ "dexter", "Dexter" },
	{ "gameofthrones", "Game of Thrones" },
	{ "strangerthings", "Stranger Things" },
	{ "thelastofus", "The Last of Us" },
	{ "themandalorian", "The Mandalorian" },
	{ "theboys", "The Boys" },
	{ "squidgame", "Squid Game" },
	{ "startrek", "Star Trek" },
	{ "doctorwho", "Doctor Who" },
	{ "thexfiles", "The X-Files" },
	{ "twinpeaks", "Twin Peaks" },
	{ "lost", "Lost" },
	{ "24", "24" },
	{ "prisonbreak", "Prison Break" },
	{ "house", "House" },
	{ "sherlock", "Sherlock" },
	{ "blackmirror", "Black Mirror" },
	{ "thewalkingdead", "The Walking Dead" },
	{ "avatarthelastairbender", "Avatar The Last Airbender" },
	{ "dragonballz", "Dragon Ball Z" },
	{ "naruto", "Naruto" },
	{ "onepiece", "One Piece" },
	{ "attackontitan", "Attack on Titan" },
	{ "cowboybebop", "Cowboy Bebop" },
	{ "topgear", "Top Gear" },
	{ "mythbusters", "Mythbusters" },
	{ "planetearth", "Planet Earth" },
};

static const struct ghostrecoveryoption g_GhostRecovery_song[] = {
	{ "bohemianrhapsody", "Bohemian Rhapsody" },
	{ "stairwaytoheaven", "Stairway to Heaven" },
	{ "hotelcalifornia", "Hotel California" },
	{ "sweetchildomine", "Sweet Child o' Mine" },
	{ "smellsliketeenspirit", "Smells Like Teen Spirit" },
	{ "backinblack", "Back in Black" },
	{ "thunderstruck", "Thunderstruck" },
	{ "entersandman", "Enter Sandman" },
	{ "livinonaprayer", "Livin' on a Prayer" },
	{ "dontstopbelievin", "Don't Stop Believin'" },
	{ "freebird", "Free Bird" },
	{ "purplehaze", "Purple Haze" },
	{ "heyjude", "Hey Jude" },
	{ "letitbe", "Let It Be" },
	{ "imagine", "Imagine" },
	{ "likearollingstone", "Like a Rolling Stone" },
	{ "johnnybgoode", "Johnny B Goode" },
	{ "billiejean", "Billie Jean" },
	{ "thriller", "Thriller" },
	{ "beatit", "Beat It" },
	{ "purplerain", "Purple Rain" },
	{ "superstition", "Superstition" },
	{ "respect", "Respect" },
	{ "whatsgoingon", "What's Going On" },
	{ "iwillsurvive", "I Will Survive" },
	{ "dancingqueen", "Dancing Queen" },
	{ "takeonme", "Take On Me" },
	{ "africa", "Africa" },
	{ "sweetdreams", "Sweet Dreams" },
	{ "everybreathyoutake", "Every Breath You Take" },
	{ "withorwithoutyou", "With or Without You" },
	{ "wonderwall", "Wonderwall" },
	{ "creep", "Creep" },
	{ "losingmyreligion", "Losing My Religion" },
	{ "underthebridge", "Under the Bridge" },
	{ "californication", "Californication" },
	{ "intheend", "In the End" },
	{ "numb", "Numb" },
	{ "chopsuey", "Chop Suey" },
	{ "sevennationarmy", "Seven Nation Army" },
	{ "mrbrightside", "Mr Brightside" },
	{ "vivalavida", "Viva la Vida" },
	{ "clocks", "Clocks" },
	{ "rollinginthedeep", "Rolling in the Deep" },
	{ "shapeofyou", "Shape of You" },
	{ "blindinglights", "Blinding Lights" },
	{ "oldtownroad", "Old Town Road" },
	{ "loseyourself", "Lose Yourself" },
};

static const struct ghostrecoveryoption g_GhostRecovery_game[] = {
	{ "goldeneye007", "GoldenEye 007" },
	{ "perfectdark", "Perfect Dark" },
	{ "perfectdarkzero", "Perfect Dark Zero" },
	{ "banjokazooie", "Banjo-Kazooie" },
	{ "donkeykong64", "Donkey Kong 64" },
	{ "conkersbadfurday", "Conker's Bad Fur Day" },
	{ "jetforcegemini", "Jet Force Gemini" },
	{ "blastcorps", "Blast Corps" },
	{ "diddykongracing", "Diddy Kong Racing" },
	{ "killerinstinct", "Killer Instinct" },
	{ "battletoads", "Battletoads" },
	{ "supermario64", "Super Mario 64" },
	{ "supermariobros3", "Super Mario Bros 3" },
	{ "supermarioworld", "Super Mario World" },
	{ "mariokart64", "Mario Kart 64" },
	{ "smashbrosmelee", "Smash Bros Melee" },
	{ "ocarinaoftime", "Ocarina of Time" },
	{ "majorasmask", "Majora's Mask" },
	{ "alinktothepast", "A Link to the Past" },
	{ "breathofthewild", "Breath of the Wild" },
	{ "metroidprime", "Metroid Prime" },
	{ "supermetroid", "Super Metroid" },
	{ "starfox64", "Star Fox 64" },
	{ "fzerox", "F-Zero X" },
	{ "pokemonredandblue", "Pokemon Red and Blue" },
	{ "sonicthehedgehog", "Sonic the Hedgehog" },
	{ "megaman2", "Mega Man 2" },
	{ "castlevaniasotn", "Castlevania SOTN" },
	{ "finalfantasyvii", "Final Fantasy VII" },
	{ "chronotrigger", "Chrono Trigger" },
	{ "doom", "Doom" },
	{ "quake", "Quake" },
	{ "halflife", "Half-Life" },
	{ "halflife2", "Half-Life 2" },
	{ "portal", "Portal" },
	{ "counterstrike", "Counter-Strike" },
	{ "teamfortress2", "Team Fortress 2" },
	{ "halocombatevolved", "Halo Combat Evolved" },
	{ "callofduty4", "Call of Duty 4" },
	{ "metalgearsolid", "Metal Gear Solid" },
	{ "residentevil4", "Resident Evil 4" },
	{ "silenthill2", "Silent Hill 2" },
	{ "gtasanandreas", "GTA San Andreas" },
	{ "reddeadredemption2", "Red Dead Redemption 2" },
	{ "skyrim", "Skyrim" },
	{ "darksouls", "Dark Souls" },
	{ "bloodborne", "Bloodborne" },
	{ "eldenring", "Elden Ring" },
	{ "minecraft", "Minecraft" },
	{ "tetris", "Tetris" },
	{ "streetfighterii", "Street Fighter II" },
	{ "mortalkombat", "Mortal Kombat" },
	{ "tonyhawksproskater2", "Tony Hawk's Pro Skater 2" },
	{ "rocketleague", "Rocket League" },
	{ "stardewvalley", "Stardew Valley" },
	{ "hollowknight", "Hollow Knight" },
	{ "celeste", "Celeste" },
	{ "undertale", "Undertale" },
};

const struct ghostrecoverycategory g_GhostRecoveryCategories[GHOSTRECOVERY_NUMCATEGORIES] = {
	{ "actor", "Favorite Actor or Creator", g_GhostRecovery_actor, (s32)ARRAYCOUNT(g_GhostRecovery_actor) },
	{ "athlete", "Favorite Athlete", g_GhostRecovery_athlete, (s32)ARRAYCOUNT(g_GhostRecovery_athlete) },
	{ "president", "Favorite President", g_GhostRecovery_president, (s32)ARRAYCOUNT(g_GhostRecovery_president) },
	{ "food", "Favorite Food", g_GhostRecovery_food, (s32)ARRAYCOUNT(g_GhostRecovery_food) },
	{ "drink", "Favorite Drink", g_GhostRecovery_drink, (s32)ARRAYCOUNT(g_GhostRecovery_drink) },
	{ "car", "Favorite Car or Truck", g_GhostRecovery_car, (s32)ARRAYCOUNT(g_GhostRecovery_car) },
	{ "book", "Favorite Book", g_GhostRecovery_book, (s32)ARRAYCOUNT(g_GhostRecovery_book) },
	{ "show", "Favorite Show", g_GhostRecovery_show, (s32)ARRAYCOUNT(g_GhostRecovery_show) },
	{ "song", "Favorite Song", g_GhostRecovery_song, (s32)ARRAYCOUNT(g_GhostRecovery_song) },
	{ "game", "Favorite Game", g_GhostRecovery_game, (s32)ARRAYCOUNT(g_GhostRecovery_game) },
};

/**
 * The accessors take an index that may be anything.
 *
 * Both indices come from a dropdown whose contents change under it - choosing
 * a different category leaves the answer index pointing into a list that may
 * be shorter - so every one of these answers for an index that is out of
 * range rather than trusting the caller to have kept the two in step.
 */
const struct ghostrecoverycategory *ghostRecoveryGetCategory(s32 index)
{
	if (index < 0 || index >= GHOSTRECOVERY_NUMCATEGORIES) {
		return NULL;
	}

	return &g_GhostRecoveryCategories[index];
}

const char *ghostRecoveryGetCategoryId(s32 index)
{
	const struct ghostrecoverycategory *cat = ghostRecoveryGetCategory(index);

	return cat ? cat->id : "";
}

s32 ghostRecoveryGetNumAnswers(s32 category)
{
	const struct ghostrecoverycategory *cat = ghostRecoveryGetCategory(category);

	return cat ? cat->numoptions : 0;
}

const char *ghostRecoveryGetAnswerId(s32 category, s32 answer)
{
	const struct ghostrecoverycategory *cat = ghostRecoveryGetCategory(category);

	if (cat == NULL || answer < 0 || answer >= cat->numoptions) {
		return "";
	}

	return cat->options[answer].id;
}

const char *ghostRecoveryGetAnswerName(s32 category, s32 answer)
{
	const struct ghostrecoverycategory *cat = ghostRecoveryGetCategory(category);

	if (cat == NULL || answer < 0 || answer >= cat->numoptions) {
		return "";
	}

	return cat->options[answer].name;
}
