// Generated by tools/langpack/latin.py - do not edit, run it again.
// code point, kind, ASCII text, mark 1, mark 2

#define LANGFONT_MARK_ACUTE 1
#define LANGFONT_MARK_GRAVE 2
#define LANGFONT_MARK_CIRCUMFLEX 3
#define LANGFONT_MARK_DIAERESIS 4
#define LANGFONT_MARK_TILDE 5
#define LANGFONT_MARK_RING 6
#define LANGFONT_MARK_CEDILLA 7
#define LANGFONT_MARK_CARON 8
#define LANGFONT_MARK_BREVE 9
#define LANGFONT_MARK_MACRON 10
#define LANGFONT_MARK_DOTABOVE 11
#define LANGFONT_MARK_DOUBLEACUTE 12
#define LANGFONT_MARK_OGONEK 13
#define LANGFONT_MARK_COMMABELOW 14
#define LANGFONT_NUM_MARKS 15

static const struct langfontrecipe g_LangFontRecipes[] = {
	{ 0x00a0, 3, " ", 0, 0 }, // no-break space
	{ 0x00a1, 2, "!", 0, 0 }, // inverted exclamation mark
	{ 0x00a3, 3, "L", 0, 0 }, // pound sign
	{ 0x00a5, 3, "Y", 0, 0 }, // yen sign
	{ 0x00a8, 5, " ", 4, 0 }, // diaeresis
	{ 0x00a9, 3, "C", 0, 0 }, // copyright sign
	{ 0x00aa, 3, "a", 0, 0 }, // feminine ordinal indicator
	{ 0x00ab, 1, "<<", 0, 0 }, // left-pointing double angle quotation mark
	{ 0x00ae, 3, "R", 0, 0 }, // registered sign
	{ 0x00b0, 5, " ", 6, 0 }, // degree sign
	{ 0x00b2, 3, "2", 0, 0 }, // superscript two
	{ 0x00b3, 3, "3", 0, 0 }, // superscript three
	{ 0x00b4, 5, " ", 1, 0 }, // acute accent
	{ 0x00b7, 3, ".", 0, 0 }, // middle dot
	{ 0x00b8, 5, " ", 7, 0 }, // cedilla
	{ 0x00b9, 3, "1", 0, 0 }, // superscript one
	{ 0x00ba, 3, "o", 0, 0 }, // masculine ordinal indicator
	{ 0x00bb, 1, ">>", 0, 0 }, // right-pointing double angle quotation mark
	{ 0x00bf, 2, "?", 0, 0 }, // inverted question mark
	{ 0x00c0, 0, "A", 2, 0 }, // latin capital letter a with grave
	{ 0x00c1, 0, "A", 1, 0 }, // latin capital letter a with acute
	{ 0x00c2, 0, "A", 3, 0 }, // latin capital letter a with circumflex
	{ 0x00c3, 0, "A", 5, 0 }, // latin capital letter a with tilde
	{ 0x00c4, 0, "A", 4, 0 }, // latin capital letter a with diaeresis
	{ 0x00c5, 0, "A", 6, 0 }, // latin capital letter a with ring above
	{ 0x00c6, 1, "AE", 0, 0 }, // latin capital letter ae
	{ 0x00c7, 0, "C", 7, 0 }, // latin capital letter c with cedilla
	{ 0x00c8, 0, "E", 2, 0 }, // latin capital letter e with grave
	{ 0x00c9, 0, "E", 1, 0 }, // latin capital letter e with acute
	{ 0x00ca, 0, "E", 3, 0 }, // latin capital letter e with circumflex
	{ 0x00cb, 0, "E", 4, 0 }, // latin capital letter e with diaeresis
	{ 0x00cc, 0, "I", 2, 0 }, // latin capital letter i with grave
	{ 0x00cd, 0, "I", 1, 0 }, // latin capital letter i with acute
	{ 0x00ce, 0, "I", 3, 0 }, // latin capital letter i with circumflex
	{ 0x00cf, 0, "I", 4, 0 }, // latin capital letter i with diaeresis
	{ 0x00d0, 3, "D", 0, 0 }, // latin capital letter eth
	{ 0x00d1, 0, "N", 5, 0 }, // latin capital letter n with tilde
	{ 0x00d2, 0, "O", 2, 0 }, // latin capital letter o with grave
	{ 0x00d3, 0, "O", 1, 0 }, // latin capital letter o with acute
	{ 0x00d4, 0, "O", 3, 0 }, // latin capital letter o with circumflex
	{ 0x00d5, 0, "O", 5, 0 }, // latin capital letter o with tilde
	{ 0x00d6, 0, "O", 4, 0 }, // latin capital letter o with diaeresis
	{ 0x00d7, 3, "x", 0, 0 }, // multiplication sign
	{ 0x00d8, 3, "O", 0, 0 }, // latin capital letter o with stroke
	{ 0x00d9, 0, "U", 2, 0 }, // latin capital letter u with grave
	{ 0x00da, 0, "U", 1, 0 }, // latin capital letter u with acute
	{ 0x00db, 0, "U", 3, 0 }, // latin capital letter u with circumflex
	{ 0x00dc, 0, "U", 4, 0 }, // latin capital letter u with diaeresis
	{ 0x00dd, 0, "Y", 1, 0 }, // latin capital letter y with acute
	{ 0x00de, 3, "P", 0, 0 }, // latin capital letter thorn
	{ 0x00df, 4, "s", 0, 0 }, // latin small letter sharp s
	{ 0x00e0, 0, "a", 2, 0 }, // latin small letter a with grave
	{ 0x00e1, 0, "a", 1, 0 }, // latin small letter a with acute
	{ 0x00e2, 0, "a", 3, 0 }, // latin small letter a with circumflex
	{ 0x00e3, 0, "a", 5, 0 }, // latin small letter a with tilde
	{ 0x00e4, 0, "a", 4, 0 }, // latin small letter a with diaeresis
	{ 0x00e5, 0, "a", 6, 0 }, // latin small letter a with ring above
	{ 0x00e6, 1, "ae", 0, 0 }, // latin small letter ae
	{ 0x00e7, 0, "c", 7, 0 }, // latin small letter c with cedilla
	{ 0x00e8, 0, "e", 2, 0 }, // latin small letter e with grave
	{ 0x00e9, 0, "e", 1, 0 }, // latin small letter e with acute
	{ 0x00ea, 0, "e", 3, 0 }, // latin small letter e with circumflex
	{ 0x00eb, 0, "e", 4, 0 }, // latin small letter e with diaeresis
	{ 0x00ec, 0, "i", 2, 0 }, // latin small letter i with grave
	{ 0x00ed, 0, "i", 1, 0 }, // latin small letter i with acute
	{ 0x00ee, 0, "i", 3, 0 }, // latin small letter i with circumflex
	{ 0x00ef, 0, "i", 4, 0 }, // latin small letter i with diaeresis
	{ 0x00f0, 3, "d", 0, 0 }, // latin small letter eth
	{ 0x00f1, 0, "n", 5, 0 }, // latin small letter n with tilde
	{ 0x00f2, 0, "o", 2, 0 }, // latin small letter o with grave
	{ 0x00f3, 0, "o", 1, 0 }, // latin small letter o with acute
	{ 0x00f4, 0, "o", 3, 0 }, // latin small letter o with circumflex
	{ 0x00f5, 0, "o", 5, 0 }, // latin small letter o with tilde
	{ 0x00f6, 0, "o", 4, 0 }, // latin small letter o with diaeresis
	{ 0x00f8, 3, "o", 0, 0 }, // latin small letter o with stroke
	{ 0x00f9, 0, "u", 2, 0 }, // latin small letter u with grave
	{ 0x00fa, 0, "u", 1, 0 }, // latin small letter u with acute
	{ 0x00fb, 0, "u", 3, 0 }, // latin small letter u with circumflex
	{ 0x00fc, 0, "u", 4, 0 }, // latin small letter u with diaeresis
	{ 0x00fd, 0, "y", 1, 0 }, // latin small letter y with acute
	{ 0x00fe, 3, "p", 0, 0 }, // latin small letter thorn
	{ 0x00ff, 0, "y", 4, 0 }, // latin small letter y with diaeresis
	{ 0x0100, 0, "A", 10, 0 }, // latin capital letter a with macron
	{ 0x0101, 0, "a", 10, 0 }, // latin small letter a with macron
	{ 0x0102, 0, "A", 9, 0 }, // latin capital letter a with breve
	{ 0x0103, 0, "a", 9, 0 }, // latin small letter a with breve
	{ 0x0104, 0, "A", 13, 0 }, // latin capital letter a with ogonek
	{ 0x0105, 0, "a", 13, 0 }, // latin small letter a with ogonek
	{ 0x0106, 0, "C", 1, 0 }, // latin capital letter c with acute
	{ 0x0107, 0, "c", 1, 0 }, // latin small letter c with acute
	{ 0x0108, 0, "C", 3, 0 }, // latin capital letter c with circumflex
	{ 0x0109, 0, "c", 3, 0 }, // latin small letter c with circumflex
	{ 0x010a, 0, "C", 11, 0 }, // latin capital letter c with dot above
	{ 0x010b, 0, "c", 11, 0 }, // latin small letter c with dot above
	{ 0x010c, 0, "C", 8, 0 }, // latin capital letter c with caron
	{ 0x010d, 0, "c", 8, 0 }, // latin small letter c with caron
	{ 0x010e, 0, "D", 8, 0 }, // latin capital letter d with caron
	{ 0x010f, 0, "d", 8, 0 }, // latin small letter d with caron
	{ 0x0110, 3, "D", 0, 0 }, // latin capital letter d with stroke
	{ 0x0111, 3, "d", 0, 0 }, // latin small letter d with stroke
	{ 0x0112, 0, "E", 10, 0 }, // latin capital letter e with macron
	{ 0x0113, 0, "e", 10, 0 }, // latin small letter e with macron
	{ 0x0114, 0, "E", 9, 0 }, // latin capital letter e with breve
	{ 0x0115, 0, "e", 9, 0 }, // latin small letter e with breve
	{ 0x0116, 0, "E", 11, 0 }, // latin capital letter e with dot above
	{ 0x0117, 0, "e", 11, 0 }, // latin small letter e with dot above
	{ 0x0118, 0, "E", 13, 0 }, // latin capital letter e with ogonek
	{ 0x0119, 0, "e", 13, 0 }, // latin small letter e with ogonek
	{ 0x011a, 0, "E", 8, 0 }, // latin capital letter e with caron
	{ 0x011b, 0, "e", 8, 0 }, // latin small letter e with caron
	{ 0x011c, 0, "G", 3, 0 }, // latin capital letter g with circumflex
	{ 0x011d, 0, "g", 3, 0 }, // latin small letter g with circumflex
	{ 0x011e, 0, "G", 9, 0 }, // latin capital letter g with breve
	{ 0x011f, 0, "g", 9, 0 }, // latin small letter g with breve
	{ 0x0120, 0, "G", 11, 0 }, // latin capital letter g with dot above
	{ 0x0121, 0, "g", 11, 0 }, // latin small letter g with dot above
	{ 0x0122, 0, "G", 7, 0 }, // latin capital letter g with cedilla
	{ 0x0123, 0, "g", 7, 0 }, // latin small letter g with cedilla
	{ 0x0124, 0, "H", 3, 0 }, // latin capital letter h with circumflex
	{ 0x0125, 0, "h", 3, 0 }, // latin small letter h with circumflex
	{ 0x0126, 3, "H", 0, 0 }, // latin capital letter h with stroke
	{ 0x0127, 3, "h", 0, 0 }, // latin small letter h with stroke
	{ 0x0128, 0, "I", 5, 0 }, // latin capital letter i with tilde
	{ 0x0129, 0, "i", 5, 0 }, // latin small letter i with tilde
	{ 0x012a, 0, "I", 10, 0 }, // latin capital letter i with macron
	{ 0x012b, 0, "i", 10, 0 }, // latin small letter i with macron
	{ 0x012c, 0, "I", 9, 0 }, // latin capital letter i with breve
	{ 0x012d, 0, "i", 9, 0 }, // latin small letter i with breve
	{ 0x012e, 0, "I", 13, 0 }, // latin capital letter i with ogonek
	{ 0x012f, 0, "i", 13, 0 }, // latin small letter i with ogonek
	{ 0x0130, 0, "I", 11, 0 }, // latin capital letter i with dot above
	{ 0x0131, 3, "i", 0, 0 }, // latin small letter dotless i
	{ 0x0134, 0, "J", 3, 0 }, // latin capital letter j with circumflex
	{ 0x0135, 0, "j", 3, 0 }, // latin small letter j with circumflex
	{ 0x0136, 0, "K", 7, 0 }, // latin capital letter k with cedilla
	{ 0x0137, 0, "k", 7, 0 }, // latin small letter k with cedilla
	{ 0x0139, 0, "L", 1, 0 }, // latin capital letter l with acute
	{ 0x013a, 0, "l", 1, 0 }, // latin small letter l with acute
	{ 0x013b, 0, "L", 7, 0 }, // latin capital letter l with cedilla
	{ 0x013c, 0, "l", 7, 0 }, // latin small letter l with cedilla
	{ 0x013d, 0, "L", 8, 0 }, // latin capital letter l with caron
	{ 0x013e, 0, "l", 8, 0 }, // latin small letter l with caron
	{ 0x0141, 3, "L", 0, 0 }, // latin capital letter l with stroke
	{ 0x0142, 3, "l", 0, 0 }, // latin small letter l with stroke
	{ 0x0143, 0, "N", 1, 0 }, // latin capital letter n with acute
	{ 0x0144, 0, "n", 1, 0 }, // latin small letter n with acute
	{ 0x0145, 0, "N", 7, 0 }, // latin capital letter n with cedilla
	{ 0x0146, 0, "n", 7, 0 }, // latin small letter n with cedilla
	{ 0x0147, 0, "N", 8, 0 }, // latin capital letter n with caron
	{ 0x0148, 0, "n", 8, 0 }, // latin small letter n with caron
	{ 0x014c, 0, "O", 10, 0 }, // latin capital letter o with macron
	{ 0x014d, 0, "o", 10, 0 }, // latin small letter o with macron
	{ 0x014e, 0, "O", 9, 0 }, // latin capital letter o with breve
	{ 0x014f, 0, "o", 9, 0 }, // latin small letter o with breve
	{ 0x0150, 0, "O", 12, 0 }, // latin capital letter o with double acute
	{ 0x0151, 0, "o", 12, 0 }, // latin small letter o with double acute
	{ 0x0152, 1, "OE", 0, 0 }, // latin capital ligature oe
	{ 0x0153, 1, "oe", 0, 0 }, // latin small ligature oe
	{ 0x0154, 0, "R", 1, 0 }, // latin capital letter r with acute
	{ 0x0155, 0, "r", 1, 0 }, // latin small letter r with acute
	{ 0x0156, 0, "R", 7, 0 }, // latin capital letter r with cedilla
	{ 0x0157, 0, "r", 7, 0 }, // latin small letter r with cedilla
	{ 0x0158, 0, "R", 8, 0 }, // latin capital letter r with caron
	{ 0x0159, 0, "r", 8, 0 }, // latin small letter r with caron
	{ 0x015a, 0, "S", 1, 0 }, // latin capital letter s with acute
	{ 0x015b, 0, "s", 1, 0 }, // latin small letter s with acute
	{ 0x015c, 0, "S", 3, 0 }, // latin capital letter s with circumflex
	{ 0x015d, 0, "s", 3, 0 }, // latin small letter s with circumflex
	{ 0x015e, 0, "S", 7, 0 }, // latin capital letter s with cedilla
	{ 0x015f, 0, "s", 7, 0 }, // latin small letter s with cedilla
	{ 0x0160, 0, "S", 8, 0 }, // latin capital letter s with caron
	{ 0x0161, 0, "s", 8, 0 }, // latin small letter s with caron
	{ 0x0162, 0, "T", 7, 0 }, // latin capital letter t with cedilla
	{ 0x0163, 0, "t", 7, 0 }, // latin small letter t with cedilla
	{ 0x0164, 0, "T", 8, 0 }, // latin capital letter t with caron
	{ 0x0165, 0, "t", 8, 0 }, // latin small letter t with caron
	{ 0x0168, 0, "U", 5, 0 }, // latin capital letter u with tilde
	{ 0x0169, 0, "u", 5, 0 }, // latin small letter u with tilde
	{ 0x016a, 0, "U", 10, 0 }, // latin capital letter u with macron
	{ 0x016b, 0, "u", 10, 0 }, // latin small letter u with macron
	{ 0x016c, 0, "U", 9, 0 }, // latin capital letter u with breve
	{ 0x016d, 0, "u", 9, 0 }, // latin small letter u with breve
	{ 0x016e, 0, "U", 6, 0 }, // latin capital letter u with ring above
	{ 0x016f, 0, "u", 6, 0 }, // latin small letter u with ring above
	{ 0x0170, 0, "U", 12, 0 }, // latin capital letter u with double acute
	{ 0x0171, 0, "u", 12, 0 }, // latin small letter u with double acute
	{ 0x0172, 0, "U", 13, 0 }, // latin capital letter u with ogonek
	{ 0x0173, 0, "u", 13, 0 }, // latin small letter u with ogonek
	{ 0x0174, 0, "W", 3, 0 }, // latin capital letter w with circumflex
	{ 0x0175, 0, "w", 3, 0 }, // latin small letter w with circumflex
	{ 0x0176, 0, "Y", 3, 0 }, // latin capital letter y with circumflex
	{ 0x0177, 0, "y", 3, 0 }, // latin small letter y with circumflex
	{ 0x0178, 0, "Y", 4, 0 }, // latin capital letter y with diaeresis
	{ 0x0179, 0, "Z", 1, 0 }, // latin capital letter z with acute
	{ 0x017a, 0, "z", 1, 0 }, // latin small letter z with acute
	{ 0x017b, 0, "Z", 11, 0 }, // latin capital letter z with dot above
	{ 0x017c, 0, "z", 11, 0 }, // latin small letter z with dot above
	{ 0x017d, 0, "Z", 8, 0 }, // latin capital letter z with caron
	{ 0x017e, 0, "z", 8, 0 }, // latin small letter z with caron
	{ 0x0218, 0, "S", 14, 0 }, // latin capital letter s with comma below
	{ 0x0219, 0, "s", 14, 0 }, // latin small letter s with comma below
	{ 0x021a, 0, "T", 14, 0 }, // latin capital letter t with comma below
	{ 0x021b, 0, "t", 14, 0 }, // latin small letter t with comma below
	{ 0x02c6, 5, " ", 3, 0 }, // modifier letter circumflex accent
	{ 0x02dc, 5, " ", 5, 0 }, // small tilde
	{ 0x1e9e, 4, "S", 0, 0 }, // latin capital letter sharp s
	{ 0x2009, 3, " ", 0, 0 }, // thin space
	{ 0x2010, 3, "-", 0, 0 }, // hyphen
	{ 0x2011, 3, "-", 0, 0 }, // non-breaking hyphen
	{ 0x2013, 3, "-", 0, 0 }, // en dash
	{ 0x2014, 3, "-", 0, 0 }, // em dash
	{ 0x2018, 3, "\'", 0, 0 }, // left single quotation mark
	{ 0x2019, 3, "\'", 0, 0 }, // right single quotation mark
	{ 0x201a, 3, ",", 0, 0 }, // single low-9 quotation mark
	{ 0x201c, 3, "\"", 0, 0 }, // left double quotation mark
	{ 0x201d, 3, "\"", 0, 0 }, // right double quotation mark
	{ 0x201e, 1, ",,", 0, 0 }, // double low-9 quotation mark
	{ 0x2022, 3, "*", 0, 0 }, // bullet
	{ 0x2026, 1, "..", 0, 0 }, // horizontal ellipsis
	{ 0x202f, 3, " ", 0, 0 }, // narrow no-break space
	{ 0x2039, 3, "<", 0, 0 }, // single left-pointing angle quotation mark
	{ 0x203a, 3, ">", 0, 0 }, // single right-pointing angle quotation mark
	{ 0x20ac, 3, "E", 0, 0 }, // euro sign
	{ 0x2122, 3, "T", 0, 0 }, // trade mark sign
	{ 0x2212, 3, "-", 0, 0 }, // minus sign
};
