#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <PR/ultratypes.h>
#include "platform.h"
#include "data.h"
#include "types.h"
#include "constants.h"
#include "bss.h"
#include "game/menu.h"
#include "config.h"
#include "fs.h"
#include "system.h"
#include "update.h"
#include "gexfront.h"
#include "patchnotes.h"
// Generated by CMake from patchnotes.txt: PATCHNOTES_NUMBER and the file itself.
#include "patchnotesdata.h"

/**
 * See patchnotes.h for what this is, and the top of patchnotes.txt for how an
 * entry is written. This file is how the game reads one.
 *
 * The format is lines of words, like update.txt and for the same reason: it is
 * written by hand, by whoever merges a fix, and read by this, and neither end
 * gains anything from braces. An entry is a line that says
 *
 *     notes <number> <date>
 *
 * and every line after it until the next one is a fix. Lines that start with #
 * are comments, blank lines separate entries, and anything above the first
 * "notes" line is the file's own instructions.
 *
 * Which entries a page shows is a range of numbers and nothing else. The build
 * knows the newest number it was configured with, so what an update brings is
 * everything above that number in the release's copy, and what a player who
 * just updated has not seen is everything above the number pd.ini remembers.
 */

// The formatted text, which menuitemScrollableRender() wraps into a buffer of
// 8000. Wrapping only ever turns a space into a line break or adds the odd
// break inside a long word, so this leaves it room; notes past it are cut at a
// line, with a word to say so.
#define PATCHNOTES_MAXTEXT 6000

// Longer than a fix should ever be. A longer line is cut, not dropped.
#define PATCHNOTES_MAXLINE 400

#define PATCHNOTES_VIEW_POPUP  0
#define PATCHNOTES_VIEW_UPDATE 1

/**
 * Mod.PatchNotesPopup: show what an update brought, once, on the main menu.
 *
 * On by default, which is an exception to the rule that a fresh pd.ini is stock
 * Perfect Dark with the fork's additions off. That rule is about how the game
 * plays and looks; this changes neither, is shown once per update and never to
 * a new player (see patchnotesInit()), and was asked for on by default.
 */
static s32 g_PopupEnabled = 1;

/**
 * Mod.PatchNotesSeen: the newest entry this install has been shown or skipped.
 *
 * -1, the default, is "never written", which is two different players: a new
 * one, whose pd.ini did not exist when the game started, and one updating from
 * a build that had no patch notes, whose pd.ini did. patchnotesInit() tells
 * them apart.
 */
static s32 g_Seen = -1;

// What g_Seen was when this run started, so the popup shows everything the
// player has not seen even after g_Seen has moved on.
static s32 g_SeenAtStart = -1;

static bool g_PopupPending = false;
static bool g_PopupDone = false;

static s32 g_View = PATCHNOTES_VIEW_UPDATE;
static char g_Title[48] = "Patch Notes";
static char g_PopupText[PATCHNOTES_MAXTEXT];
static char g_UpdateText[PATCHNOTES_MAXTEXT];

// What g_UpdateText was formatted from, so it is only formatted again when the
// check has fetched something different or has changed its mind about whether
// there is a newer build.
static u32 g_UpdateGeneration = 0;
static s32 g_UpdateFound = -1;
static s32 g_UpdateCount = 0;

s32 patchnotesBuildNumber(void)
{
	return PATCHNOTES_NUMBER;
}

static const char *patchnotesBuiltIn(void)
{
	return (const char *)g_PatchNotesBuiltIn;
}

/**
 * Whether a line has something in it that looks like an IPv4 address.
 *
 * The notes are written from tester reports, and every report carries the
 * address it came from. None of that belongs in front of players, and the
 * instructions say so - this is the belt to those braces. A line with four
 * dot-separated runs of one to three digits is left out whole, because a
 * version number written like that is far less likely than a pasted address.
 */
static bool patchnotesHasAddress(const char *line)
{
	const char *p;

	for (p = line; *p; p++) {
		const char *q = p;
		s32 groups = 0;

		if (p != line && ((p[-1] >= '0' && p[-1] <= '9') || p[-1] == '.')) {
			continue;
		}

		while (groups < 4) {
			s32 digits = 0;

			while (*q >= '0' && *q <= '9' && digits < 4) {
				q++;
				digits++;
			}

			if (digits == 0 || digits > 3) {
				break;
			}

			groups++;

			if (groups < 4) {
				if (*q != '.') {
					break;
				}

				q++;
			}
		}

		if (groups == 4) {
			return true;
		}
	}

	return false;
}

/**
 * One line of the file, as the menu can draw it.
 *
 * The menu font has ASCII and nothing else, so a byte outside it becomes a
 * question mark - once per character rather than once per byte, which is what
 * skipping UTF-8's continuation bytes does. "|" starts a heading in the
 * scrollable's renderer and would turn the rest of a fix red, so it is a
 * slash. Trailing spaces and a Windows line ending go.
 */
static void patchnotesCleanLine(const char *in, u32 inlen, char *out, u32 outsize)
{
	u32 len = 0;
	u32 i;

	for (i = 0; i < inlen && len + 1 < outsize; i++) {
		u8 c = (u8)in[i];

		if (c == '\t') {
			c = ' ';
		} else if (c >= 0x80 && c < 0xc0) {
			continue;
		} else if (c < 0x20 || c >= 0x7f) {
			if (c == '\r') {
				continue;
			}

			c = '?';
		} else if (c == '|') {
			c = '/';
		}

		out[len++] = (char)c;
	}

	while (len > 0 && out[len - 1] == ' ') {
		len--;
	}

	out[len] = '\0';
}

/**
 * Whether a line is an entry's header, and if so its number and date.
 *
 * Only "notes", a number and at most one word after it. A fix that happens to
 * begin with the word notes is still a fix.
 */
static bool patchnotesParseHeader(const char *line, s32 *num, char *date, u32 datesize)
{
	char word[32];
	int consumed = 0;
	int value;

	if (strncmp(line, "notes ", 6) != 0 || sscanf(line, "notes %d%n", &value, &consumed) != 1) {
		return false;
	}

	date[0] = '\0';
	word[0] = '\0';
	line += consumed;

	while (*line == ' ') {
		line++;
	}

	if (*line) {
		if (sscanf(line, "%31s%n", word, &consumed) != 1) {
			return false;
		}

		line += consumed;

		while (*line == ' ') {
			line++;
		}

		if (*line) {
			return false;
		}
	}

	*num = value;
	snprintf(date, datesize, "%s", word);

	return true;
}

static bool patchnotesAppend(char *out, u32 outsize, u32 *len, const char *text)
{
	u32 add = (u32)strlen(text);

	if (*len + add + 1 > outsize) {
		return false;
	}

	memcpy(out + *len, text, add + 1);
	*len += add;

	return true;
}

/**
 * The fixes of every entry numbered above `after` and up to `upto`, in the
 * order the file has them (newest first), as the scrollable's text. Returns
 * how many fixes it wrote.
 *
 * An entry's heading is written with its first fix rather than when its
 * header is read, so an entry with nothing under it is not a heading on its
 * own.
 */
static s32 patchnotesFormat(const char *text, s32 after, s32 upto, char *out, u32 outsize)
{
	const char *at = text;
	char heading[96] = { 0 };
	u32 len = 0;
	s32 fixes = 0;
	bool inrange = false;

	out[0] = '\0';

	// Room for the note that says the rest was cut.
	outsize -= 64;

	while (at && *at) {
		const char *eol = strchr(at, '\n');
		u32 linelen = eol ? (u32)(eol - at) : (u32)strlen(at);
		char line[PATCHNOTES_MAXLINE];
		char date[32];
		s32 num;

		patchnotesCleanLine(at, linelen, line, sizeof(line));
		at = eol ? eol + 1 : NULL;

		if (line[0] == '\0' || line[0] == '#') {
			continue;
		}

		if (patchnotesParseHeader(line, &num, date, sizeof(date))) {
			inrange = num > after && num <= upto;

			// A heading is "|", its text and a blank line; the renderer draws
			// it outdented and in red.
			snprintf(heading, sizeof(heading), "%s|Patch %d%s%s\n\n",
					len > 0 ? "\n" : "", num, date[0] ? " - " : "", date);
			continue;
		}

		if (!inrange || patchnotesHasAddress(line)) {
			continue;
		}

		if (heading[0]) {
			if (!patchnotesAppend(out, outsize, &len, heading)) {
				goto cut;
			}

			heading[0] = '\0';
		}

		if (!patchnotesAppend(out, outsize, &len, "- ")
				|| !patchnotesAppend(out, outsize, &len, line)
				|| !patchnotesAppend(out, outsize, &len, "\n")) {
			goto cut;
		}

		fixes++;
	}

	return fixes;

cut:
	// Back to the end of the last whole line, then say so. The full notes are
	// the file on the release page, and a menu is no place for all of them.
	while (len > 0 && out[len - 1] != '\n') {
		len--;
	}

	out[len] = '\0';
	outsize += 64;
	patchnotesAppend(out, outsize, &len, "\n(Older notes are in patchnotes.txt on the release page.)\n");

	return fixes;
}

/**
 * The Check for Updates view, formatted again when what it is made of changed.
 *
 * A newer release with notes above this build's number shows those: that is
 * what installing it brings. Anything else - no newer release, a release
 * without notes, one that has none this build lacks, no check yet - shows what
 * this build itself has, from the copy baked into it, which is the same text
 * whether the player is online or not.
 */
static void patchnotesRefreshUpdateView(void)
{
	u32 generation = updateGetNotesGeneration();
	s32 state = updateGetState();
	s32 found = state == UPDATE_FOUND || state == UPDATE_STAGED;
	s32 mine = patchnotesBuildNumber();

	if (generation == g_UpdateGeneration && found == g_UpdateFound) {
		return;
	}

	g_UpdateGeneration = generation;
	g_UpdateFound = found;
	g_UpdateCount = 0;

	if (found) {
		char *fetched = updateCopyNotes();

		if (fetched) {
			g_UpdateCount = patchnotesFormat(fetched, mine, INT_MAX, g_UpdateText, sizeof(g_UpdateText));
			free(fetched);
		}
	}

	if (g_UpdateCount == 0
			&& patchnotesFormat(patchnotesBuiltIn(), INT_MIN, mine, g_UpdateText, sizeof(g_UpdateText)) == 0) {
		snprintf(g_UpdateText, sizeof(g_UpdateText), "This build has no patch notes.\n");
	}
}

s32 patchnotesCountForUpdate(void)
{
	patchnotesRefreshUpdateView();

	return g_UpdateCount;
}

char *patchnotesGetText(void)
{
	if (g_View == PATCHNOTES_VIEW_POPUP) {
		return g_PopupText;
	}

	patchnotesRefreshUpdateView();

	return g_UpdateText;
}

void patchnotesOpenForUpdate(void)
{
	patchnotesRefreshUpdateView();

	g_View = PATCHNOTES_VIEW_UPDATE;
	snprintf(g_Title, sizeof(g_Title), "%s", g_UpdateCount > 0 ? "What's in the Update" : "What's New in This Build");

	menuPushDialog(&g_PatchNotesMenuDialog);
}

bool patchnotesPopupIsEnabled(void)
{
	return g_PopupEnabled != 0;
}

void patchnotesPopupSetEnabled(bool enabled)
{
	g_PopupEnabled = enabled ? 1 : 0;
}

/**
 * Remember that this build's notes have been dealt with, and write it down now.
 *
 * Now rather than at exit, like the report name in tracereport.c: a game that
 * crashes or is killed before it exits would otherwise show the same notes
 * again next time, and the one promise this makes is "once".
 */
static void patchnotesMarkSeen(void)
{
	if (g_Seen < patchnotesBuildNumber()) {
		g_Seen = patchnotesBuildNumber();
		configSave(CONFIG_PATH);
	}
}

/**
 * The popup, from the Perfect Menu's tick while it is the dialog on top.
 *
 * The Perfect Menu is the main menu - where the game lands after the file is
 * chosen, and where a player finishing a mission comes back to - and asking
 * from its own tick is what keeps this off everything else: the intro, the
 * title, a boot notice drawn on the window, a mission's pause menu, and any
 * dialog already open over the menu. It waits for the menu to have finished
 * opening, and for GE Plus's folder when that is what is showing.
 */
void patchnotesMainMenuTick(void)
{
	struct menudialog *dialog = g_Menus[g_MpPlayerNum].curdialog;
	s32 fixes;

	if (g_PopupDone) {
		return;
	}

	if (!g_PopupPending || !g_PopupEnabled) {
		// Switched off before it had a chance to show: the notes count as
		// seen, so that switching it back on later does not bring them back.
		g_PopupDone = true;
		patchnotesMarkSeen();
		return;
	}

	if (g_Vars.stagenum != STAGE_CITRAINING || gexFrontIsActive()
			|| dialog == NULL || dialog->state != MENUDIALOGSTATE_POPULATED) {
		return;
	}

	g_PopupDone = true;

	// The copy baked into the build, so this works offline: it is by
	// definition what the build that was just started contains.
	fixes = patchnotesFormat(patchnotesBuiltIn(), g_SeenAtStart, patchnotesBuildNumber(),
			g_PopupText, sizeof(g_PopupText));

	patchnotesMarkSeen();

	if (fixes == 0) {
		return;
	}

	sysLogPrintf(LOG_NOTE, "patchnotes: showing %d fixes since notes %d", fixes, g_SeenAtStart);

	g_View = PATCHNOTES_VIEW_POPUP;
	snprintf(g_Title, sizeof(g_Title), "What's New");
	menuPushDialog(&g_PatchNotesMenuDialog);
}

/**
 * Decide whether this start is the first after an update.
 *
 * Called straight after configInit(), because whether pd.ini existed is part of
 * the answer and the next thing to run - GE Plus's first conversion - can write
 * one. A player with no pd.ini is new: they are given the number silently and
 * shown nothing, since a list of fixes to a game they have not played yet
 * tells them nothing. A player with a pd.ini but no number updated from a
 * build before the notes existed, and is shown all of them.
 */
void patchnotesInit(void)
{
	s32 mine = patchnotesBuildNumber();

	if (g_Seen < 0 && fsFileSize(CONFIG_PATH) <= 0) {
		g_Seen = mine;
		g_PopupDone = true;
		return;
	}

	g_SeenAtStart = g_Seen;
	g_PopupPending = mine > g_Seen;

	if (g_PopupPending) {
		sysLogPrintf(LOG_NOTE, "patchnotes: this build has notes %d, this install has seen %d%s",
				mine, g_Seen, g_PopupEnabled ? "" : " (popup off)");
	}
}

struct menuitem g_PatchNotesMenuItems[] = {
	{
		// The notes. The only row that takes focus, so up and down scroll
		// it rather than moving between rows, as on a character's profile.
		MENUITEMTYPE_SCROLLABLE,
		DESCRIPTION_PATCHNOTES,
		0,
		0,
		0,
		NULL,
	},
	{
		MENUITEMTYPE_SEPARATOR,
		0,
		0,
		0,
		0,
		NULL,
	},
	{
		MENUITEMTYPE_LABEL,
		0,
		MENUITEMFLAG_SELECTABLE_CENTRE | MENUITEMFLAG_SMALLFONT | MENUITEMFLAG_LITERAL_TEXT,
		(uintptr_t)"Up and down scroll. Confirm or back closes.\n",
		0,
		NULL,
	},
	{ MENUITEMTYPE_END },
};

struct menudialogdef g_PatchNotesMenuDialog = {
	MENUDIALOGTYPE_DEFAULT,
	(uintptr_t)g_Title,
	g_PatchNotesMenuItems,
	NULL,
	// Confirm closes it as well as back: the popup is in the way of the menu
	// the player came for, and either button should be the way past it.
	MENUDIALOGFLAG_LITERAL_TEXT | MENUDIALOGFLAG_DISABLEITEMSCROLL | MENUDIALOGFLAG_CLOSEONSELECT,
	NULL,
};

PD_CONSTRUCTOR static void patchnotesConfigInit(void)
{
	configRegisterInt("Mod.PatchNotesPopup", &g_PopupEnabled, 0, 1);
	configRegisterInt("Mod.PatchNotesSeen", &g_Seen, -1, 0x7fffffff);
}
