"""The GoldenEye -> Perfect Dark AI command map.

Generated by .xbla-work/ge-arena/genaitable.py - read that for how each row
was found. A row is GoldenEye's opcode:

    (name, length, [(argument, width)], perfect dark opcode, (argument specs))

and an argument spec makes one Perfect Dark argument: `n` copies GoldenEye's
argument n at its own width, `(n, w)` copies it as w bytes, `("=", v, w)` is a
constant and `("&", n, mask)` copies argument n masked, at its own width.

An argument named ANIMATION_ID is one of GoldenEye's own animation numbers and
is written with 0x8000 set, the way a PAD or a TEXT_SLOT is rewritten: the port
maps a tagged id to whatever the mod's animation took when it was appended, and
leaves everything else alone. Without the tag a stock Perfect Dark ailist -
which a mission's chrs do fall back on - would have its own aiChrDoAnimation
read as GoldenEye's. A row whose Perfect Dark opcode is None has no equivalent and the
command is left out of the converted list.
"""

# Perfect Dark's own chr ids (constants.h). The rows below carry 0x00f2
# inlined, which is CHR_P1P2 - the generator called it CHR_BOND, and for a
# solo mission the two resolve to the same player.
CHR_BOND = 0x00f8
CHR_SELF = 0x00fd

# PlayAnimation's bitfield is Perfect Dark's chranimflags bit for bit where the
# two games kept the same meaning - chrStartAnim() is GoldenEye's own
# chrlvPerformAnimationForActor() line for line - and the conversion keeps only
# those bits:
#
#   0x01 mirror        = CHRANIMFLAG_FLIP
#   0x02 (unknown)     = CHRANIMFLAG_MOVEWHENINVIS (act_anim.unk02c, same slot)
#   0x04 hold last     = CHRANIMFLAG_PAUSEATEND
#   0x10 idle on end   = CHRANIMFLAG_SLOWUPDATE (both set chr->sleep = merge)
#   0x40 no translate  = CHRANIMFLAG_LOCKPOS
#   0x80 reverse       = CHRANIMFLAG_REVERSE
#
# 0x08 is GoldenEye's "play the sneeze sound" and Perfect Dark's
# CHRANIMFLAG_COMPLETED, which would end the animation the moment it started,
# and 0x20 is a translation scale of 4 that Perfect Dark has no flag for
# (GoldenEye calls modelSetAnimTranslationScale() outside the flags). Both go.
ANIM_FLAGS = 0xd7

# opcode: (name, length, args, pd opcode, pd args, where the row came from)
TABLE = [
    ('GotoNext',                            2,    [('LABEL', 1)],                                0x0000, (0,),                                        'both'),  # 00 aiGoToNext
    ('GotoFirst',                           2,    [('LABEL', 1)],                                0x0001, (0,),                                        'both'),  # 01 aiGoToFirst
    ('Label',                               2,    [('ID', 1)],                                   0x0002, (0,),                                        'both'),  # 02 aiLabel
    ('Yield',                               1,    [],                                            0x0003, (),                                          'both'),  # 03 aiYield
    ('EndList',                             1,    [],                                            0x0004, (),                                          'both'),  # 04 aiEndList
    ('SetChrAiList',                        4,    [('CHR_NUM', 1), ('AI_LIST_ID', 2)],           0x0005, (0, 1),                                      'both'),  # 05 aiSetList
    ('SetReturnAiList',                     3,    [('AI_LIST_ID', 2)],                           0x0006, (('=', 253, 1), 0),                          'hand'),  # 06 aiSetReturnList
    ('Return',                              1,    [],                                            0x0008, (),                                          'both'),  # 07 aiReturn
    ('Stop',                                1,    [],                                            0x0009, (),                                          'both'),  # 08 aiStop
    ('Kneel',                               1,    [],                                            0x000a, (),                                          'both'),  # 09 aiKneel
    ('PlayAnimation',                       9,    [('ANIMATION_ID', 2), ('START_TIME30', 2), ('END_TIME30', 2), ('BITFIELD', 1), ('INTERPOL_TIME60', 1)], 0x000b, (0, 1, 2, ('&', 3, ANIM_FLAGS), 4, ('=', CHR_SELF, 1), ('=', 2, 1)), 'hand'),  # 0a aiChrDoAnimation
    ('IFPlayingAnimation',                  2,    [('GOTOLABEL', 1)],                            0x000c, (0,),                                        'hand'),  # 0b aiIfIdle
    ('PointAtBond',                         1,    [],                                            0x000d, (),                                          'table'),  # 0c aiBeSurprisedOneHand
    ('LookSurprised',                       1,    [],                                            0x000e, (),                                          'table'),  # 0d aiBeSurprisedLookAround
    ('TRYSidestepping',                     2,    [('GOTOLABEL', 1)],                            0x000f, (0,),                                        'both'),  # 0e aiTrySidestep
    ('TRYSideHopping',                      2,    [('GOTOLABEL', 1)],                            0x0010, (0,),                                        'table'),  # 0f aiTryJumpOut
    ('TRYSideRunning',                      2,    [('GOTOLABEL', 1)],                            0x0011, (0,),                                        'both'),  # 10 aiTryRunSideways
    ('TRYFiringWalk',                       2,    [('GOTOLABEL', 1)],                            0x0012, (0,),                                        'both'),  # 11 aiTryAttackWalk
    ('TRYFiringRun',                        2,    [('GOTOLABEL', 1)],                            0x0013, (0,),                                        'both'),  # 12 aiTryAttackRun
    ('TRYFiringRoll',                       2,    [('GOTOLABEL', 1)],                            0x0014, (0,),                                        'both'),  # 13 aiTryAttackRoll
    ('TRYFireOrAimAtTarget',                6,    [('BITFIELD', 2), ('TARGET', 2), ('GOTOLABEL', 1)], 0x0015, (0, 1, 2),                                   'both'),  # 14 aiTryAttackStand
    ('TRYFireOrAimAtTargetKneel',           6,    [('BITFIELD', 2), ('TARGET', 2), ('GOTOLABEL', 1)], 0x0016, (0, 1, 2),                                   'both'),  # 15 aiTryAttackKneel
    ('TRYFireOrAimAtTargetUpdate',          6,    [('BITFIELD', 2), ('TARGET', 2), ('GOTOLABEL', 1)], 0x0017, (0, 1, 2),                                   'both'),  # 16 aiTryModifyAttack
    ('TRYFacingTarget',                     6,    [('BITFIELD', 2), ('TARGET', 2), ('GOTOLABEL', 1)], 0x0018, (0, 1, 2),                                   'both'),  # 17 aiFaceEntity
    ('HitChrWithItem',                      4,    [('CHR_NUM', 1), ('PART_NUM', 1), ('ITEM_NUM', 1)], None,   (),                                          'hand'),  # 18 -
    ('ChrHitChr',                           4,    [('CHR_NUM', 1), ('CHR_NUM_TARGET', 1), ('PART_NUM', 1)], 0x001a, (0, 1, 2),                                   'table'),  # 19 aiChrDamageChr
    ('TRYThrowingGrenade',                  2,    [('GOTOLABEL', 1)],                            0x001b, (('=', 512, 2), ('=', 0, 2), 0),             'hand'),  # 1a aiConsiderGrenadeThrow
    ('TRYDroppingItem',                     5,    [('PROP_NUM', 2), ('ITEM_NUM', 1), ('GOTOLABEL', 1)], 0x001c, (0, 1, 2),                                   'table'),  # 1b aiDropItem
    ('RunToPad',                            3,    [('PAD', 2)],                                  0x001d, (0,),                                        'both'),  # 1c aiJogToPad
    ('RunToPadPreset',                      1,    [],                                            0x001e, (('=', 0, 1),),                              'hand'),  # 1d aiGoToPadPreset
    ('WalkToPad',                           3,    [('PAD', 2)],                                  0x001f, (0,),                                        'both'),  # 1e aiWalkToPad
    ('SprintToPad',                         3,    [('PAD', 2)],                                  0x0020, (0,),                                        'both'),  # 1f aiRunToPad
    ('StartPatrol',                         2,    [('PATH_NUM', 1)],                             0x0021, (0,),                                        'both'),  # 20 aiSetPath
    ('Surrender',                           1,    [],                                            0x0024, (),                                          'both'),  # 21 aiSurrender
    ('RemoveMe',                            1,    [],                                            0x0025, (),                                          'table'),  # 22 aiFadeOut
    ('ChrRemoveInstant',                    2,    [('CHR_NUM', 1)],                              0x0026, (0,),                                        'table'),  # 23 aiRemoveChr
    ('TRYTriggeringAlarmAtPad',             4,    [('PAD', 2), ('GOTOLABEL', 1)],                0x0027, (0, 1),                                      'table'),  # 24 aiTryStartAlarm
    ('AlarmOn',                             1,    [],                                            0x0028, (),                                          'table'),  # 25 aiActivateAlarm
    ('AlarmOff',                            1,    [],                                            0x0029, (),                                          'table'),  # 26 aiDeactivateAlarm
    ('TRYRunFromBond',                      2,    [('GOTOLABEL', 1)],                            0x002a, (0,),                                        'table'),  # 27 aiTryRunFromTarget
    ('TRYRunToBond',                        2,    [('GOTOLABEL', 1)],                            0x002b, (0,),                                        'both'),  # 28 aiTryJogToTargetProp
    ('TRYWalkToBond',                       2,    [('GOTOLABEL', 1)],                            0x002c, (0,),                                        'table'),  # 29 aiTryWalkToTargetProp
    ('TRYSprintToBond',                     2,    [('GOTOLABEL', 1)],                            0x002d, (0,),                                        'both'),  # 2a aiTryRunToTargetProp
    ('TRYFindCover',                        2,    [('GOTOLABEL', 1)],                            0x002e, (0,),                                        'table'),  # 2b aiTryGoToCoverProp
    ('TRYRunToChr',                         3,    [('CHR_NUM', 1), ('GOTOLABEL', 1)],            0x002f, (0, 1),                                      'table'),  # 2c aiTryJogToChr
    ('TRYWalkToChr',                        3,    [('CHR_NUM', 1), ('GOTOLABEL', 1)],            0x0030, (0, 1),                                      'table'),  # 2d aiTryWalkToChr
    ('TRYSprintToChr',                      3,    [('CHR_NUM', 1), ('GOTOLABEL', 1)],            0x0031, (0, 1),                                      'table'),  # 2e aiTryRunToChr
    ('IFImOnPatrolOrStopped',               2,    [('GOTOLABEL', 1)],                            0x0032, (0,),                                        'both'),  # 2f aiIfStopped
    ('IFChrDyingOrDead',                    3,    [('CHR_NUM', 1), ('GOTOLABEL', 1)],            0x0033, (0, 1),                                      'both'),  # 30 aiIfChrDead
    ('IFChrDoesNotExist',                   3,    [('CHR_NUM', 1), ('GOTOLABEL', 1)],            0x0034, (0, 1),                                      'both'),  # 31 aiIfChrDeathAnimationFinished
    ('IFISeeBond',                          2,    [('GOTOLABEL', 1)],                            0x0035, (0,),                                        'both'),  # 32 aiIfCanSeeTarget
    ('SetNewRandom',                        1,    [],                                            0x0036, (),                                          'both'),  # 33 aiRandom
    ('IFRandomLessThan',                    3,    [('BYTE', 1), ('GOTOLABEL', 1)],               0x0037, (0, 1),                                      'table'),  # 34 aiIfRandomLessThan
    ('IFRandomGreaterThan',                 3,    [('BYTE', 1), ('GOTOLABEL', 1)],               0x0038, (0, 1),                                      'both'),  # 35 aiIfRandomGreaterThan
    ('IFICanHearAlarm',                     2,    [('GOTOLABEL', 1)],                            0x0039, (0,),                                        'table'),  # 36 aiIfCanHearAlarm
    ('IFAlarmIsOn',                         2,    [('GOTOLABEL', 1)],                            0x003a, (0,),                                        'table'),  # 37 aiIfAlarmActive
    ('IFGasIsLeaking',                      2,    [('GOTOLABEL', 1)],                            0x003b, (0,),                                        'table'),  # 38 aiIfGasActive
    ('IFIHeardBond',                        2,    [('GOTOLABEL', 1)],                            0x003c, (0,),                                        'table'),  # 39 aiIfHearsTarget
    ('IFISeeSomeoneShot',                   2,    [('GOTOLABEL', 1)],                            0x003f, (0,),                                        'table'),  # 3a aiIfLosToTarget
    ('IFISeeSomeoneDie',                    2,    [('GOTOLABEL', 1)],                            0x0042, (0,),                                        'table'),  # 3b aiSetPadPresetToPadOnRouteToTarget
    ('IFICouldSeeBond',                     2,    [('GOTOLABEL', 1)],                            0x003f, (0,),                                        'hand'),  # 3c aiIfLosToTarget
    ('IFICouldSeeBondsStan',                2,    [('GOTOLABEL', 1)],                            0x003f, (0,),                                        'hand'),  # 3d aiIfLosToTarget
    ('IFIWasShotRecently',                  2,    [('GOTOLABEL', 1)],                            0x0043, (0,),                                        'table'),  # 3e aiIfSawTargetRecently
    ('IFIHeardBondRecently',                2,    [('GOTOLABEL', 1)],                            0x0044, (0,),                                        'table'),  # 3f aiIfHeardTargetRecently
    ('IFImInRoomWithChr',                   3,    [('CHR_NUM', 1), ('GOTOLABEL', 1)],            0x0045, (0, 1),                                      'table'),  # 40 aiIfLosToChr
    ('IFIveNotBeenSeen',                    2,    [('GOTOLABEL', 1)],                            0x0046, (0,),                                        'table'),  # 41 aiIfNeverBeenOnScreen
    ('IFImOnScreen',                        2,    [('GOTOLABEL', 1)],                            0x0047, (0,),                                        'both'),  # 42 aiIfOnScreen
    ('IFMyRoomIsOnScreen',                  2,    [('GOTOLABEL', 1)],                            0x0048, (('=', 253, 1), 0),                          'hand'),  # 43 aiIfChrInOnScreenRoom
    ('IFRoomWithPadIsOnScreen',             4,    [('PAD', 2), ('GOTOLABEL', 1)],                0x0049, (0, 1),                                      'table'),  # 44 aiIfRoomIsOnScreen
    ('IFImTargetedByBond',                  2,    [('GOTOLABEL', 1)],                            0x004a, (0,),                                        'table'),  # 45 aiIfTargetAimingAtMe
    ('IFBondMissedMe',                      2,    [('GOTOLABEL', 1)],                            0x004b, (0,),                                        'both'),  # 46 aiIfNearMiss
    ('IFMyAngleToBondLessThan',             3,    [('ANGLE', 1), ('GOTOLABEL', 1)],              0x004d, (0, 1),                                      'table'),  # 47 aiIfTargetInFovLeft
    ('IFMyAngleToBondGreaterThan',          3,    [('ANGLE', 1), ('GOTOLABEL', 1)],              0x004f, (0, 1),                                      'table'),  # 48 aiIfTargetOutOfFovLeft
    ('IFMyAngleFromBondLessThan',           3,    [('ANGLE', 1), ('GOTOLABEL', 1)],              0x0050, (0, 1),                                      'table'),  # 49 aiIfTargetInFov
    ('IFMyAngleFromBondGreaterThan',        3,    [('ANGLE', 1), ('GOTOLABEL', 1)],              0x0051, (0, 1),                                      'table'),  # 4a aiIfTargetOutOfFov
    ('IFMyDistanceToBondLessThanDecimeter', 4,    [('DISTANCE', 2), ('GOTOLABEL', 1)],           0x0052, (0, 1),                                      'both'),  # 4b aiIfDistanceToTargetLessThan
    ('IFMyDistanceToBondGreaterThanDecimeter', 4,    [('DISTANCE', 2), ('GOTOLABEL', 1)],           0x0053, (0, 1),                                      'both'),  # 4c aiIfDistanceToTargetGreaterThan
    ('IFChrDistanceToPadLessThanDecimeter', 7,    [('CHR_NUM', 1), ('DISTANCE', 2), ('PAD', 2), ('GOTOLABEL', 1)], 0x0054, (0, 1, 2, 3),                                'both'),  # 4d aiIfChrDistanceToPadLessThan
    ('IFChrDistanceToPadGreaterThanDecimeter', 7,    [('CHR_NUM', 1), ('DISTANCE', 2), ('PAD', 2), ('GOTOLABEL', 1)], 0x0055, (0, 1, 2, 3),                                'table'),  # 4e aiIfChrDistanceToPadGreaterThan
    ('IFMyDistanceToChrLessThanDecimeter',  5,    [('DISTANCE', 2), ('CHR_NUM', 1), ('GOTOLABEL', 1)], 0x0056, (0, 1, 2),                                   'table'),  # 4f aiIfDistanceToChrLessThan
    ('IFMyDistanceToChrGreaterThanDecimeter', 5,    [('DISTANCE', 2), ('CHR_NUM', 1), ('GOTOLABEL', 1)], 0x0057, (0, 1, 2),                                   'table'),  # 50 aiIfDistanceToChrGreaterThan
    ('TRYSettingMyPresetToChrWithinDistanceDecimeter', 4,    [('DISTANCE', 2), ('GOTOLABEL', 1)],           0x0058, (0, 1),                                      'table'),  # 51 ai0058
    ('IFBondDistanceToPadLessThanDecimeter', 6,    [('DISTANCE', 2), ('PAD', 2), ('GOTOLABEL', 1)], 0x0059, (0, 1, 2),                                   'table'),  # 52 aiIfDistanceFromTargetToPadLessThan
    ('IFBondDistanceToPadGreaterThanDecimeter', 6,    [('DISTANCE', 2), ('PAD', 2), ('GOTOLABEL', 1)], 0x005a, (0, 1, 2),                                   'table'),  # 53 aiIfDistanceFromTargetToPadGreaterThan
    ('IFChrInRoomWithPad',                  5,    [('CHR_NUM', 1), ('PAD', 2), ('GOTOLABEL', 1)], 0x005b, (0, ('=', 0, 1), 1, 2),                      'hand'),  # 54 aiIfChrInRoom
    ('IFBondInRoomWithPad',                 4,    [('PAD', 2), ('GOTOLABEL', 1)],                0x005c, (0, 1),                                      'table'),  # 55 aiIfTargetInRoom
    ('IFBondCollectedObject',               3,    [('OBJECT_TAG', 1), ('GOTOLABEL', 1)],         0x005d, (('=', 242, 1), 0, 1),                       'hand'),  # 56 aiIfChrHasObject
    ('IFKeyDropped',                        3,    [('ITEM_NUM', 1), ('GOTOLABEL', 1)],           0x005e, (0, 1),                                      'table'),  # 57 aiIfWeaponThrown
    ('IFItemIsAttachedToObject',            4,    [('ITEM_NUM', 1), ('OBJECT_TAG', 1), ('GOTOLABEL', 1)], 0x005f, (0, 1, 2),                                   'table'),  # 58 aiIfWeaponThrownOnObject
    ('IFBondHasItemEquipped',               3,    [('ITEM_NUM', 1), ('GOTOLABEL', 1)],           0x0060, (('=', 242, 1), 0, 1),                       'hand'),  # 59 aiIfChrHasWeaponEquipped
    ('IFObjectExists',                      3,    [('OBJECT_TAG', 1), ('GOTOLABEL', 1)],         0x0062, (0, 1),                                      'table'),  # 5a aiIfObjectHealthy
    ('IFObjectNotDestroyed',                3,    [('OBJECT_TAG', 1), ('GOTOLABEL', 1)],         0x0062, (0, 1),                                      'hand'),  # 5b aiIfObjectHealthy
    ('IFObjectWasActivated',                3,    [('OBJECT_TAG', 1), ('GOTOLABEL', 1)],         0x0063, (('=', 242, 1), 0, 1),                       'hand'),  # 5c aiIfChrActivatedObject
    ('IFBondUsedGadgetOnObject',            3,    [('OBJECT_TAG', 1), ('GOTOLABEL', 1)],         0x0063, (('=', 242, 1), 0, 1),                       'hand'),  # 5d aiIfChrActivatedObject
    ('ActivateObject',                      2,    [('OBJECT_TAG', 1)],                           0x0065, (0,),                                        'hand'),  # 5e aiObjInteract
    ('DestroyObject',                       2,    [('OBJECT_TAG', 1)],                           0x0065, (0,),                                        'table'),  # 5f aiObjInteract
    ('DropObject',                          2,    [('OBJECT_TAG', 1)],                           0x0066, (0,),                                        'table'),  # 60 aiDestroyObject
    ('ChrDropAllConcealedItems',            2,    [('CHR_NUM', 1)],                              0x0067, (0,),                                        'table'),  # 61 ai0067
    ('ChrDropAllHeldItems',                 2,    [('CHR_NUM', 1)],                              0x0068, (0,),                                        'table'),  # 62 aiChrDropItems
    ('BondCollectObject',                   2,    [('OBJECT_TAG', 1)],                           0x0069, (0,),                                        'table'),  # 63 aiChrDropWeapon
    ('ChrEquipObject',                      3,    [('OBJECT_TAG', 1), ('CHR_NUM', 1)],           0x006a, (0, 1),                                      'table'),  # 64 aiGiveObjectToChr
    ('MoveObject',                          4,    [('OBJECT_TAG', 1), ('PAD', 2)],               0x006b, (0, 1),                                      'table'),  # 65 aiObjectMoveToPad
    ('DoorOpen',                            2,    [('OBJECT_TAG', 1)],                           0x006c, (0,),                                        'both'),  # 66 aiOpenDoor
    ('DoorClose',                           2,    [('OBJECT_TAG', 1)],                           0x006d, (0,),                                        'both'),  # 67 aiCloseDoor
    ('IFDoorStateEqual',                    4,    [('OBJECT_TAG', 1), ('DOOR_STATE', 1), ('GOTOLABEL', 1)], 0x006e, (0, 1, 2),                                   'both'),  # 68 aiIfDoorState
    ('IFDoorHasBeenOpenedBefore',           3,    [('OBJECT_TAG', 1), ('GOTOLABEL', 1)],         0x006f, (0, 1),                                      'table'),  # 69 aiIfObjectIsDoor
    ('DoorSetLock',                         3,    [('OBJECT_TAG', 1), ('LOCK_FLAG', 1)],         0x0070, (0, 1),                                      'table'),  # 6a aiLockDoor
    ('DoorUnsetLock',                       3,    [('OBJECT_TAG', 1), ('LOCK_FLAG', 1)],         0x0071, (0, 1),                                      'table'),  # 6b aiUnlockDoor
    ('IFDoorLockEqual',                     4,    [('OBJECT_TAG', 1), ('LOCK_FLAG', 1), ('GOTOLABEL', 1)], 0x0072, (0, 1, 2),                                   'table'),  # 6c aiIfDoorLocked
    ('IFObjectiveNumComplete',              3,    [('OBJ_NUM', 1), ('GOTOLABEL', 1)],            0x0073, (0, 1),                                      'both'),  # 6d aiIfObjectiveComplete
    ('TRYUnknown6e',                        3,    [('UNKNOWN_FLAG', 1), ('GOTOLABEL', 1)],       0x0074, (0, 1),                                      'table'),  # 6e aiIfObjectiveFailed
    ('TRYUnknown6f',                        3,    [('UNKNOWN_FLAG', 1), ('GOTOLABEL', 1)],       0x0076, (0, 1),                                      'table'),  # 6f aiSetPadPresetToTargetQuadrant
    ('IFGameDifficultyLessThan',            3,    [('DIFICULTY_ID', 1), ('GOTOLABEL', 1)],       0x0077, (0, 1),                                      'both'),  # 70 aiIfDifficultyLessThan
    ('IFGameDifficultyGreaterThan',         3,    [('DIFICULTY_ID', 1), ('GOTOLABEL', 1)],       0x0078, (0, 1),                                      'both'),  # 71 aiIfDifficultyGreaterThan
    ('IFMissionTimeLessThan',               4,    [('SECONDS', 2), ('GOTOLABEL', 1)],            0x0079, (0, 1),                                      'hand'),  # 72 aiIfStageTimerLessThan
    ('IFMissionTimeGreaterThan',            4,    [('SECONDS', 2), ('GOTOLABEL', 1)],            0x007a, (0, 1),                                      'hand'),  # 73 aiIfStageTimerGreaterThan
    ('IFSystemPowerTimeLessThan',           4,    [('MINUTES', 2), ('GOTOLABEL', 1)],            0x0079, (0, 1),                                      'table'),  # 74 aiIfStageTimerLessThan
    ('IFSystemPowerTimeGreaterThan',        4,    [('MINUTES', 2), ('GOTOLABEL', 1)],            0x007a, (0, 1),                                      'table'),  # 75 aiIfStageTimerGreaterThan
    ('IFLevelIdLessThan',                   3,    [('LEVEL_ID', 1), ('GOTOLABEL', 1)],           0x007b, (0, 1),                                      'table'),  # 76 aiIfStageIdLessThan
    ('IFLevelIdGreaterThan',                3,    [('LEVEL_ID', 1), ('GOTOLABEL', 1)],           0x007c, (0, 1),                                      'table'),  # 77 aiIfStageIdGreaterThan
    ('IFMyNumArghsLessThan',                3,    [('HIT_NUM', 1), ('GOTOLABEL', 1)],            0x007d, (0, 1),                                      'table'),  # 78 aiIfNumArghsLessThan
    ('IFMyNumArghsGreaterThan',             3,    [('HIT_NUM', 1), ('GOTOLABEL', 1)],            0x007e, (0, 1),                                      'both'),  # 79 aiIfNumArghsGreaterThan
    ('IFMyNumCloseArghsLessThan',           3,    [('MISSED_NUM', 1), ('GOTOLABEL', 1)],         0x007f, (0, 1),                                      'table'),  # 7a aiIfNumCloseArghsLessThan
    ('IFMyNumCloseArghsGreaterThan',        3,    [('MISSED_NUM', 1), ('GOTOLABEL', 1)],         0x0080, (0, 1),                                      'table'),  # 7b aiIfNumCloseArghsGreaterThan
    ('IFChrHealthLessThan',                 4,    [('CHR_NUM', 1), ('HEALTH', 1), ('GOTOLABEL', 1)], 0x0081, (0, 1, 2),                                   'table'),  # 7c aiIfChrHealthGreaterThan
    ('IFChrHealthGreaterThan',              4,    [('CHR_NUM', 1), ('HEALTH', 1), ('GOTOLABEL', 1)], 0x0082, (0, 1, 2),                                   'table'),  # 7d aiIfChrHealthLessThan
    ('IFChrWasDamagedSinceLastCheck',       3,    [('CHR_NUM', 1), ('GOTOLABEL', 1)],            0x0083, (0, 1),                                      'hand'),  # 7e aiIfInjured
    ('IFBondHealthLessThan',                3,    [('HEALTH', 1), ('GOTOLABEL', 1)],             0x0082, (('=', 242, 1), 0, 1),                       'hand'),  # 7f aiIfChrHealthLessThan
    ('IFBondHealthGreaterThan',             3,    [('HEALTH', 1), ('GOTOLABEL', 1)],             0x0081, (('=', 242, 1), 0, 1),                       'hand'),  # 80 aiIfChrHealthGreaterThan
    ('SetMyMorale',                         2,    [('CHRBYTE', 1)],                              0x0084, (0,),                                        'table'),  # 81 aiSetMorale
    ('AddToMyMorale',                       2,    [('CHRBYTE', 1)],                              0x0085, (0,),                                        'table'),  # 82 aiAddMorale
    ('SubtractFromMyMorale',                2,    [('CHRBYTE', 1)],                              0x0087, (0,),                                        'table'),  # 83 aiSubtractMorale
    ('IFMyMoraleLessThan',                  3,    [('CHRBYTE', 1), ('GOTOLABEL', 1)],            0x0088, (0, 1),                                      'table'),  # 84 aiIfMoraleLessThan
    ('IFMyMoraleLessThanRandom',            2,    [('GOTOLABEL', 1)],                            0x0089, (0,),                                        'table'),  # 85 aiIfMoraleLessThanRandom
    ('SetMyAlertness',                      2,    [('CHRBYTE', 1)],                              0x008a, (0,),                                        'table'),  # 86 aiSetAlertness
    ('AddToMyAlertness',                    2,    [('CHRBYTE', 1)],                              0x008b, (0,),                                        'table'),  # 87 aiAddAlertness
    ('SubtractFromMyAlertness',             2,    [('CHRBYTE', 1)],                              0x008d, (0,),                                        'table'),  # 88 aiSubtractAlertness
    ('IFMyAlertnessLessThan',               3,    [('CHRBYTE', 1), ('GOTOLABEL', 1)],            0x008f, (0, ('=', 253, 1), 1),                       'hand'),  # 89 aiIfChrAlertnessLessThan
    ('IFMyAlertnessLessThanRandom',         2,    [('GOTOLABEL', 1)],                            0x0090, (0,),                                        'table'),  # 8a aiIfAlertnessLessThanRandom
    ('SetMyHearingScale',                   3,    [('HEARING_SCALE', 2)],                        0x0092, (0,),                                        'table'),  # 8b aiSetHearDistance
    ('SetMyVisionRange',                    2,    [('VISION_RANGE', 1)],                         0x0093, (0,),                                        'table'),  # 8c aiSetViewDistance
    ('SetMyGrenadeProbability',             2,    [('GRENADE_PROB', 1)],                         0x0094, (0,),                                        'both'),  # 8d aiSetGrenadeProbability
    ('SetMyChrNum',                         2,    [('CHR_NUM', 1)],                              0x0095, (0,),                                        'table'),  # 8e aiSetChrNum
    ('SetMyHealthTotal',                    3,    [('HEALTH', 2)],                               0x0097, (0,),                                        'table'),  # 8f aiAddHealth
    ('SetMyArmour',                         3,    [('AMOUNT', 2)],                               None,   (),                                          'table'),  # 90 -
    ('SetMySpeedRating',                    2,    [('SPEED_RATING', 1)],                         0x0098, (0,),                                        'both'),  # 91 aiSetReactionSpeed
    ('SetMyArghRating',                     2,    [('ARGH_RATING', 1)],                          0x0099, (0,),                                        'table'),  # 92 aiSetRecoverySpeed
    ('SetMyAccuracyRating',                 2,    [('ACCURACY_RATING', 1)],                      0x009a, (0,),                                        'both'),  # 93 aiSetAccuracy
    ('SetMyFlags2',                         2,    [('BITS', 1)],                                 None,   (),                                          'hand'),  # 94 -
    ('UnsetMyFlags2',                       2,    [('BITS', 1)],                                 None,   (),                                          'hand'),  # 95 -
    ('IFMyFlags2Has',                       3,    [('BITS', 1), ('GOTOLABEL', 1)],               None,   (),                                          'hand'),  # 96 -
    ('SetChrBitfield',                      3,    [('CHR_NUM', 1), ('BITS', 1)],                 None,   (),                                          'hand'),  # 97 -
    ('UnsetChrBitfield',                    3,    [('CHR_NUM', 1), ('BITS', 1)],                 None,   (),                                          'hand'),  # 98 -
    ('IFChrBitfieldHas',                    4,    [('CHR_NUM', 1), ('BITS', 1), ('GOTOLABEL', 1)], None,   (),                                          'hand'),  # 99 -
    ('SetObjectiveBitfield',                5,    [('BITFIELD', 4)],                             0x00a1, (0,),                                        'both'),  # 9a aiSetStageFlag
    ('UnsetObjectiveBitfield',              5,    [('BITFIELD', 4)],                             0x00a2, (0,),                                        'both'),  # 9b aiUnsetStageFlag
    ('IFObjectiveBitfieldHas',              6,    [('BITS', 4), ('GOTOLABEL', 1)],               0x00a3, ((0, 4), ('=', 1, 1), 1),                    'hand'),  # 9c aiIfStageFlagEq
    ('SetMychrflags',                       5,    [('CHRFLAGS', 4)],                             0x00a4, (0,),                                        'both'),  # 9d aiSetChrflag
    ('UnsetMychrflags',                     5,    [('CHRFLAGS', 4)],                             0x00a5, (0,),                                        'both'),  # 9e aiUnsetChrflag
    ('IFMychrflagsHas',                     6,    [('CHRFLAGS', 4), ('GOTOLABEL', 1)],           0x00a6, (0, 1),                                      'table'),  # 9f aiIfHasChrflag
    ('SetChrchrflags',                      6,    [('CHR_NUM', 1), ('CHRFLAGS', 4)],             0x00a7, (0, 1),                                      'both'),  # a0 aiChrSetChrflag
    ('UnsetChrchrflags',                    6,    [('CHR_NUM', 1), ('CHRFLAGS', 4)],             0x00a8, (0, 1),                                      'both'),  # a1 aiChrUnsetChrflag
    ('IFChrchrflagsHas',                    7,    [('CHR_NUM', 1), ('CHRFLAGS', 4), ('GOTOLABEL', 1)], 0x00a9, (0, 1, 2),                                   'table'),  # a2 aiIfChrHasChrflag
    ('SetObjectFlags',                      6,    [('OBJECT_TAG', 1), ('BITFIELD', 4)],          0x00aa, (0, 1),                                      'both'),  # a3 aiSetObjFlag
    ('UnsetObjectFlags',                    6,    [('OBJECT_TAG', 1), ('BITFIELD', 4)],          0x00ab, (0, 1),                                      'both'),  # a4 aiUnsetObjFlag
    ('IFObjectFlagsHas',                    7,    [('OBJECT_TAG', 1), ('BITS', 4), ('GOTOLABEL', 1)], 0x00ac, (0, 1, 2),                                   'table'),  # a5 aiIfObjHasFlag
    ('SetObjectFlags2',                     6,    [('OBJECT_TAG', 1), ('BITS', 4)],              0x00ad, (0, 1),                                      'table'),  # a6 aiSetObjFlag2
    ('UnsetObjectFlags2',                   6,    [('OBJECT_TAG', 1), ('BITS', 4)],              0x00ae, (0, 1),                                      'table'),  # a7 aiUnsetObjFlag2
    ('IFObjectFlags2Has',                   7,    [('OBJECT_TAG', 1), ('BITFIELD', 4), ('GOTOLABEL', 1)], 0x00af, (0, 1, 2),                                   'table'),  # a8 aiIfObjHasFlag2
    ('SetMyChrPreset',                      2,    [('CHR_PRESET', 1)],                           0x00b0, (0,),                                        'table'),  # a9 aiSetChrPreset
    ('SetChrChrPreset',                     3,    [('CHR_NUM', 1), ('CHR_PRESET', 1)],           0x00b1, (0, 1),                                      'table'),  # aa aiSetChrTarget
    ('SetMyPadPreset',                      3,    [('PAD_PRESET', 2)],                           0x00b2, (0,),                                        'both'),  # ab aiSetPadPreset
    ('SetChrPadPreset',                     4,    [('CHR_NUM', 1), ('PAD_PRESET', 2)],           0x00b3, (0, 1),                                      'table'),  # ac aiChrSetPadPreset
    ('PRINT',                               None, [],                                            None,   (),                                          'hand'),  # ad -
    ('MyTimerStart',                        1,    [],                                            0x00b6, (),                                          'both'),  # ae aiRestartTimer
    ('MyTimerReset',                        1,    [],                                            0x00b7, (),                                          'table'),  # af aiResetTimer
    ('MyTimerPause',                        1,    [],                                            0x00b8, (),                                          'table'),  # b0 aiPauseTimer
    ('MyTimerResume',                       1,    [],                                            0x00b9, (),                                          'table'),  # b1 aiResumeTimer
    ('IFMyTimerIsNotRunning',               2,    [('GOTOLABEL', 1)],                            0x00ba, (0,),                                        'table'),  # b2 aiIfTimerStopped
    ('IFMyTimerLessThanTicks',              5,    [('TICKS', 3), ('GOTOLABEL', 1)],              0x00bc, (0, 1),                                      'table'),  # b3 aiIfTimerLessThan
    ('IFMyTimerGreaterThanTicks',           5,    [('TICKS', 3), ('GOTOLABEL', 1)],              0x00bd, (0, 1),                                      'both'),  # b4 aiIfTimerGreaterThan
    ('HudCountdownShow',                    1,    [],                                            0x00be, (),                                          'both'),  # b5 aiShowCountdownTimer
    ('HudCountdownHide',                    1,    [],                                            0x00bf, (),                                          'table'),  # b6 aiHideCountdownTimer
    ('HudCountdownSet',                     3,    [('SECONDS', 2)],                              0x00c0, (0,),                                        'both'),  # b7 aiSetCountdownTimerValue
    ('HudCountdownStop',                    1,    [],                                            0x00c1, (),                                          'table'),  # b8 aiStopCountdownTimer
    ('HudCountdownStart',                   1,    [],                                            0x00c2, (),                                          'both'),  # b9 aiStartCountdownTimer
    ('IFHudCountdownIsNotRunning',          2,    [('GOTOLABEL', 1)],                            0x00c3, (0,),                                        'table'),  # ba aiIfCountdownTimerStopped
    ('IFHudCountdownLessThan',              4,    [('SECONDS', 2), ('GOTOLABEL', 1)],            0x00c4, (0, 1),                                      'both'),  # bb aiIfCountdownTimerLessThan
    ('IFHudCountdownGreaterThan',           4,    [('SECONDS', 2), ('GOTOLABEL', 1)],            0x00c5, (0, 1),                                      'table'),  # bc aiIfCountdownTimerGreaterThan
    ('TRYSpawningChrAtPad',                 12,   [('BODY_NUM', 1), ('HEAD_NUM', 1), ('PAD', 2), ('AI_LIST_ID', 2), ('BITFIELD', 4), ('GOTOLABEL', 1)], 0x00c6, (0, 1, 2, 3, 4, 5),                          'both'),  # bd aiSpawnChrAtPad
    ('TRYSpawningChrNextToChr',             11,   [('BODY_NUM', 1), ('HEAD_NUM', 1), ('CHR_NUM_TARGET', 1), ('AI_LIST_ID', 2), ('BITFIELD', 4), ('GOTOLABEL', 1)], 0x00c7, (0, 1, 2, 3, 4, 5),                          'table'),  # be aiSpawnChrAtChr
    ('TRYGiveMeItem',                       9,    [('PROP_NUM', 2), ('ITEM_NUM', 1), ('PROPFLAG', 4), ('GOTOLABEL', 1)], 0x00c8, (0, 1, 2, 3),                                'both'),  # bf aiTryEquipWeapon
    ('TRYGiveMeHat',                        8,    [('PROP_NUM', 2), ('PROP_BITFIELD', 4), ('GOTOLABEL', 1)], None,   (),                                          'hand'),  # c0 -
    ('TRYCloningChr',                       5,    [('CHR_NUM', 1), ('AI_LIST_ID', 2), ('GOTOLABEL', 1)], None,   (),                                          'hand'),  # c1 -
    ('TextPrintBottom',                     3,    [('TEXT_SLOT', 2)],                            0x00cb, (('=', CHR_BOND, 1), 0),                     'hand'),  # c2 aiShowHudmsg
    ('TextPrintTop',                        3,    [('TEXT_SLOT', 2)],                            0x00cb, (('=', CHR_BOND, 1), 0),                     'hand'),  # c3 aiShowHudmsg
    ('SfxPlay',                             4,    [('SOUND_NUM', 2), ('CHANNEL_NUM', 1)],        0x00ce, (0, 1),                                      'both'),  # c4 aiPlaySound
    ('SfxEmitFromObject',                   5,    [('CHANNEL_NUM', 1), ('OBJECT_TAG', 1), ('VOL_DECAY_TIME60', 2)], 0x00cf, (0, 1, 2),                                   'both'),  # c5 aiSetObjectSoundPlaying
    ('SfxEmitFromPad',                      6,    [('CHANNEL_NUM', 1), ('PAD', 2), ('VOL_DECAY_TIME60', 2)], 0x00d0, (0, 1, 2),                                   'table'),  # c6 aiPlayRepeatingSoundFromPad
    ('SfxSetChannelVolume',                 6,    [('CHANNEL_NUM', 1), ('TARGET_VOLUME', 2), ('TRANSITION_TIME60', 2)], 0x00d1, (0, 1, 2),                                   'table'),  # c7 aiSetObjectSoundVolume
    ('SfxFadeChannelVolume',                6,    [('CHANNEL_NUM', 1), ('TARGET_VOLUME', 2), ('TRANSITION_TIME60', 2)], 0x00d2, (0, 1, 2),                                   'table'),  # c8 aiSetObjectSoundVolumeByDistance
    ('SfxStopChannel',                      2,    [('CHANNEL_NUM', 1)],                          0x00d3, (0,),                                        'table'),  # c9 aiAudioMuteChannel
    ('IFSfxChannelVolumeLessThan',          5,    [('CHANNEL_NUM', 1), ('VOLUME', 2), ('GOTOLABEL', 1)], 0x00d4, (0, 1, 2),                                   'table'),  # ca aiIfObjectSoundVolumeLessThan
    ('VehicleStartPath',                    2,    [('PATH_NUM', 1)],                             0x00d5, (0,),                                        'table'),  # cb aiHovercarBeginPath
    ('VehicleSpeed',                        5,    [('TOP_SPEED', 2), ('ACCELERATION_TIME60', 2)], 0x00d6, (0, 1),                                      'table'),  # cc aiSetVehicleSpeed
    ('AircraftRotorSpeed',                  5,    [('ROTOR_SPEED', 2), ('ACCELERATION_TIME60', 2)], 0x00d7, (0, 1),                                      'table'),  # cd aiSetRotorSpeed
    ('IFCameraIsInIntro',                   2,    [('GOTOLABEL', 1)],                            0x00d8, (0,),                                        'table'),  # ce aiNoOp00d8
    ('IFCameraIsInBondSwirl',               2,    [('GOTOLABEL', 1)],                            0x00d9, (0,),                                        'table'),  # cf aiNoOp00d9
    ('TvChangeScreenBank',                  4,    [('OBJECT_TAG', 1), ('SCREEN_INDEX', 1), ('SCREEN_BANK', 1)], 0x00da, (0, 1, 2),                                   'both'),  # d0 aiSetObjImage
    ('IFBondInTank',                        2,    [('GOTOLABEL', 1)],                            0x00db, (0,),                                        'table'),  # d1 aiNoOp00db
    ('EndLevel',                            1,    [],                                            0x00dc, (),                                          'both'),  # d2 aiEndLevel
    ('CameraReturnToBond',                  1,    [],                                            None,   (),                                          'hand'),  # d3 -
    ('CameraLookAtBondFromPad',             3,    [('PAD', 2)],                                  None,   (),                                          'hand'),  # d4 -
    ('CameraSwitch',                        6,    [('OBJECT_TAG', 1), ('LOOK_AT_BOND_FLAG', 2), ('UNUSED_FLAG', 2)], 0x00df, (0, 1, 2),                                   'both'),  # d5 ai00df
    ('IFBondYPosLessThan',                  4,    [('Y_POS', 2), ('GOTOLABEL', 1)],              None,   (),                                          'table'),  # d6 -
    ('BondDisableControl',                  2,    [('BITFIELD', 1)],                             0x00e0, (0, ('=', 0, 1)),                            'hand'),  # d7 aiRevokeControl
    ('BondEnableControl',                   1,    [],                                            None,   (),                                          'hand'),  # d8 -
    ('TRYTeleportingChrToPad',              5,    [('CHR_NUM', 1), ('PAD', 2), ('GOTOLABEL', 1)], None,   (),                                          'hand'),  # d9 -
    ('ScreenFadeToBlack',                   1,    [],                                            None,   (),                                          'hand'),  # da -
    ('ScreenFadeFromBlack',                 1,    [],                                            None,   (),                                          'hand'),  # db -
    ('IFScreenFadeCompleted',               2,    [('GOTOLABEL', 1)],                            0x01cc, (0,),                                        'hand'),  # dc aiIfFadeComplete
    ('HideAllChrs',                         1,    [],                                            0x01d5, (('=', 0, 1),),                              'hand'),  # dd aiShowCutsceneChrs
    ('ShowAllChrs',                         1,    [],                                            0x01d5, (('=', 1, 1),),                              'hand'),  # de aiShowCutsceneChrs
    ('DoorOpenInstant',                     2,    [('OBJECT_TAG', 1)],                           0x00e8, (0,),                                        'hand'),  # df aiSetDoorOpen
    ('ChrRemoveItemInHand',                 3,    [('CHR_NUM', 1), ('HAND_INDEX', 1)],           None,   (),                                          'hand'),  # e0 -
    ('IfNumberOfActivePlayersLessThan',     3,    [('NUMBER', 1), ('GOTOLABEL', 1)],             0x00ea, (0, 1),                                      'hand'),  # e1 aiIfNumPlayersLessThan
    ('IFBondItemTotalAmmoLessThan',         4,    [('ITEM_NUM', 1), ('AMMO_TOTAL', 1), ('GOTOLABEL', 1)], None,   (),                                          'hand'),  # e2 -
    ('BondEquipItem',                       2,    [('ITEM_NUM', 1)],                             None,   (),                                          'hand'),  # e3 -
    ('BondEquipItemCinema',                 2,    [('ITEM_NUM', 1)],                             None,   (),                                          'hand'),  # e4 -
    ('BondSetLockedVelocity',               3,    [('X_SPEED60', 1), ('Z_SPEED60', 1)],          None,   (),                                          'hand'),  # e5 -
    ('IFObjectInRoomWithPad',               5,    [('OBJECT_TAG', 1), ('PAD', 2), ('GOTOLABEL', 1)], None,   (),                                          'hand'),  # e6 -
    ('IFImFiringAndLockedForward',          2,    [('GOTOLABEL', 1)],                            None,   (),                                          'hand'),  # e7 -
    ('IFImFiring',                          2,    [('GOTOLABEL', 1)],                            None,   (),                                          'hand'),  # e8 -
    ('SwitchSky',                           1,    [],                                            0x00f2, (),                                          'hand'),  # e9 aiSwitchToAltSky
    ('TriggerFadeAndExitLevelOnButtonPress', 1,    [],                                            None,   (),                                          'hand'),  # ea -
    ('IFBondIsDead',                        2,    [('GOTOLABEL', 1)],                            None,   (),                                          'hand'),  # eb -
    ('BondDisableDamageAndPickups',         1,    [],                                            None,   (),                                          'hand'),  # ec -
    ('BondHideWeapons',                     1,    [],                                            None,   (),                                          'hand'),  # ed -
    ('CameraOrbitPad',                      13,   [('LAT_DISTANCE', 2), ('VERT_DISTANCE', 2), ('ORBIT_SPEED60', 2), ('PAD', 2), ('Y_POS_OFFSET', 2), ('INITIAL_ROTATION', 2)], None,   (),                                          'hand'),  # ee -
    ('CreditsRoll',                         1,    [],                                            None,   (),                                          'hand'),  # ef -
    ('IFCreditsHasCompleted',               2,    [('GOTOLABEL', 1)],                            None,   (),                                          'hand'),  # f0 -
    ('IFObjectiveAllCompleted',             2,    [('GOTOLABEL', 1)],                            0x00f7, (0,),                                        'hand'),  # f1 aiIfAllObjectivesComplete
    ('IFFolderActorIsEqual',                3,    [('BOND_ACTOR_INDEX', 1), ('GOTOLABEL', 1)],   None,   (),                                          'hand'),  # f2 -
    ('IFBondDamageAndPickupsDisabled',      2,    [('GOTOLABEL', 1)],                            None,   (),                                          'hand'),  # f3 -
    ('MusicPlaySlot',                       4,    [('MUSIC_SLOT', 1), ('SECONDS_STOPPED_DURATION', 1), ('SECONDS_TOTAL_DURATION', 1)], None,   (),                                          'hand'),  # f4 -
    ('MusicStopSlot',                       2,    [('MUSIC_SLOT', 1)],                           None,   (),                                          'hand'),  # f5 -
    ('TriggerExplosionsAroundBond',         1,    [],                                            0x00fb, (('=', 242, 1),),                            'hand'),  # f6 aiChrExplosions
    ('IFKilledCiviliansGreaterThan',        3,    [('CIVILIANS_KILLED', 1), ('GOTOLABEL', 1)],   None,   (),                                          'hand'),  # f7 -
    ('IFChrWasShotSinceLastCheck',          3,    [('CHR_NUM', 1), ('GOTOLABEL', 1)],            0x0083, (0, 1),                                      'hand'),  # f8 aiIfInjured
    ('BondKilledInAction',                  1,    [],                                            0x00fe, (),                                          'hand'),  # f9 aiKillBond
    ('RaiseArms',                           1,    [],                                            None,   (),                                          'hand'),  # fa -
    ('GasLeakAndFadeFog',                   1,    [],                                            None,   (),                                          'hand'),  # fb -
    ('ObjectRocketLaunch',                  2,    [('OBJECT_TAG', 1)],                           None,   (),                                          'hand'),  # fc -
]

