"""GoldenEye's own hit, death and explosion tables, as port/include/gechranimtable.h.

A GoldenEye guard picks what to play when shot out of `g_HitReactionTable`
(the decompilation's src/game/chr.c): a death list and a flinch list for each
part of the body, the parts numbered as Perfect Dark's HITPART_*. A blast picks
out of `D_8002E648` by the side it came from (`explosion_animation_table`), and
a guard shot dead against a wall out of `death_stagger`.

Perfect Dark's tables (chraction.c's g_DeathAnimsHuman*, g_InjuryAnimsHuman*,
g_YeetAnimsHuman) grew out of these and then parted from them: rows added,
rows dropped, and some of GoldenEye's animations re-made under the same number.
GE Plus plays GoldenEye's, so it takes GoldenEye's tables (gechranims.c).

Each row names its animation by GoldenEye's own id (geanimtable.py's order),
which the port turns into the row the conversion appended it at.

    python3 tools/geconvert/gechranims.py [path/to/007] > port/include/gechranimtable.h
"""
import os
import re
import sys

import geanimtable

GE = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '../../../007')

IDS = {name: i for i, (name, _) in enumerate(geanimtable.TABLE)}

PARTS = ['left_foot', 'left_leg', 'left_thigh', 'right_foot', 'right_leg', 'right_thigh', 'pelvis', 'head',
         'left_hand', 'left_arm', 'left_shoulder', 'right_hand', 'right_arm', 'right_shoulder', 'chest', 'gun']

# Perfect Dark's number for each of GoldenEye's HIT_* parts, in PARTS order
HITPARTS = ['HITPART_LFOOT', 'HITPART_LSHIN', 'HITPART_LTHIGH', 'HITPART_RFOOT', 'HITPART_RSHIN',
            'HITPART_RTHIGH', 'HITPART_PELVIS', 'HITPART_HEAD', 'HITPART_LHAND', 'HITPART_LFOREARM',
            'HITPART_LBICEP', 'HITPART_RHAND', 'HITPART_RFOREARM', 'HITPART_RBICEP', 'HITPART_TORSO',
            'HITPART_GUN']


def num(s):
    s = s.strip().rstrip('f')
    return float(s) if '.' in s else int(s, 0)


def arrays(src, kind):
    """{name: [row fields]} for every `struct kind name[] = {...};` in src."""
    out = {}
    for m in re.finditer(r'struct %s (\w+)\[\] = \{(.*?)\n\};' % kind, src, re.S):
        rows = []
        for r in re.finditer(r'\{\s*PTR_ANIM_(\w+)\s*,([^}]*)\}', m.group(2)):
            rows.append([IDS[r.group(1)]] + [num(x) for x in r.group(2).split(',')])
        out[m.group(1)] = rows
    return out


def f(x):
    s = '%g' % x
    return (s if '.' in s else s + '.0') + 'f'


def main():
    src = open(os.path.join(GE, 'src/game/chr.c')).read()
    struck = arrays(src, 'StruckAnim')
    blasts = arrays(src, 'explosion_death_animation')['D_8002E648']

    print('/**')
    print(' * GoldenEye\'s own hit, death and explosion tables (its src/game/chr.c), with')
    print(' * each animation as GoldenEye\'s own id. Generated by')
    print(' * tools/geconvert/gechranims.py - do not edit; gechranims.c reads it.')
    print(' */')
    print('#ifndef GECHRANIMTABLE_H')
    print('#define GECHRANIMTABLE_H')
    print()
    print('// geid, flip, end frame, speed, knockback, thud frames')
    print('struct gestruck { u8 geid; u8 flip; f32 endframe; f32 speed; u8 knockback; f32 thud1; f32 thud2; };')
    print()

    def table(name, rows):
        print('static const struct gestruck g_Ge_%s[] = {' % name)
        for r in rows:
            geid, flip, end, speed, knock, thud1, thud2 = r
            print('\t{ %3d, %d, %s, %s, %d, %s, %s },  // %s' % (geid, flip, f(end), f(speed), knock,
                                                              f(thud1), f(thud2), geanimtable.TABLE[geid][0]))
        print('};')
        print()

    for p in PARTS:
        table('death_' + p, struck['death_' + p])
        table('flinch_' + p, struck['flinch_' + p])
    table('death_stagger', struck['death_stagger'])

    print('#define GE_STRUCK(a) a, (s32)(sizeof(a) / sizeof(a[0]))')
    print()
    print('static const struct { s32 hitpart; const struct gestruck *death; s32 numdeath; const struct gestruck *flinch; s32 numflinch; } g_GeHitReactions[] = {')
    for p, hp in zip(PARTS, HITPARTS):
        print('\t{ %s, GE_STRUCK(g_Ge_death_%s), GE_STRUCK(g_Ge_flinch_%s) },' % (hp, p, p))
    print('};')
    print()

    # D_8002E648: geid, flip, speed, start frame, (a frame nothing reads), thud frame, end frame
    print('// geid, flip, speed, start frame, thud frame, end frame')
    print('struct geblast { u8 geid; u8 flip; f32 speed; f32 startframe; f32 thudframe; f32 endframe; };')
    print()
    print('static const struct geblast g_GeBlasts[] = {')
    for r in blasts:
        geid, flip, speed, start, _unused, thud, end = r
        print('\t{ %3d, %d, %s, %s, %s, %s },  // %s' % (geid, flip, f(speed), f(start), f(thud), f(end),
                                                    geanimtable.TABLE[geid][0]))
    print('};')
    print()

    # explosion_animation_table: the eight sides a blast comes from, each a
    # list of rows of g_GeBlasts and how many of them to pick among
    lists = {m.group(1): [int(x, 0) for x in m.group(2).split(',')]
             for m in re.finditer(r's8 (expl_\w+)\[\] = \{([^}]*)\};', src)}
    order = re.search(r'explosion_animation_table\[[^\]]*\] = \{(.*?)\n\};', src, re.S).group(1)
    sides = re.findall(r'\{(expl_\w+),\s*(\d+)\}', order)
    print('static const struct { s8 rows[8]; s32 count; } g_GeBlastSides[8] = {')
    for name, count in sides:
        print('\t{ { %s }, %s },  // %s' % (', '.join(str(x) for x in lists[name]), count, name))
    print('};')
    print()
    print('#endif')


main()
