#!/usr/bin/env python3
"""Write port/src/geimagesurfaces.h from GoldenEye's decompiled image table.

GoldenEye keeps what a shot does to each of its images in the first byte of
the image's g_Textures entry (image.h, struct image_entry): the sound a bullet
makes in the high nibble (hitSound) and the mark it leaves in the low one
(hitTexture), as its HIT_* numbers - which are Perfect Dark's SURFACETYPE_*
numbers one for one, from HIT_DEFAULT 0 to HIT_GLASS_XLU 12. The decomp
spells the table out in assets/images.def, one IMAGE() row an image in image
order; checked byte for byte against the US ROM's own table (0x80049300 in the
inflated data segment, 2698 images and the 0xffff end row).

A converted level draws GoldenEye's images under Perfect Dark's numbers, and
Perfect Dark reads a hit's surface out of its own table by that number
(getexsurface.c), so a GoldenEye door of metal sounded of glass in its middle
and left mud's smudge for a hole.
"""
import os, re, sys

DECOMP = next(d for d in (os.path.expanduser("~/claude-007/007/assets"),
                          os.path.expanduser("~/perfect-dark/007/assets")) if os.path.isdir(d))
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "port", "src", "geimagesurfaces.h")

HIT = ["HIT_DEFAULT", "HIT_STONE", "HIT_WOOD", "HIT_METAL", "HIT_GLASS", "HIT_WATER", "HIT_SNOW",
       "HIT_DIRT", "HIT_MUD", "HIT_TILE", "HIT_METALOBJ", "HIT_CHR", "HIT_GLASS_XLU"]


def main():
    rows = []
    for line in open(os.path.join(DECOMP, "images.def")):
        m = re.match(r"\s*IMAGE\(\s*(\w+)\s*,\s*\w+\s*,\s*(\w+)\s*,\s*(\w+)\s*,", line)
        if m:
            rows.append((m.group(1), HIT.index(m.group(2)), HIT.index(m.group(3))))

    if len(rows) != 2698:
        sys.exit("images.def has %d images, not GoldenEye's 2698" % len(rows))

    out = []
    out.append("// Generated by tools/geconvert/gen_texsurface.py from GoldenEye's decomp")
    out.append("// (assets/images.def): each of GoldenEye's images, in image order, as the")
    out.append("// first byte of its g_Textures entry - the sound a shot makes (high nibble)")
    out.append("// and the mark it leaves (low nibble), GoldenEye's HIT_* numbers, which are")
    out.append("// Perfect Dark's SURFACETYPE_* numbers. getexsurface.c.")
    out.append("#define GE_NUM_IMAGES %d" % len(rows))
    out.append("")
    out.append("static const u8 g_GeImageSurfaces[GE_NUM_IMAGES] = {")
    for i in range(0, len(rows), 16):
        out.append("\t" + " ".join("0x%02x," % ((s << 4) | h) for _, s, h in rows[i:i + 16]))
    out.append("};")
    open(OUT, "w").write("\n".join(out) + "\n")
    print("wrote %s: %d images, %d not HIT_DEFAULT" % (os.path.normpath(OUT), len(rows),
                                                      sum(1 for _, s, h in rows if s or h)))


if __name__ == "__main__":
    main()
