#!/usr/bin/env python3
"""
Compiles each language's source files (lang/<code>/, CLAUDE-notes/languages.md)
into one <code>.lang pack, and optionally a C file that embeds them all in the
binary (the updater ships a bare executable, so the built-in languages live in
it). The build runs:

    build.py --src lang --embed <build>/langpacks.c

and a translator testing a pack without rebuilding the game runs:

    build.py --src lang --only fr --out <game dir>/lang

which writes fr.lang where the game looks for dropped-in packs.

The .lang format is plain UTF-8 text the game parses without a JSON reader:

    @name<TAB>Francais
    @script<TAB>latin            latin | cjk
    @fallback<TAB>en
    pd.0200<TAB>...              a Perfect Dark text id, bank * 512 + row, hex
    port:<English><TAB>...       a port string keyed by its English
    ge.<bank>.<slot><TAB>...     GoldenEye text by GoldenEye's id
    ge:<English><TAB>...         GoldenEye text keyed by its English

with backslash, newline and tab written as \\\\, \\n and \\t in keys and values.
A string that fails a check (check.py) is left out with a warning, so the game
shows the English for it rather than crashing on a bad printf conversion.
"""

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import check  # noqa: E402


def escape(s):
    return s.replace('\\', '\\\\').replace('\n', '\\n').replace('\t', '\\t').replace('\r', '').replace('\x00', '\\0')


def compile_language(srcdir, quiet=False):
    meta, strings, p = check.read_language(srcdir)

    if not quiet:
        for w in p.warnings:
            print('langpack: warning: ' + w, file=sys.stderr)
        for e in p.errors:
            print('langpack: left out: ' + e, file=sys.stderr)

    if 'name' not in meta:
        return None

    lines = []
    lines.append('@name\t' + escape(meta['name']))
    lines.append('@script\t' + escape(meta.get('script', 'latin')))
    lines.append('@fallback\t' + escape(meta.get('fallback', 'en')))

    for key in sorted(strings):
        lines.append(escape(key) + '\t' + escape(strings[key]))

    return '\n'.join(lines) + '\n'


def languages(src, only=None):
    if not os.path.isdir(src):
        return []
    codes = []
    for code in sorted(os.listdir(src)):
        if only and code not in only:
            continue
        if os.path.exists(os.path.join(src, code, 'meta.json')):
            codes.append(code)
    return codes


def c_string(text):
    """A C string literal, split at the pack's lines so no line is enormous."""
    out = []
    data = text.encode('utf-8')
    line = []
    for b in data:
        if b == 0x5c:
            line.append('\\\\')
        elif b == 0x22:
            line.append('\\"')
        elif 0x20 <= b < 0x7f and b != 0x3f:  # '?' escaped against trigraphs
            line.append(chr(b))
        else:
            line.append('\\%03o' % b)
        if b == 0x0a:
            out.append('\t"' + ''.join(line) + '"')
            line = []
    if line:
        out.append('\t"' + ''.join(line) + '"')
    return '\n'.join(out) if out else '\t""'


def write_embed(path, packs):
    out = []
    out.append('// Generated by tools/langpack/build.py from lang/ - do not edit.')
    out.append('#include <stddef.h>')
    out.append('')
    out.append('struct langpackembedded { const char *code; const char *text; unsigned int len; };')
    out.append('')
    for i, (code, text) in enumerate(packs):
        out.append('static const char pack%d[] =' % i)
        out.append(c_string(text) + ';')
        out.append('')
    out.append('const struct langpackembedded g_LangPacksEmbedded[] = {')
    for i, (code, text) in enumerate(packs):
        out.append('\t{ "%s", pack%d, sizeof(pack%d) - 1 },' % (code, i, i))
    out.append('\t{ NULL, NULL, 0 },')
    out.append('};')
    out.append('')
    out.append('const int g_LangNumPacksEmbedded = %d;' % len(packs))

    data = '\n'.join(out) + '\n'

    # Rewritten only when it changes, so nothing recompiles for nothing, but
    # always touched, so the build's rule sees it as newer than its sources.
    try:
        with open(path, encoding='utf-8') as f:
            if f.read() == data:
                os.utime(path, None)
                return
    except OSError:
        pass

    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(data)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--src', default=os.path.join(check.ROOT, 'lang'), help='the lang/ directory')
    ap.add_argument('--only', action='append', help='a language code to build (repeatable)')
    ap.add_argument('--out', help='write <code>.lang files into this directory')
    ap.add_argument('--embed', help='write the C file that embeds the packs')
    ap.add_argument('--pack', help='build one language directory (any path) into --out')
    ap.add_argument('--quiet', action='store_true')
    args = ap.parse_args()

    packs = []

    if args.pack:
        code = os.path.basename(os.path.normpath(args.pack))
        text = compile_language(args.pack, args.quiet)
        if text is None:
            print('langpack: %s has no meta.json name' % args.pack, file=sys.stderr)
            return 1
        packs.append((code, text))
    else:
        for code in languages(args.src, args.only):
            text = compile_language(os.path.join(args.src, code), args.quiet)
            if text is not None:
                packs.append((code, text))

    if args.out:
        os.makedirs(args.out, exist_ok=True)
        for code, text in packs:
            with open(os.path.join(args.out, code + '.lang'), 'w', encoding='utf-8', newline='\n') as f:
                f.write(text)

    if args.embed:
        write_embed(args.embed, packs)

    if not args.quiet:
        print('langpack: %d language(s): %s' % (len(packs), ' '.join(c for c, _ in packs) or '-'))

    return 0


if __name__ == '__main__':
    sys.exit(main())
