#!/usr/bin/env python3
"""
Writes port/include/xblatablesdata.h: the fields of the game's tables the XBLA
release changed, with the N64 value and the release's, for xblatables.c to
flip when the release is switched on.

The values are read out of the release's image (dumpimage.sh's early read) at
the addresses tablediff.py placed the tables, field by field through the same
N64 layout tablediff.py rebuilds from the port's debug info, and compared
against the N64 build's bytes. Only these tables are taken, by request:

  g_ExplosionTypes, g_SmokeTypes, g_SparkTypes  every changed field
  g_FogEnvironments                              row 0 (Crash Site): the port's
                                                 struct does not fit the N64
                                                 size past it, so later rows'
                                                 offsets are not trusted
  g_HeadsAndBodies                               the type bits (N64 12-10,
                                                 release 12-9), rows the port has

Never edit the header by hand; run this again.

  gentables.py [--image BIN] [--elf ELF] [--port pd.x86_64] [--out HEADER]
"""

import argparse
import os
import re
import struct
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import tablediff as td  # noqa: E402

TABLES = [
    # name, release address, rows allowed (None = all)
    ('g_ExplosionTypes', 0x825cbc70, None),
    ('g_SmokeTypes', 0x825cd3e8, None),
    ('g_SparkTypes', 0x825cce58, None),
    ('g_FogEnvironments', 0x825c1288, {0}),
]
HEADS = ('g_HeadsAndBodies', 0x825f53b0)


def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument('--image', default=os.path.join(td.WORK, '.xbla-work/default.image-82000000.early.bin'))
    ap.add_argument('--elf', default=os.path.join(td.WORK, 'pd-upstream/build/ntsc-final/stage1.elf'))
    ap.add_argument('--port', default=os.path.join(td.ROOT, 'build/pd.x86_64'))
    ap.add_argument('--out', default=os.path.join(td.ROOT, 'port/include/xblatablesdata.h'))
    return ap.parse_args()


def elf_bytes_at(elf, addr, size):
    data = open(elf, 'rb').read()
    for line in subprocess.run(['readelf', '-SW', elf], capture_output=True, text=True).stdout.splitlines():
        m = re.match(r'\s*\[\s*\d+\]\s+\S+\s+PROGBITS\s+([0-9a-f]+)\s+([0-9a-f]+)\s+([0-9a-f]+)', line)
        if m:
            va, off, sz = (int(g, 16) for g in m.groups())
            if va <= addr and addr + size <= va + sz:
                return data[off + addr - va:off + addr - va + size]
    raise SystemExit('0x%08x not in a PROGBITS section of %s' % (addr, elf))


def main():
    args = parse_args()
    img = open(args.image, 'rb').read()
    tables = {t['name']: t for t in td.elf_tables(args.elf, 16)}
    names = [n for n, _, _ in TABLES] + [HEADS[0]]
    lays = td.port_layouts(args.port, names)
    files = {int(v, 16): n for n, v in re.findall(r'#define (FILE_\w+)\s+(0x[0-9a-fA-F]+)',
                                                  open(os.path.join(td.ROOT, 'src/include/files.h')).read())}

    out = ['/**',
           ' * Generated by tools/xblaxex/gentables.py from the XBLA release\'s image. Do not edit.',
           ' *',
           ' * The fields of the game\'s tables the release changed: the field, the N64',
           ' * value and the release\'s, as the raw bits of the field. See xblatables.c.',
           ' */',
           '',
           '#ifndef _IN_XBLATABLESDATA_H',
           '#define _IN_XBLATABLESDATA_H',
           '',
           'static const struct xblatabfield xblaTabFields[] = {']
    total = 0
    for name, start, rows in TABLES:
        t = tables[name]
        lay = lays.get(name)
        leaves, es = td.table_layout(t, lay)
        if not leaves:
            raise SystemExit('%s: no N64 layout from the port' % name)
        start -= td.IMAGE_BASE
        score = td.score_at(t, img, start)
        if score < 0.8:
            raise SystemExit('%s: only %.0f%% agrees at its address; is this the image tablediff.py read?' % (name, score * 100))
        b, x = t['bytes'], img[start:start + t['size']]
        out.append('\t// %s: release 0x%08x, %.1f%% of words agree' % (name, start + td.IMAGE_BASE, score * 100))
        for off, size, kind, path in leaves:
            if off + size > len(b) or kind in ('ptr', 'bits'):
                continue
            row = off // es
            if rows is not None and row not in rows:
                continue
            a = int.from_bytes(b[off:off + size], 'big')
            y = int.from_bytes(x[off:off + size], 'big')
            if a == y or (kind == 'float' and size == 4 and td.float_close(a, y, 4)):
                continue
            if kind == 'float' and size != 4:
                raise SystemExit('%s%s: a %d-byte float' % (name, path, size))
            if kind == 'float':
                note = '%g -> %g' % (td.as_float(a), td.as_float(y))
            else:
                note = '%d -> %d' % (a, y)
            out.append('\tXBLATAB(%s%s, 0x%0*x, 0x%0*x), // %s' % (name, path, size * 2, a, size * 2, y, note))
            total += 1
    out.append('};')
    out.append('')

    # The type bits: the release moved the type up a bit and widened it.
    name, start = HEADS
    lay = lays.get(name)
    count = lay['count'] if lay else 0
    if lay is None or lay['elemsize'] != 20:
        raise SystemExit('%s: expected 20-byte N64 rows' % name)
    n64 = elf_bytes_at(args.elf, tables[name]['addr'], count * 20)
    start -= td.IMAGE_BASE
    out.append('static const struct xblatabtype xblaTabTypes[] = {')
    ntypes = 0
    for i in range(count):
        w, fn = struct.unpack_from('>HH', n64, i * 20)
        xw, xfn = struct.unpack_from('>HH', img, start + i * 20)
        if fn != xfn:
            continue  # a row the release reused (0x97, the ROM's empty last row, is its Agent 4)
        a, y = (w >> 10) & 7, (xw >> 9) & 15
        if ((w >> 2) & 0xff) != ((xw >> 1) & 0xff):
            raise SystemExit('%s[0x%x]: heights disagree, the bit layout is not the one this was written for' % (name, i))
        if a != y:
            out.append('\t{ 0x%02x, %d, %d }, // %s' % (i, a, y, files.get(fn, hex(fn))))
            ntypes += 1
    out.append('};')
    out.append('')
    out.append('#endif')
    open(args.out, 'w').write('\n'.join(out) + '\n')
    print('%s: %d fields, %d types' % (args.out, total, ntypes))


if __name__ == '__main__':
    main()
