/**
 * GoldenEye's own hit, death and explosion tables (its src/game/chr.c), with
 * each animation as GoldenEye's own id. Generated by
 * tools/geconvert/gechranims.py - do not edit; gechranims.c reads it.
 */
#ifndef GECHRANIMTABLE_H
#define GECHRANIMTABLE_H

// geid, flip, end frame, speed, knockback, thud frames
struct gestruck { u8 geid; u8 flip; f32 endframe; f32 speed; u8 knockback; f32 thud1; f32 thud2; };

static const struct gestruck g_Ge_death_left_foot[] = {
	{  31, 0, -1.0f, 0.5f, 0, 27.0f, -1.0f },  // death_backward_spin_face_down_left
	{  32, 0, -1.0f, 0.5f, 0, 26.0f, -1.0f },  // death_backward_spin_face_up_left
	{  29, 1, -1.0f, 0.5f, 0, 25.0f, -1.0f },  // death_backward_spin_face_down_right
	{  30, 1, -1.0f, 0.5f, 0, 23.0f, -1.0f },  // death_backward_spin_face_up_right
};

static const struct gestruck g_Ge_flinch_left_foot[] = {
	{  20, 0, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_left_leg
	{  21, 1, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_right_leg
};

static const struct gestruck g_Ge_death_left_leg[] = {
	{  31, 0, -1.0f, 0.5f, 0, 27.0f, -1.0f },  // death_backward_spin_face_down_left
	{  32, 0, -1.0f, 0.5f, 0, 26.0f, -1.0f },  // death_backward_spin_face_up_left
	{  29, 1, -1.0f, 0.5f, 0, 25.0f, -1.0f },  // death_backward_spin_face_down_right
	{  30, 1, -1.0f, 0.5f, 0, 23.0f, -1.0f },  // death_backward_spin_face_up_right
};

static const struct gestruck g_Ge_flinch_left_leg[] = {
	{  20, 0, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_left_leg
	{  21, 1, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_right_leg
};

static const struct gestruck g_Ge_death_left_thigh[] = {
	{  31, 0, -1.0f, 0.5f, 1, 27.0f, -1.0f },  // death_backward_spin_face_down_left
	{  32, 0, -1.0f, 0.5f, 1, 26.0f, -1.0f },  // death_backward_spin_face_up_left
	{  29, 1, -1.0f, 0.5f, 1, 25.0f, -1.0f },  // death_backward_spin_face_down_right
	{  30, 1, -1.0f, 0.5f, 1, 23.0f, -1.0f },  // death_backward_spin_face_up_right
	{  57, 1, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // death_left_leg
};

static const struct gestruck g_Ge_flinch_left_thigh[] = {
	{  20, 0, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_left_leg
	{  21, 1, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_right_leg
	{  57, 1, 20.0f, 0.4f, 0, -1.0f, -1.0f },  // death_left_leg
};

static const struct gestruck g_Ge_death_right_foot[] = {
	{  29, 0, -1.0f, 0.5f, 0, 25.0f, -1.0f },  // death_backward_spin_face_down_right
	{  30, 0, -1.0f, 0.5f, 0, 23.0f, -1.0f },  // death_backward_spin_face_up_right
	{  31, 1, -1.0f, 0.5f, 0, 27.0f, -1.0f },  // death_backward_spin_face_down_left
	{  32, 1, -1.0f, 0.5f, 0, 26.0f, -1.0f },  // death_backward_spin_face_up_left
};

static const struct gestruck g_Ge_flinch_right_foot[] = {
	{  21, 0, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_right_leg
	{  20, 1, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_left_leg
};

static const struct gestruck g_Ge_death_right_leg[] = {
	{  29, 0, -1.0f, 0.5f, 0, 25.0f, -1.0f },  // death_backward_spin_face_down_right
	{  30, 0, -1.0f, 0.5f, 0, 23.0f, -1.0f },  // death_backward_spin_face_up_right
	{  31, 1, -1.0f, 0.5f, 0, 27.0f, -1.0f },  // death_backward_spin_face_down_left
	{  32, 1, -1.0f, 0.5f, 0, 26.0f, -1.0f },  // death_backward_spin_face_up_left
};

static const struct gestruck g_Ge_flinch_right_leg[] = {
	{  21, 0, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_right_leg
	{  20, 1, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_left_leg
};

static const struct gestruck g_Ge_death_right_thigh[] = {
	{  29, 0, -1.0f, 0.5f, 1, 25.0f, -1.0f },  // death_backward_spin_face_down_right
	{  30, 0, -1.0f, 0.5f, 1, 23.0f, -1.0f },  // death_backward_spin_face_up_right
	{  31, 1, -1.0f, 0.5f, 1, 27.0f, -1.0f },  // death_backward_spin_face_down_left
	{  32, 1, -1.0f, 0.5f, 1, 26.0f, -1.0f },  // death_backward_spin_face_up_left
	{  57, 0, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // death_left_leg
};

static const struct gestruck g_Ge_flinch_right_thigh[] = {
	{  21, 0, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_right_leg
	{  20, 1, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_left_leg
	{  57, 0, 20.0f, 0.4f, 0, -1.0f, -1.0f },  // death_left_leg
};

static const struct gestruck g_Ge_death_pelvis[] = {
	{  26, 0, -1.0f, 0.5f, 0, 55.0f, 39.0f },  // death_forward_face_down
	{  26, 1, -1.0f, 0.5f, 0, 55.0f, 39.0f },  // death_forward_face_down
	{  27, 0, -1.0f, 0.5f, 0, 36.0f, -1.0f },  // death_forward_spin_face_up
	{  27, 1, -1.0f, 0.5f, 0, 36.0f, -1.0f },  // death_forward_spin_face_up
	{  28, 0, -1.0f, 0.5f, 1, 29.0f, -1.0f },  // death_backward_fall_face_up1
	{  28, 1, -1.0f, 0.5f, 1, 29.0f, -1.0f },  // death_backward_fall_face_up1
	{  33, 0, -1.0f, 0.5f, 0, 97.0f, 64.0f },  // death_forward_face_down_hard
	{  33, 1, -1.0f, 0.5f, 0, 97.0f, 64.0f },  // death_forward_face_down_hard
	{  35, 0, -1.0f, 0.5f, 0, 31.0f, -1.0f },  // death_fetal_position_right
	{  35, 1, -1.0f, 0.5f, 0, 31.0f, -1.0f },  // death_fetal_position_right
	{  36, 0, -1.0f, 0.5f, 0, 36.0f, -1.0f },  // death_fetal_position_left
	{  36, 1, -1.0f, 0.5f, 0, 36.0f, -1.0f },  // death_fetal_position_left
	{  37, 0, -1.0f, 0.5f, 0, 28.0f, -1.0f },  // death_backward_fall_face_up2
	{  37, 1, -1.0f, 0.5f, 0, 28.0f, -1.0f },  // death_backward_fall_face_up2
	{  22, 0, -1.0f, 0.5f, 0, 79.0f, 415.0f },  // death_genitalia
	{  22, 1, -1.0f, 0.5f, 0, 79.0f, 415.0f },  // death_genitalia
};

static const struct gestruck g_Ge_flinch_pelvis[] = {
	{  22, 0, 20.0f, 0.5f, 0, -1.0f, -1.0f },  // death_genitalia
	{  22, 1, 30.0f, 0.5f, 0, -1.0f, -1.0f },  // death_genitalia
	{  34, 0, 20.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down_soft
	{  34, 1, 20.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down_soft
	{  26, 0, 15.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down
	{  26, 1, 15.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down
	{  35, 0, 10.0f, 0.25f, 0, -1.0f, -1.0f },  // death_fetal_position_right
	{  35, 1, 10.0f, 0.25f, 0, -1.0f, -1.0f },  // death_fetal_position_right
};

static const struct gestruck g_Ge_death_head[] = {
	{  26, 0, -1.0f, 0.5f, 0, 55.0f, 39.0f },  // death_forward_face_down
	{  26, 1, -1.0f, 0.5f, 0, 55.0f, 39.0f },  // death_forward_face_down
	{  27, 0, -1.0f, 0.5f, 0, 36.0f, -1.0f },  // death_forward_spin_face_up
	{  27, 1, -1.0f, 0.5f, 0, 36.0f, -1.0f },  // death_forward_spin_face_up
	{  28, 0, -1.0f, 0.5f, 1, 29.0f, -1.0f },  // death_backward_fall_face_up1
	{  28, 1, -1.0f, 0.5f, 1, 29.0f, -1.0f },  // death_backward_fall_face_up1
	{  29, 0, -1.0f, 0.5f, 1, 25.0f, -1.0f },  // death_backward_spin_face_down_right
	{  29, 1, -1.0f, 0.5f, 1, 25.0f, -1.0f },  // death_backward_spin_face_down_right
	{  30, 0, -1.0f, 0.5f, 1, 23.0f, -1.0f },  // death_backward_spin_face_up_right
	{  30, 1, -1.0f, 0.5f, 1, 23.0f, -1.0f },  // death_backward_spin_face_up_right
	{  31, 0, -1.0f, 0.5f, 1, 27.0f, -1.0f },  // death_backward_spin_face_down_left
	{  31, 1, -1.0f, 0.5f, 1, 27.0f, -1.0f },  // death_backward_spin_face_down_left
	{  32, 0, -1.0f, 0.5f, 1, 26.0f, -1.0f },  // death_backward_spin_face_up_left
	{  32, 1, -1.0f, 0.5f, 1, 26.0f, -1.0f },  // death_backward_spin_face_up_left
	{  33, 0, -1.0f, 0.5f, 0, 97.0f, 64.0f },  // death_forward_face_down_hard
	{  33, 1, -1.0f, 0.5f, 0, 97.0f, 64.0f },  // death_forward_face_down_hard
	{  34, 0, -1.0f, 0.5f, 0, 94.0f, 66.0f },  // death_forward_face_down_soft
	{  34, 1, -1.0f, 0.5f, 0, 94.0f, 66.0f },  // death_forward_face_down_soft
	{  35, 0, -1.0f, 0.5f, 0, 31.0f, -1.0f },  // death_fetal_position_right
	{  35, 1, -1.0f, 0.5f, 0, 31.0f, -1.0f },  // death_fetal_position_right
	{  36, 0, -1.0f, 0.5f, 0, 36.0f, -1.0f },  // death_fetal_position_left
	{  36, 1, -1.0f, 0.5f, 0, 36.0f, -1.0f },  // death_fetal_position_left
	{  37, 0, -1.0f, 0.5f, 0, 28.0f, -1.0f },  // death_backward_fall_face_up2
	{  37, 1, -1.0f, 0.5f, 0, 28.0f, -1.0f },  // death_backward_fall_face_up2
	{  24, 0, -1.0f, 0.5f, 0, 87.0f, 203.0f },  // death_neck
	{  24, 1, -1.0f, 0.5f, 0, 87.0f, 203.0f },  // death_neck
	{  56, 0, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // death_head
	{  56, 1, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // death_head
};

static const struct gestruck g_Ge_flinch_head[] = {
	{  24, 0, 15.0f, 0.5f, 0, 87.0f, 203.0f },  // death_neck
	{  24, 1, 15.0f, 0.5f, 0, 87.0f, 203.0f },  // death_neck
	{  34, 0, 20.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down_soft
	{  34, 1, 20.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down_soft
	{  26, 0, 15.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down
	{  26, 1, 15.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down
};

static const struct gestruck g_Ge_death_left_hand[] = {
	{  31, 0, -1.0f, 0.5f, 0, 27.0f, -1.0f },  // death_backward_spin_face_down_left
	{  32, 0, -1.0f, 0.5f, 0, 26.0f, -1.0f },  // death_backward_spin_face_up_left
	{  29, 1, -1.0f, 0.5f, 0, 25.0f, -1.0f },  // death_backward_spin_face_down_right
	{  30, 1, -1.0f, 0.5f, 0, 23.0f, -1.0f },  // death_backward_spin_face_up_right
};

static const struct gestruck g_Ge_flinch_left_hand[] = {
	{  18, 0, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_left_hand
	{  19, 1, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_right_hand
};

static const struct gestruck g_Ge_death_left_arm[] = {
	{  31, 0, -1.0f, 0.5f, 0, 27.0f, -1.0f },  // death_backward_spin_face_down_left
	{  32, 0, -1.0f, 0.5f, 0, 26.0f, -1.0f },  // death_backward_spin_face_up_left
	{  29, 1, -1.0f, 0.5f, 0, 25.0f, -1.0f },  // death_backward_spin_face_down_right
	{  30, 1, -1.0f, 0.5f, 0, 23.0f, -1.0f },  // death_backward_spin_face_up_right
};

static const struct gestruck g_Ge_flinch_left_arm[] = {
	{  16, 0, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_left_arm
	{  17, 1, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_right_arm
};

static const struct gestruck g_Ge_death_left_shoulder[] = {
	{  31, 0, -1.0f, 0.5f, 1, 27.0f, -1.0f },  // death_backward_spin_face_down_left
	{  32, 0, -1.0f, 0.5f, 1, 26.0f, -1.0f },  // death_backward_spin_face_up_left
	{  29, 1, -1.0f, 0.5f, 1, 25.0f, -1.0f },  // death_backward_spin_face_down_right
	{  30, 1, -1.0f, 0.5f, 1, 23.0f, -1.0f },  // death_backward_spin_face_up_right
};

static const struct gestruck g_Ge_flinch_left_shoulder[] = {
	{  14, 0, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_left_shoulder
	{  15, 1, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_right_shoulder
	{  34, 0, 20.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down_soft
};

static const struct gestruck g_Ge_death_right_hand[] = {
	{  29, 0, -1.0f, 0.5f, 0, 25.0f, -1.0f },  // death_backward_spin_face_down_right
	{  30, 0, -1.0f, 0.5f, 0, 23.0f, -1.0f },  // death_backward_spin_face_up_right
	{  31, 1, -1.0f, 0.5f, 0, 27.0f, -1.0f },  // death_backward_spin_face_down_left
	{  32, 1, -1.0f, 0.5f, 0, 26.0f, -1.0f },  // death_backward_spin_face_up_left
};

static const struct gestruck g_Ge_flinch_right_hand[] = {
	{  19, 0, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_right_hand
	{  18, 1, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_left_hand
};

static const struct gestruck g_Ge_death_right_arm[] = {
	{  29, 0, -1.0f, 0.5f, 0, 25.0f, -1.0f },  // death_backward_spin_face_down_right
	{  30, 0, -1.0f, 0.5f, 0, 23.0f, -1.0f },  // death_backward_spin_face_up_right
	{  31, 1, -1.0f, 0.5f, 0, 27.0f, -1.0f },  // death_backward_spin_face_down_left
	{  32, 1, -1.0f, 0.5f, 0, 26.0f, -1.0f },  // death_backward_spin_face_up_left
};

static const struct gestruck g_Ge_flinch_right_arm[] = {
	{  17, 0, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_right_arm
	{  16, 1, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_left_arm
};

static const struct gestruck g_Ge_death_right_shoulder[] = {
	{  29, 0, -1.0f, 0.5f, 1, 25.0f, -1.0f },  // death_backward_spin_face_down_right
	{  30, 0, -1.0f, 0.5f, 1, 23.0f, -1.0f },  // death_backward_spin_face_up_right
	{  31, 1, -1.0f, 0.5f, 1, 27.0f, -1.0f },  // death_backward_spin_face_down_left
	{  32, 1, -1.0f, 0.5f, 1, 26.0f, -1.0f },  // death_backward_spin_face_up_left
};

static const struct gestruck g_Ge_flinch_right_shoulder[] = {
	{  15, 0, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_right_shoulder
	{  14, 1, -1.0f, 0.5f, 0, -1.0f, -1.0f },  // hit_left_shoulder
	{  34, 1, 20.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down_soft
};

static const struct gestruck g_Ge_death_chest[] = {
	{  26, 0, -1.0f, 0.5f, 0, 55.0f, 39.0f },  // death_forward_face_down
	{  26, 1, -1.0f, 0.5f, 0, 55.0f, 39.0f },  // death_forward_face_down
	{  27, 0, -1.0f, 0.5f, 0, 36.0f, -1.0f },  // death_forward_spin_face_up
	{  27, 1, -1.0f, 0.5f, 0, 36.0f, -1.0f },  // death_forward_spin_face_up
	{  28, 0, -1.0f, 0.5f, 1, 29.0f, -1.0f },  // death_backward_fall_face_up1
	{  28, 1, -1.0f, 0.5f, 1, 29.0f, -1.0f },  // death_backward_fall_face_up1
	{  29, 0, -1.0f, 0.5f, 1, 25.0f, -1.0f },  // death_backward_spin_face_down_right
	{  29, 1, -1.0f, 0.5f, 1, 25.0f, -1.0f },  // death_backward_spin_face_down_right
	{  30, 0, -1.0f, 0.5f, 1, 23.0f, -1.0f },  // death_backward_spin_face_up_right
	{  30, 1, -1.0f, 0.5f, 1, 23.0f, -1.0f },  // death_backward_spin_face_up_right
	{  31, 0, -1.0f, 0.5f, 1, 27.0f, -1.0f },  // death_backward_spin_face_down_left
	{  31, 1, -1.0f, 0.5f, 1, 27.0f, -1.0f },  // death_backward_spin_face_down_left
	{  32, 0, -1.0f, 0.5f, 1, 26.0f, -1.0f },  // death_backward_spin_face_up_left
	{  32, 1, -1.0f, 0.5f, 1, 26.0f, -1.0f },  // death_backward_spin_face_up_left
	{  33, 0, -1.0f, 0.5f, 0, 97.0f, 64.0f },  // death_forward_face_down_hard
	{  33, 1, -1.0f, 0.5f, 0, 97.0f, 64.0f },  // death_forward_face_down_hard
	{  34, 0, -1.0f, 0.5f, 0, 94.0f, 66.0f },  // death_forward_face_down_soft
	{  34, 1, -1.0f, 0.5f, 0, 94.0f, 66.0f },  // death_forward_face_down_soft
	{  35, 0, -1.0f, 0.5f, 0, 31.0f, -1.0f },  // death_fetal_position_right
	{  35, 1, -1.0f, 0.5f, 0, 31.0f, -1.0f },  // death_fetal_position_right
	{  36, 0, -1.0f, 0.5f, 0, 36.0f, -1.0f },  // death_fetal_position_left
	{  36, 1, -1.0f, 0.5f, 0, 36.0f, -1.0f },  // death_fetal_position_left
	{  37, 0, -1.0f, 0.5f, 0, 28.0f, -1.0f },  // death_backward_fall_face_up2
	{  37, 1, -1.0f, 0.5f, 0, 28.0f, -1.0f },  // death_backward_fall_face_up2
};

static const struct gestruck g_Ge_flinch_chest[] = {
	{  34, 0, 20.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down_soft
	{  34, 1, 20.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down_soft
	{  26, 0, 15.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down
	{  26, 1, 15.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down
};

static const struct gestruck g_Ge_death_gun[] = {
	{  26, 0, -1.0f, 0.5f, 0, 55.0f, 39.0f },  // death_forward_face_down
	{  26, 1, -1.0f, 0.5f, 0, 55.0f, 39.0f },  // death_forward_face_down
	{  27, 0, -1.0f, 0.5f, 0, 36.0f, -1.0f },  // death_forward_spin_face_up
	{  27, 1, -1.0f, 0.5f, 0, 36.0f, -1.0f },  // death_forward_spin_face_up
	{  28, 0, -1.0f, 0.5f, 1, 29.0f, -1.0f },  // death_backward_fall_face_up1
	{  28, 1, -1.0f, 0.5f, 1, 29.0f, -1.0f },  // death_backward_fall_face_up1
	{  33, 0, -1.0f, 0.5f, 0, 97.0f, 64.0f },  // death_forward_face_down_hard
	{  33, 1, -1.0f, 0.5f, 0, 97.0f, 64.0f },  // death_forward_face_down_hard
	{  34, 0, -1.0f, 0.5f, 0, 94.0f, 66.0f },  // death_forward_face_down_soft
	{  34, 1, -1.0f, 0.5f, 0, 94.0f, 66.0f },  // death_forward_face_down_soft
	{  35, 0, -1.0f, 0.5f, 0, 31.0f, -1.0f },  // death_fetal_position_right
	{  35, 1, -1.0f, 0.5f, 0, 31.0f, -1.0f },  // death_fetal_position_right
	{  36, 0, -1.0f, 0.5f, 0, 36.0f, -1.0f },  // death_fetal_position_left
	{  36, 1, -1.0f, 0.5f, 0, 36.0f, -1.0f },  // death_fetal_position_left
	{  37, 0, -1.0f, 0.5f, 0, 28.0f, -1.0f },  // death_backward_fall_face_up2
	{  37, 1, -1.0f, 0.5f, 0, 28.0f, -1.0f },  // death_backward_fall_face_up2
};

static const struct gestruck g_Ge_flinch_gun[] = {
	{  34, 0, 20.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down_soft
	{  34, 1, 20.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down_soft
	{  26, 0, 15.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down
	{  26, 1, 15.0f, 0.5f, 0, -1.0f, -1.0f },  // death_forward_face_down
};

static const struct gestruck g_Ge_death_stagger[] = {
	{  25, 0, -1.0f, 0.5f, 0, 67.0f, 54.0f },  // death_stagger_back_to_wall
	{  25, 1, -1.0f, 0.5f, 0, 67.0f, 54.0f },  // death_stagger_back_to_wall
};

#define GE_STRUCK(a) a, (s32)(sizeof(a) / sizeof(a[0]))

static const struct { s32 hitpart; const struct gestruck *death; s32 numdeath; const struct gestruck *flinch; s32 numflinch; } g_GeHitReactions[] = {
	{ HITPART_LFOOT, GE_STRUCK(g_Ge_death_left_foot), GE_STRUCK(g_Ge_flinch_left_foot) },
	{ HITPART_LSHIN, GE_STRUCK(g_Ge_death_left_leg), GE_STRUCK(g_Ge_flinch_left_leg) },
	{ HITPART_LTHIGH, GE_STRUCK(g_Ge_death_left_thigh), GE_STRUCK(g_Ge_flinch_left_thigh) },
	{ HITPART_RFOOT, GE_STRUCK(g_Ge_death_right_foot), GE_STRUCK(g_Ge_flinch_right_foot) },
	{ HITPART_RSHIN, GE_STRUCK(g_Ge_death_right_leg), GE_STRUCK(g_Ge_flinch_right_leg) },
	{ HITPART_RTHIGH, GE_STRUCK(g_Ge_death_right_thigh), GE_STRUCK(g_Ge_flinch_right_thigh) },
	{ HITPART_PELVIS, GE_STRUCK(g_Ge_death_pelvis), GE_STRUCK(g_Ge_flinch_pelvis) },
	{ HITPART_HEAD, GE_STRUCK(g_Ge_death_head), GE_STRUCK(g_Ge_flinch_head) },
	{ HITPART_LHAND, GE_STRUCK(g_Ge_death_left_hand), GE_STRUCK(g_Ge_flinch_left_hand) },
	{ HITPART_LFOREARM, GE_STRUCK(g_Ge_death_left_arm), GE_STRUCK(g_Ge_flinch_left_arm) },
	{ HITPART_LBICEP, GE_STRUCK(g_Ge_death_left_shoulder), GE_STRUCK(g_Ge_flinch_left_shoulder) },
	{ HITPART_RHAND, GE_STRUCK(g_Ge_death_right_hand), GE_STRUCK(g_Ge_flinch_right_hand) },
	{ HITPART_RFOREARM, GE_STRUCK(g_Ge_death_right_arm), GE_STRUCK(g_Ge_flinch_right_arm) },
	{ HITPART_RBICEP, GE_STRUCK(g_Ge_death_right_shoulder), GE_STRUCK(g_Ge_flinch_right_shoulder) },
	{ HITPART_TORSO, GE_STRUCK(g_Ge_death_chest), GE_STRUCK(g_Ge_flinch_chest) },
	{ HITPART_GUN, GE_STRUCK(g_Ge_death_gun), GE_STRUCK(g_Ge_flinch_gun) },
};

// geid, flip, speed, start frame, thud frame, end frame
struct geblast { u8 geid; u8 flip; f32 speed; f32 startframe; f32 thudframe; f32 endframe; };

static const struct geblast g_GeBlasts[] = {
	{ 130, 0, 0.5f, 9.0f, 29.0f, -1.0f },  // death_explosion_forward
	{ 130, 1, 0.5f, 9.0f, 29.0f, -1.0f },  // death_explosion_forward
	{ 138, 0, 0.5f, 11.0f, 31.0f, -1.0f },  // death_explosion_forward_face_down
	{ 138, 1, 0.5f, 11.0f, 31.0f, -1.0f },  // death_explosion_forward_face_down
	{ 137, 0, 0.5f, 6.0f, 27.0f, -1.0f },  // death_explosion_forward_roll
	{ 137, 1, 0.5f, 6.0f, 27.0f, -1.0f },  // death_explosion_forward_roll
	{ 140, 0, 0.5f, 29.0f, 48.0f, -1.0f },  // death_explosion_forward_right2
	{ 140, 1, 0.5f, 29.0f, 48.0f, -1.0f },  // death_explosion_forward_right2
	{ 141, 0, 0.5f, 29.0f, 49.0f, -1.0f },  // death_explosion_forward_right2_alt
	{ 141, 1, 0.5f, 29.0f, 49.0f, -1.0f },  // death_explosion_forward_right2_alt
	{ 142, 0, 0.5f, 19.0f, 42.0f, -1.0f },  // death_explosion_forward_right3
	{ 142, 1, 0.5f, 19.0f, 42.0f, -1.0f },  // death_explosion_forward_right3
	{ 131, 0, 0.5f, 9.0f, 29.0f, 55.0f },  // death_explosion_left1
	{ 131, 1, 0.5f, 9.0f, 29.0f, 55.0f },  // death_explosion_left1
	{ 134, 0, 0.5f, 6.0f, 27.0f, -1.0f },  // death_explosion_right
	{ 134, 1, 0.5f, 6.0f, 27.0f, -1.0f },  // death_explosion_right
	{ 135, 0, 0.5f, 6.0f, 29.0f, -1.0f },  // death_explosion_forward_right1
	{ 135, 1, 0.5f, 6.0f, 29.0f, -1.0f },  // death_explosion_forward_right1
	{ 132, 0, 0.5f, 8.0f, 25.0f, -1.0f },  // death_explosion_back_left
	{ 132, 1, 0.5f, 8.0f, 25.0f, -1.0f },  // death_explosion_back_left
	{ 133, 0, 0.5f, 8.0f, 25.0f, -1.0f },  // death_explosion_back1
	{ 133, 1, 0.5f, 8.0f, 25.0f, -1.0f },  // death_explosion_back1
	{ 136, 0, 0.5f, 12.0f, 29.0f, -1.0f },  // death_explosion_back2
	{ 136, 1, 0.5f, 12.0f, 29.0f, -1.0f },  // death_explosion_back2
	{ 139, 0, 0.5f, 22.0f, 41.0f, -1.0f },  // death_explosion_left2
	{ 139, 1, 0.5f, 22.0f, 41.0f, -1.0f },  // death_explosion_left2
};

static const struct { s8 rows[8]; s32 count; } g_GeBlastSides[8] = {
	{ { 0, 1, 2, 3, 4, 5, 0, 0 }, 6 },  // expl_forward
	{ { 7, 9, 11, 0 }, 3 },  // expl_f_left
	{ { 12, 15, 17, 0 }, 3 },  // expl_left
	{ { 18, 24, 0, 0 }, 2 },  // expl_b_right
	{ { 20, 21, 22, 23 }, 4 },  // expl_back
	{ { 19, 25, 0, 0 }, 2 },  // expl_b_left
	{ { 13, 14, 16, 0 }, 3 },  // expl_right
	{ { 6, 8, 10, 0 }, 3 },  // expl_f_right
};

#endif
