// Generated by tools/langfont/bake.py - do not edit.
// M PLUS Rounded 1c (SIL Open Font License 1.1, tools/langfont/fonts/OFL.txt),
// baked into Perfect Dark's glyph format. See tools/langfont/README.md.
#ifndef _IN_LANGFONT_CJK_H
#define _IN_LANGFONT_CJK_H

#include <PR/ultratypes.h>

#define LANGFONT_CJK_COUNT 3358

// cell sizes: small for xs/sm/md, big for lg
#define LANGFONT_CJK_SMALL_W 12
#define LANGFONT_CJK_SMALL_H 11
#define LANGFONT_CJK_BIG_W 14
#define LANGFONT_CJK_BIG_H 15

/**
 * The glyph of code point cp, or NULL if the font has none.
 *
 * CI4 in the ROM fonts' layout: 16 texels (8 bytes) a row, *height + 2 rows,
 * body in indices 9-15 and the outline band in 1-7 (var8007fb5c); texel
 * (1, 1) is the cell's top left, so it is drawn at x - 1, y - 1 over
 * *width + 2 columns like any ROM glyph. *width is the advance too (the font
 * is monospaced and the gap is inside the cell). *baseline is the fontchar
 * field: rows from the line's top to the cell's.
 *
 * big selects the 15 row class (the lg font); otherwise 11 rows.
 * The pointer stays valid and unchanged for the life of the program.
 */
const u8 *langfontCjkGlyph(u32 cp, s32 big, u8 *width, u8 *height, s8 *baseline);

/**
 * The same glyph as I8 for GE Plus's front end (struct gefont): body alone,
 * no band, rows of (*width + 7) & ~7 bytes, *height rows, 0x00-0xff.
 */
const u8 *langfontCjkGlyphI8(u32 cp, s32 big, u8 *width, u8 *height, s8 *baseline);

// whether the font has cp
s32 langfontCjkHas(u32 cp);

#endif
