/**
 * Generated by tools/xblaxex/gentables.py from the XBLA release's image. Do not edit.
 *
 * The fields of the game's tables the release changed: the field, the N64
 * value and the release's, as the raw bits of the field. See xblatables.c.
 */

#ifndef _IN_XBLATABLESDATA_H
#define _IN_XBLATABLESDATA_H

static const struct xblatabfield xblaTabFields[] = {
	// g_SmokeTypes: release 0x825cd3e8, 95.0% of words agree
	XBLATAB(g_SmokeTypes[6].spreadspeed, 0x0046, 0x0028), // 70 -> 40
	XBLATAB(g_SmokeTypes[6].fgrotatespeed, 0x3e99999a, 0x3e6147ae), // 0.3 -> 0.22
	XBLATAB(g_SmokeTypes[7].size, 0x000f, 0x0007), // 15 -> 7
	XBLATAB(g_SmokeTypes[7].bgrotatespeed, 0x3cf5c28f, 0x3c75c28f), // 0.03 -> 0.015
	XBLATAB(g_SmokeTypes[7].fgrotatespeed, 0x3e99999a, 0x3f000000), // 0.3 -> 0.5
	XBLATAB(g_SmokeTypes[7].numclouds, 0x0078, 0x0096), // 120 -> 150
	XBLATAB(g_SmokeTypes[7].unk18, 0x3e19999a, 0x3d8f5c29), // 0.15 -> 0.07
	XBLATAB(g_SmokeTypes[7].unk1c, 0x3e99999a, 0x3ecccccd), // 0.3 -> 0.4
	XBLATAB(g_SmokeTypes[8].fgrotatespeed, 0x40000000, 0x3fc00000), // 2 -> 1.5
	XBLATAB(g_SmokeTypes[8].numclouds, 0x001e, 0x000a), // 30 -> 10
	// g_FogEnvironments: release 0x825c1288, 98.5% of words agree
	XBLATAB(g_FogEnvironments[0].far, 0x2710, 0x4e20), // 10000 -> 20000
	XBLATAB(g_FogEnvironments[0].fogmin, 0x03e2, 0x03e1), // 994 -> 993
	XBLATAB(g_FogEnvironments[0].fogmax, 0x03e8, 0x03e7), // 1000 -> 999
};

static const struct xblatabtype xblaTabTypes[] = {
	{ 0x04, 1, 6 }, // FILE_CHEADDARK_COMBAT
	{ 0x07, 0, 7 }, // FILE_CHEADCARRINGTON
	{ 0x09, 0, 8 }, // FILE_CHEADTRENT
	{ 0x0c, 1, 6 }, // FILE_CHEADDARK_FROCK
	{ 0x2f, 1, 6 }, // FILE_CHEADDARKAQUA
	{ 0x38, 1, 0 }, // FILE_CHEADWINNER
	{ 0x3c, 1, 6 }, // FILE_CHEADDARK_SNOW
	{ 0x3e, 1, 6 }, // FILE_CHEAD_VD
	{ 0x43, 0, 1 }, // FILE_CHEADPENNY
	{ 0x56, 1, 6 }, // FILE_CDARK_COMBAT
	{ 0x5a, 0, 7 }, // FILE_CCARRINGTON
	{ 0x5d, 0, 8 }, // FILE_CTRENT
	{ 0x61, 1, 6 }, // FILE_CDARK_FROCK
	{ 0x62, 1, 6 }, // FILE_CDARK_TRENCH
	{ 0x6d, 1, 6 }, // FILE_CDARK_RIPPED
	{ 0x86, 1, 6 }, // FILE_CDARK_AF1
	{ 0x87, 1, 6 }, // FILE_CDARKWET
	{ 0x88, 1, 6 }, // FILE_CDARKAQUALUNG
	{ 0x89, 1, 6 }, // FILE_CDARKSNOW
	{ 0x8a, 1, 6 }, // FILE_CDARKLAB
	{ 0x90, 0, 7 }, // FILE_CCARREVENINGSUIT
	{ 0x95, 1, 6 }, // FILE_CDARK_LEATHER
	{ 0x96, 1, 6 }, // FILE_CDARK_NEGOTIATOR
};

#endif
