#!/usr/bin/env python3
"""Write port/src/gegunstats.h from GoldenEye's decompiled weapon stats.

Each of GoldenEye's guns keeps its numbers in obseg/gun/<name>/gunWeaponStat.inc.c
as one WeaponStats row, whose fields gun.h names. Perfect Dark's own conversions
of those guns carry the same numbers - the DD44's 1 damage, 6 spread, 8 rounds
and 16 frame recovery are the tt33's Destruction, Inaccuracy, MagSize and
SingleRate - so they are written out as they stand, with no scaling.

Also each row's AmmoType (GoldenEye's AMMOTYPES index) and BitFlags (its
WEAPONSTATBITFLAG_* word), which geguns.c builds a definition's ammunition and
flags from rather than taking its host's.
"""
import os, re, sys

DECOMP = next(d for d in (os.path.expanduser("~/claude-007/007/assets/obseg/gun"),
                          os.path.expanduser("~/perfect-dark/007/assets/obseg/gun")) if os.path.isdir(d))
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "port", "src", "gegunstats.h")
CONSTANTS = os.path.join(DECOMP, "..", "..", "..", "src", "bondconstants.h")

# The GoldenEye weapon, and the decomp's own directory for it
GUNS = [
    ("WEAPON_GE_PP7", "wppk"), ("WEAPON_GE_PP7SILENCED", "wppksil"),
    ("WEAPON_GE_DD44", "tt33"), ("WEAPON_GE_KLOBB", "skorpion"),
    ("WEAPON_GE_KF7SOVIET", "ak47"), ("WEAPON_GE_ZMG", "uzi"),
    ("WEAPON_GE_D5K", "mp5k"), ("WEAPON_GE_D5KSILENCED", "mp5ksil"),
    ("WEAPON_GE_PHANTOM", "spectre"), ("WEAPON_GE_AR33", "m16"),
    ("WEAPON_GE_RCP90", "fnp90"), ("WEAPON_GE_SHOTGUN", "shotgun"),
    ("WEAPON_GE_AUTOSHOTGUN", "autoshot"), ("WEAPON_GE_SNIPERRIFLE", "sniperrifle"),
    ("WEAPON_GE_COUGARMAGNUM", "ruger"), ("WEAPON_GE_GOLDENGUN", "goldengun"),
    ("WEAPON_GE_MOONRAKER", "laser"), ("WEAPON_GE_GRENADELAUNCHER", "grenadelaunch"),
    ("WEAPON_GE_ROCKETLAUNCHER", "rocketlaunch"), ("WEAPON_GE_HUNTINGKNIFE", "knife"),
    ("WEAPON_GE_THROWINGKNIFE", "throwknife"), ("WEAPON_GE_GRENADE", "grenade"),
    ("WEAPON_GE_TIMEDMINE", "timedmine"), ("WEAPON_GE_PROXIMITYMINE", "proximitymine"),
    ("WEAPON_GE_REMOTEMINE", "remotemine"),
]

FIELDS = ["MuzzleFlash", "PosX", "PosY", "PosZ", "PlayX", "PlayY", "PlayZ", "AmmoType",
          "MagSize", "AutoRate", "SingleRate", "ShootThrough", "SoundTrigRate", "Sound",
          "Cartridge", "Destruction", "Inaccuracy", "Zoom", "CrosshairSpeed", "AimLockSpeed",
          "Sway", "RecoilSpeed", "RecoilBack", "RecoilUp", "BoltRecoilBack", "LoudMin",
          "LoudMax", "NoisePerShot", "NoiseLinearTime", "NoiseScaledTime", "ForceOfImpact"]


def constants():
    """GoldenEye's WEAPONSTATBITFLAG_* values and its AMMOTYPES order."""
    text = open(CONSTANTS).read()
    bits = {m.group(1): int(m.group(2), 0)
            for m in re.finditer(r"#define (WEAPONSTATBITFLAG_\w+)\s+(0x[0-9a-fA-F]+)", text)}
    enum = text[text.index("AMMO_NONE"):]
    enum = enum[:enum.index("}")]
    ammo = {}
    for tok in re.findall(r"\b(AMMO_\w+)\b(?!\s*=\s*AMMO)", enum):
        if tok not in ammo:
            ammo[tok] = len(ammo)
    return bits, ammo


def read(src, bits, ammo):
    path = os.path.join(DECOMP, src, "gunWeaponStat.inc.c")
    body = re.sub(r"//[^\n]*", "", open(path).read())
    body = body[body.index("{") + 1:]
    flags = 0
    if "WEAPONSTATBITFLAG" in body:
        for name in re.findall(r"WEAPONSTATBITFLAG_\w+", body):
            flags |= bits[name]
        body = body[:body.index("WEAPONSTATBITFLAG")]
    toks = [t.strip() for t in body.split(",") if t.strip()]
    row = dict(zip(FIELDS, toks))
    row["AmmoType"] = ammo[row["AmmoType"]]
    row["BitFlags"] = flags
    return row


def main():
    bits, ammo = constants()
    rows = []
    for weapon, src in GUNS:
        s = read(src, bits, ammo)
        # RecoilSpeed is four bytes, big-endian in the word (gun.h's b44[4])
        speed = int(s["RecoilSpeed"], 0) & 0xffffffff
        speed = [(speed >> sh) & 0xff for sh in (24, 16, 8, 0)]
        speed = [b - 256 if b > 127 else b for b in speed]
        rows.append("\tGUNSTAT(%s, \"%s\", %d, 0x%02x, 0x%02x, %d, %sf, %sf, %sf, %sf, %sf, %sf, %sf, %sf,\n"
                    "\t\t%d, %d, %d, %d, %sf, %sf, %sf, %sf, %sf, %sf, %d, 0x%08x),\n" % (
            weapon, src, int(s["MagSize"], 0), int(s["AutoRate"], 0) & 0xff,
            int(s["SingleRate"], 0) & 0xff, int(s["ShootThrough"], 0),
            s["Destruction"], s["Inaccuracy"], s["ForceOfImpact"],
            s["LoudMin"], s["LoudMax"], s["NoisePerShot"], s["NoiseLinearTime"], s["NoiseScaledTime"],
            speed[0], speed[1], speed[2], speed[3], s["RecoilBack"], s["RecoilUp"], s["BoltRecoilBack"],
            s["Sway"], s["Zoom"], s["MuzzleFlash"], s["AmmoType"], s["BitFlags"]))
    with open(OUT, "w") as f:
        f.write("// Generated by tools/geguns/gen_gunstats.py from GoldenEye's decomp\n"
                "// (obseg/gun/<source>/gunWeaponStat.inc.c, fields named by its gun.h):\n"
                "// GoldenEye's own numbers for each of its guns, as they stand. Perfect\n"
                "// Dark's conversions of these guns carry the same numbers - the DD44's 1\n"
                "// damage, 6 spread, 8 rounds and 16 frame recovery are the tt33's\n"
                "// Destruction, Inaccuracy, MagSize and SingleRate - so nothing is scaled.\n"
                "// weapon, source, magazine, automatic rate, single rate, objects shot\n"
                "// through, destruction (damage), inaccuracy (spread), force of impact,\n"
                "// then how loud it is: the least and most a guard hears it from (x100\n"
                "// units), what a shot adds, and the two times the noise dies away over;\n"
                "// then how it handles: the four recoil speed bytes, how far the hands\n"
                "// pull back, how far the gun kicks up, how far the bolt slides, the\n"
                "// sway, the aim zoom and how far the flash sits past the barrel; then\n"
                "// GoldenEye's ammunition type (its AMMOTYPES index) and its BitFlags\n")
        f.writelines(rows)
    print("wrote %s, %d rows" % (OUT, len(rows)))


main()
